// $Id: ListWorkerQtyInquiry.java,v 1.2 2006/11/13 08:20:53 suresh Exp $

//#CM693018
/*
 * Copyright 2000-2001 DAIFUKU Co.,Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of DAIFUKU Co.,Ltd.
 * Use is subject to license terms.
 */
package jp.co.daifuku.wms.base.system.display.web.listbox.listworkerqtyinquiry;
import jp.co.daifuku.bluedog.ui.control.Page;

//#CM693019
/**
 * Non variable class generated by a tool.
 * 
 * <BR>
 * <TABLE BORDER="1" CELLPADDING="3" CELLSPACING="0">
 * <TR BGCOLOR="#CCCCFF" CLASS="TableHeadingColor"><TD>Date</TD><TD>Name</TD><TD>Comment</TD></TR>
 * <TR><TD>2004/02/13</TD><TD>N.Sawa(DFK)</TD><TD>created this class</TD></TR>
 * </TABLE>
 * <BR>
 * @version $Revision: 1.2 $, $Date: 2006/11/13 08:20:53 $
 * @author  $Author: suresh $
 */
public class ListWorkerQtyInquiry extends Page
{

	//#CM693020
	// Class variables -----------------------------------------------
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ListName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ListName" , "In_SettingName");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_SearchCondition = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_SearchCondition" , "W_SearchCondition");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_WorkDetails = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_WorkDetails" , "W_WorkDetails");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_JavaSetWkCtx = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_JavaSetWkCtx" , "W_JavaSet");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_WorkDate = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_WorkDate" , "W_WorkDate");
	public jp.co.daifuku.bluedog.ui.control.DateTextBox txt_FDateStart = jp.co.daifuku.bluedog.ui.control.DateTextBoxFactory.getInstance("txt_FDateStart" , "W_F_Date");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_FromTo = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_FromTo" , "W_FromTo");
	public jp.co.daifuku.bluedog.ui.control.DateTextBox txt_FDateEnd = jp.co.daifuku.bluedog.ui.control.DateTextBoxFactory.getInstance("txt_FDateEnd" , "W_F_Date");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_WorkerCode = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_WorkerCode" , "W_WorkerCode");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_JavaSetWkCd = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_JavaSetWkCd" , "W_JavaSet");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_GroupCondition = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_GroupCondition" , "W_GroupCondition");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_JavaSetGcd = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_JavaSetGcd" , "W_JavaSet");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Close_U = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Close_U" , "Close");
	public jp.co.daifuku.bluedog.ui.control.Pager pgr_U = jp.co.daifuku.bluedog.ui.control.PagerFactory.getInstance("pgr_U" , "Pager");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_InMsg = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_InMsg" , "In_ErrorJsp");
	public jp.co.daifuku.bluedog.ui.control.ListCell lst_SWkrRsltIqr = jp.co.daifuku.bluedog.ui.control.ListCellFactory.getInstance("lst_SWkrRsltIqr" , "W_S_WkrRsltIqr");
	public jp.co.daifuku.bluedog.ui.control.Pager pgr_D = jp.co.daifuku.bluedog.ui.control.PagerFactory.getInstance("pgr_D" , "Pager");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Close_D = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Close_D" , "Close");

}
//#CM693021
//end of class
