// $Id: ReportDataEnvironment.java,v 1.2 2006/11/13 08:21:38 suresh Exp $

//#CM694013
/*
 * Copyright 2000-2001 DAIFUKU Co.,Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of DAIFUKU Co.,Ltd.
 * Use is subject to license terms.
 */
package jp.co.daifuku.wms.base.system.display.web.reportdataenvironment;
import jp.co.daifuku.bluedog.ui.control.Page;

//#CM694014
/**
 * Non variable class generated by a tool.
 * 
 * <BR>
 * <TABLE BORDER="1" CELLPADDING="3" CELLSPACING="0">
 * <TR BGCOLOR="#CCCCFF" CLASS="TableHeadingColor"><TD>Date</TD><TD>Name</TD><TD>Comment</TD></TR>
 * <TR><TD>2004/02/13</TD><TD>N.Sawa(DFK)</TD><TD>created this class</TD></TR>
 * </TABLE>
 * <BR>
 * @version $Revision: 1.2 $, $Date: 2006/11/13 08:21:38 $
 * @author  $Author: suresh $
 */
public class ReportDataEnvironment extends Page
{

	//#CM694015
	// Class variables -----------------------------------------------
	public jp.co.daifuku.bluedog.ui.control.Label lbl_SettingName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_SettingName" , "In_SettingName");
	public jp.co.daifuku.bluedog.ui.control.LinkButton btn_Help = jp.co.daifuku.bluedog.ui.control.LinkButtonFactory.getInstance("btn_Help" , "Help");
	public jp.co.daifuku.bluedog.ui.control.Message message = jp.co.daifuku.bluedog.ui.control.MessageFactory.getInstance("message" , "OperationMsg");
	public jp.co.daifuku.bluedog.ui.control.Tab tab_Set = jp.co.daifuku.bluedog.ui.control.TabFactory.getInstance("tab_Set" , "W_Set");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_ToMenu = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_ToMenu" , "To_Menu");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_WorkerCode = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_WorkerCode" , "W_WorkerCode");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_WorkerCode = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_WorkerCode" , "W_WorkerCode");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Password = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Password" , "W_Password");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_Password = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_Password" , "W_Password");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_InstkRsltFld = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_InstkRsltFld" , "W_InstkRsltFld");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_InstkRsltFld = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_InstkRsltFld" , "W_InstkRsltFld");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_ReferenceInstk = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_ReferenceInstk" , "W_Reference");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_InstkRsltFileNm = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_InstkRsltFileNm" , "W_InstkRsltFileNm");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_InstkRsltFileNm = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_InstkRsltFileNm" , "W_InstkRsltFileNm");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_StrgRsltFld = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_StrgRsltFld" , "W_StrgRsltFld");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_StrgRsltFld = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_StrgRsltFld" , "W_StrgRsltFld");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_ReferenceStrg = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_ReferenceStrg" , "W_Reference");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_StrgRsltFileNm = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_StrgRsltFileNm" , "W_StrgRsltFileNm");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_StrgRsltFileNm = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_StrgRsltFileNm" , "W_StrgRsltFileNm");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_RtrivlRsltDataFld = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_RtrivlRsltDataFld" , "W_RtrivlRsltDataFld");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_RtrivlRsltFld = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_RtrivlRsltFld" , "W_RtrivlRsltFld");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_ReferenceRtrivl = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_ReferenceRtrivl" , "W_Reference");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_RtrivlRsltFileNm = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_RtrivlRsltFileNm" , "W_RtrivlRsltFileNm");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_RtrivlRsltFileNm = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_RtrivlRsltFileNm" , "W_RtrivlRsltFileNm");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_PickRsltDataFld = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_PickRsltDataFld" , "W_PickRsltDataFld");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_PickRsltFld = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_PickRsltFld" , "W_PickRsltFld");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_ReferencePick = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_ReferencePick" , "W_Reference");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_PickRsltDataFileNm = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_PickRsltDataFileNm" , "W_PickRsltDataFileNm");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_PickRsltFileNm = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_PickRsltFileNm" , "W_PickRsltFileNm");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ShpRsltFld = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ShpRsltFld" , "W_ShpRsltFld");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_ShpRsltFld = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_ShpRsltFld" , "W_ShpRsltFld");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_ReferenceShp = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_ReferenceShp" , "W_Reference");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ShpRsltFileNm = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ShpRsltFileNm" , "W_ShpRsltFileNm");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_ShpRsltFileNm = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_ShpRsltFileNm" , "W_ShpRsltFileNm");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_StockMovRsltFld = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_StockMovRsltFld" , "W_StockMovRsltFld");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_StockMovRsltFld = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_StockMovRsltFld" , "W_StockMovRsltFld");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_ReferenceStock = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_ReferenceStock" , "W_Reference");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_StockMovRsltFileNm = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_StockMovRsltFileNm" , "W_StockMovRsltFileNm");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_StockMovRsltFileNm = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_StockMovRsltFileNm" , "W_StockMovRsltFileNm");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_InvntryRsltFld = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_InvntryRsltFld" , "W_InvntryRsltFld");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_InvntryRsltFld = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_InvntryRsltFld" , "W_InvntryRsltFld");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_ReferenceInventory = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_ReferenceInventory" , "W_Reference");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_InvntryRsltFileNm = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_InvntryRsltFileNm" , "W_InvntryRsltFileNm");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_InvntryRsltFileNm = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_InvntryRsltFileNm" , "W_InvntryRsltFileNm");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_NoPlanStrgFld = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_NoPlanStrgFld" , "W_NoPlanStorageFld");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_NoPlanStrgFld = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_NoPlanStrgFld" , "W_NoPlanStorageFld");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_ReferenceNoPlanStrg = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_ReferenceNoPlanStrg" , "W_Reference");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_NoPlanStrgFileNm = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_NoPlanStrgFileNm" , "W_NoPlanStorageFileNm");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_NoPlanStrgFileNm = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_NoPlanStrgFileNm" , "W_NoPlanStorageFileNm");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_NoPlanRtrivlFld = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_NoPlanRtrivlFld" , "W_NoPlanRetrievalFld");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_NoPlanRtrivlFld = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_NoPlanRtrivlFld" , "W_NoPlanRetrievalFld");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_ReferenceNoPlanRtrivl = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_ReferenceNoPlanRtrivl" , "W_Reference");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_NoPlanRtrivlFileNm = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_NoPlanRtrivlFileNm" , "W_NoPlanRetrievalFileNm");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_NoPlanRtrivlFileNm = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_NoPlanRtrivlFileNm" , "W_NoPlanRetrievalFileNm");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Submit = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Submit" , "Submit");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Clear = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Clear" , "Clear");

}
//#CM694016
//end of class
