// $Id: WorkerQtyInquiry.java,v 1.2 2006/11/13 08:22:19 suresh Exp $

//#CM694973
/*
 * Copyright 2000-2001 DAIFUKU Co.,Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of DAIFUKU Co.,Ltd.
 * Use is subject to license terms.
 */
package jp.co.daifuku.wms.base.system.display.web.workerqtyinquiry;
import jp.co.daifuku.bluedog.ui.control.Page;

//#CM694974
/**
 * Non variable class generated by a tool.
 * 
 * <BR>
 * <TABLE BORDER="1" CELLPADDING="3" CELLSPACING="0">
 * <TR BGCOLOR="#CCCCFF" CLASS="TableHeadingColor"><TD>Date</TD><TD>Name</TD><TD>Comment</TD></TR>
 * <TR><TD>2004/02/13</TD><TD>N.Sawa(DFK)</TD><TD>created this class</TD></TR>
 * </TABLE>
 * <BR>
 * @version $Revision: 1.2 $, $Date: 2006/11/13 08:22:19 $
 * @author  $Author: suresh $
 */
public class WorkerQtyInquiry extends Page
{

	//#CM694975
	// Class variables -----------------------------------------------
	public jp.co.daifuku.bluedog.ui.control.Label lbl_SettingName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_SettingName" , "In_SettingName");
	public jp.co.daifuku.bluedog.ui.control.LinkButton btn_Help = jp.co.daifuku.bluedog.ui.control.LinkButtonFactory.getInstance("btn_Help" , "Help");
	public jp.co.daifuku.bluedog.ui.control.Message message = jp.co.daifuku.bluedog.ui.control.MessageFactory.getInstance("message" , "OperationMsg");
	public jp.co.daifuku.bluedog.ui.control.Tab tab_Inquiry = jp.co.daifuku.bluedog.ui.control.TabFactory.getInstance("tab_Inquiry" , "W_Inquiry");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_ToMenu = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_ToMenu" , "To_Menu");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_WorkDetails = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_WorkDetails" , "W_WorkDetails");
	public jp.co.daifuku.bluedog.ui.control.PullDown pul_WorkDetails = jp.co.daifuku.bluedog.ui.control.PullDownFactory.getInstance("pul_WorkDetails" , "W_WorkDetails");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_StartWorkDate = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_StartWorkDate" , "W_StartWorkDate");
	public jp.co.daifuku.bluedog.ui.control.DateTextBox txt_StartWorkDate = jp.co.daifuku.bluedog.ui.control.DateTextBoxFactory.getInstance("txt_StartWorkDate" , "W_StartWorkDate");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_PSearchStrtWk = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_PSearchStrtWk" , "P_Search");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_FromTo = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_FromTo" , "W_FromTo");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_EndWorkDate = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_EndWorkDate" , "W_EndWorkDate");
	public jp.co.daifuku.bluedog.ui.control.DateTextBox txt_EndWorkDate = jp.co.daifuku.bluedog.ui.control.DateTextBoxFactory.getInstance("txt_EndWorkDate" , "W_EndWorkDate");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_PSearchEdWk = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_PSearchEdWk" , "P_Search");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_WorkerCode = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_WorkerCode" , "W_WorkerCode");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_WorkerCode = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_WorkerCode" , "W_WorkerCode");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_PSearchWkr = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_PSearchWkr" , "P_Search");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_GroupCondition = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_GroupCondition" , "W_GroupCondition");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_TermTotal = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_TermTotal" , "W_TermTotal");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_DailyTotal = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_DailyTotal" , "W_DailyTotal");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_Detail = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_Detail" , "W_Detail");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_PDisplay = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_PDisplay" , "W_P_Display");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Print = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Print" , "W_Print");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Clear = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Clear" , "Clear");

}
//#CM694976
//end of class
