// $Id: DefineLoadDataMenuSorting.java,v 1.2 2006/11/13 08:18:25 suresh Exp $

//#CM688278
/*
 * Copyright 2000-2001 DAIFUKU Co.,Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of DAIFUKU Co.,Ltd.
 * Use is subject to license terms.
 */
package jp.co.daifuku.wms.base.system.display.web.defineloaddatamenu;
import jp.co.daifuku.bluedog.ui.control.Page;

//#CM688279
/**
 * Non variable class generated by a tool.
 * 
 * <BR>
 * <TABLE BORDER="1" CELLPADDING="3" CELLSPACING="0">
 * <TR BGCOLOR="#CCCCFF" CLASS="TableHeadingColor"><TD>Date</TD><TD>Name</TD><TD>Comment</TD></TR>
 * <TR><TD>2004/02/13</TD><TD>N.Sawa(DFK)</TD><TD>created this class</TD></TR>
 * </TABLE>
 * <BR>
 * @version $Revision: 1.2 $, $Date: 2006/11/13 08:18:25 $
 * @author  $Author: suresh $
 */
public class DefineLoadDataMenuSorting extends Page
{

	//#CM688280
	// Class variables -----------------------------------------------
	public jp.co.daifuku.bluedog.ui.control.Label lbl_SettingName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_SettingName" , "In_SettingName");
	public jp.co.daifuku.bluedog.ui.control.LinkButton btn_Help = jp.co.daifuku.bluedog.ui.control.LinkButtonFactory.getInstance("btn_Help" , "Help");
	public jp.co.daifuku.bluedog.ui.control.Message message = jp.co.daifuku.bluedog.ui.control.MessageFactory.getInstance("message" , "OperationMsg");
	public jp.co.daifuku.bluedog.ui.control.Tab tab_LodClmSetPick = jp.co.daifuku.bluedog.ui.control.TabFactory.getInstance("tab_LodClmSetPick" , "W_LodClm_SetPick");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Back = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Back" , "Back");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_ToMenu = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_ToMenu" , "To_Menu");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ValidLeft1 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ValidLeft1" , "W_Valid");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_DigitsUseLength1 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_DigitsUseLength1" , "W_DigitsUseLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLength1 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLength1" , "W_MaxLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Position1 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Position1" , "W_Position");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Valid2 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Valid2" , "W_Valid");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_DigitsUseLength2 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_DigitsUseLength2" , "W_DigitsUseLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLength2 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLength2" , "W_MaxLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Position2 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Position2" , "W_Position");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_PickPlanDateReq = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_PickPlanDateReq" , "W_PickPlanDateReq");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_NPickPlanDateReq = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_NPickPlanDateReq" , "W_CommonNotUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_PickPlanDateReqLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_PickPlanDateReqLen" , "W_PickPlanDateReqLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenPickPlanDateReq = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenPickPlanDateReq" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_PickPlanDateReqPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_PickPlanDateReqPst" , "W_PickPlanDateReqPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ItemName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ItemName" , "W_ItemName");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_NItemNm = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_NItemNm" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_ItemNmLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_ItemNmLen" , "W_ItemNameLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenItemNm = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenItemNm" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_ItemNmPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_ItemNmPst" , "W_ItemNamePosition");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ConsignorCode = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ConsignorCode" , "W_ConsignorCode");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_CnsgnrCd = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_CnsgnrCd" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CnsgnrCdLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CnsgnrCdLen" , "W_CnsgnrCdLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenCnsgnrCd = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenCnsgnrCd" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CnsgnrCdPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CnsgnrCdPst" , "W_CnsgnrCdPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_PickingQtyPtlReq = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_PickingQtyPtlReq" , "W_PickingQtyPtlReq");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_NPickQtyPtlReq = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_NPickQtyPtlReq" , "W_CommonNotUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_PickQtyPtlLenReq = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_PickQtyPtlLenReq" , "W_PickQtyPtlReqLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenPickQtyPtlReq = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenPickQtyPtlReq" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_PickQtyPtlReqPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_PickQtyPtlReqPst" , "W_PickQtyPtlReqPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ConsignorName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ConsignorName" , "W_ConsignorName");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_ConsignorName = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_ConsignorName" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CnsgnrNmLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CnsgnrNmLen" , "W_CnsgnrNmLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenConsignorName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenConsignorName" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CnsgnrNmPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CnsgnrNmPst" , "W_CnsgnrNmPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_PicePickPlaceReq = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_PicePickPlaceReq" , "W_PicePickPlaceReq");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_NPiecePickPlaceReq = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_NPiecePickPlaceReq" , "W_CommonNotUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_PiecePickPlaceReqLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_PiecePickPlaceReqLen" , "W_PicePkPlaceReqLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenPiecePickPlaceReq = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenPiecePickPlaceReq" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_PiecePickPlaceReqPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_PiecePickPlaceReqPst" , "W_PicePkPlaceReqPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_CustCdReq = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_CustCdReq" , "W_CustCdReq");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_NCustCdReq = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_NCustCdReq" , "W_CommonNotUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CustCdReqLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CustCdReqLen" , "W_CustCdReqLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenCustCdReq = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenCustCdReq" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CustCdReqPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CustCdReqPst" , "W_CustCdReqPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_CasePickingPlace = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_CasePickingPlace" , "W_CasePickingPlace");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_CasePickPlacee = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_CasePickPlacee" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CasePickPlaceLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CasePickPlaceLen" , "W_CasePickPlaceLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenCasePickPlace = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenCasePickPlace" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CasePickPlacePst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CasePickPlacePst" , "W_CasePickPlacePst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_CustNm = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_CustNm" , "W_CustomerName");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_NCustNm = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_NCustNm" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CustNmLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CustNmLen" , "W_CustNmLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenCustNm = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenCustNm" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CustNmPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CustNmPst" , "W_CustNmPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_CrossDCRequired = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_CrossDCRequired" , "W_CrossDCRequired");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_NCrossDCFlagReq = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_NCrossDCFlagReq" , "W_CommonNotUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CrossDCFlagReqLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CrossDCFlagReqLen" , "W_CrsDCFlgReqLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenCrossDCFlagReq = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenCrossDCFlagReq" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CrossDCFlagPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CrossDCFlagPst" , "W_CrossDCFlagPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ShippingTicketNo = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ShippingTicketNo" , "W_ShippingTicketNo");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_ShpTktNo = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_ShpTktNo" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_ShpTktNoLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_ShpTktNoLen" , "W_ShpTktNoLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenShpTktNo = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenShpTktNo" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_ShpTktNoPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_ShpTktNoPst" , "W_ShpTktNoPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_SupplierCodeAst = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_SupplierCodeAst" , "W_SupplierCodeAst");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_SupplierCdAst = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_SupplierCdAst" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_SupplierCdAstLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_SupplierCdAstLen" , "W_SplCdAstLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenSupplierCdAst = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenSupplierCdAst" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_SupplierCdAstPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_SupplierCdAstPst" , "W_SplCdAstPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ShpTktLineNo = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ShpTktLineNo" , "W_ShpTktLineNo");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_ShpTktLineNo = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_ShpTktLineNo" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_ShpTktLineNoLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_ShpTktLineNoLen" , "W_ShpTktLineNoLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenShpTktLineNo = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenShpTktLineNo" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_ShpTktLineNoPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_ShpTktLineNoPst" , "W_ShpTktLineNoPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_SupplierName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_SupplierName" , "W_SupplierName");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_SupplierNmAst = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_SupplierNmAst" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_SupplierNmAstLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_SupplierNmAstLen" , "W_SplNmAstLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenSupplierNmAst = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenSupplierNmAst" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_SupplierNmAstPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_SupplierNmAstPst" , "W_SplNmAstPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ItemCodeRequired = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ItemCodeRequired" , "W_ItemCodeRequired");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_NItemCdReq = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_NItemCdReq" , "W_CommonNotUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_ItemCdReqLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_ItemCdReqLen" , "W_ItemCdReqLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenItemCdReq = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenItemCdReq" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_ItemCdReqPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_ItemCdReqPst" , "W_ItemCdReqPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_InstockTicketNoAst = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_InstockTicketNoAst" , "W_InstockTicketNoAst");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_InstkTktNoAst = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_InstkTktNoAst" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_InstkTktNoAstLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_InstkTktNoAstLen" , "W_InstkTktNoAstLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenInstkTktNoAst = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenInstkTktNoAst" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_InstkTktNoAstPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_InstkTktNoAstPst" , "W_InstkTktNoAstPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_BundleItf = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_BundleItf" , "W_BundleItf");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_BundleItf = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_BundleItf" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_BundleItfLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_BundleItfLen" , "W_BundleItfLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenBundleItf = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenBundleItf" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_BundleItfPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_BundleItfPst" , "W_BundleItfPosition");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_InstkTktLineNoAst = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_InstkTktLineNoAst" , "W_InstkTktLineNoAst");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_InstkTktLineNoAst = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_InstkTktLineNoAst" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_InstkTktLineNoAstLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_InstkTktLineNoAstLen" , "W_InstkTktLineAstLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenInstkTktLineNoAst = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenInstkTktLineNoAst" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_InstkTktLineNoAstPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_InstkTktLineNoAstPst" , "W_InstkTktLineAstPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_CaseItf = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_CaseItf" , "W_CaseItf");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_CaseItf = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_CaseItf" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CaseItfLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CaseItfLen" , "W_CaseItfLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenCaseItf = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenCaseItf" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CaseItfPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CaseItfPst" , "W_CaseItfPosition");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_BundleEntering = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_BundleEntering" , "W_BundleEntering");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_BundleEntering = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_BundleEntering" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_BundleEnteringLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_BundleEnteringLen" , "W_BdlEtrLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenBundleEntering = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenBundleEntering" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_BundleEnteringPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_BundleEnteringPst" , "W_BdlEtrPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_CrossTCRequiredAst = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_CrossTCRequiredAst" , "W_CrossTCRequiredAst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_CaseEtrReq = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_CaseEtrReq" , "W_CaseEtrReq");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_NCaseEtrReq = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_NCaseEtrReq" , "W_CommonNotUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CaseEtrReqLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CaseEtrReqLen" , "W_CaseEtrReqLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenCaseEtrReq = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenCaseEtrReq" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CaseEtrReqPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CaseEtrReqPst" , "W_CaseEtrReqPst");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Submit = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Submit" , "Submit");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Clear = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Clear" , "Clear");

}
//#CM688281
//end of class
