// $Id: DefineLoadDataMenuInstock.java,v 1.2 2006/11/13 08:18:28 suresh Exp $

//#CM687652
/*
 * Copyright 2000-2001 DAIFUKU Co.,Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of DAIFUKU Co.,Ltd.
 * Use is subject to license terms.
 */
package jp.co.daifuku.wms.base.system.display.web.defineloaddatamenu;
import jp.co.daifuku.bluedog.ui.control.Page;

//#CM687653
/**
 * Non variable class generated by a tool.
 * 
 * <BR>
 * <TABLE BORDER="1" CELLPADDING="3" CELLSPACING="0">
 * <TR BGCOLOR="#CCCCFF" CLASS="TableHeadingColor"><TD>Date</TD><TD>Name</TD><TD>Comment</TD></TR>
 * <TR><TD>2004/02/13</TD><TD>N.Sawa(DFK)</TD><TD>created this class</TD></TR>
 * </TABLE>
 * <BR>
 * @version $Revision: 1.2 $, $Date: 2006/11/13 08:18:28 $
 * @author  $Author: suresh $
 */
public class DefineLoadDataMenuInstock extends Page
{

	//#CM687654
	// Class variables -----------------------------------------------
	public jp.co.daifuku.bluedog.ui.control.Label lbl_SettingName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_SettingName" , "In_SettingName");
	public jp.co.daifuku.bluedog.ui.control.LinkButton btn_Help = jp.co.daifuku.bluedog.ui.control.LinkButtonFactory.getInstance("btn_Help" , "Help");
	public jp.co.daifuku.bluedog.ui.control.Message message = jp.co.daifuku.bluedog.ui.control.MessageFactory.getInstance("message" , "OperationMsg");
	public jp.co.daifuku.bluedog.ui.control.Tab tab_LodClm_SetInstk = jp.co.daifuku.bluedog.ui.control.TabFactory.getInstance("tab_LodClm_SetInstk" , "W_LodClm_SetInstk");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Back = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Back" , "Back");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_ToMenu = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_ToMenu" , "To_Menu");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ValidLeft1 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ValidLeft1" , "W_Valid");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_DigitsUseLength1 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_DigitsUseLength1" , "W_DigitsUseLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLength1 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLength1" , "W_MaxLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Position1 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Position1" , "W_Position");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Valid2 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Valid2" , "W_Valid");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_DigitsUseLength2 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_DigitsUseLength2" , "W_DigitsUseLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLength2 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLength2" , "W_MaxLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Position2 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Position2" , "W_Position");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_InstkPlanDateReq = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_InstkPlanDateReq" , "W_InstkPlanDateReq");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_NInstockPlanDtReq = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_NInstockPlanDtReq" , "W_CommonNotUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_InstkPlanDtReqLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_InstkPlanDtReqLen" , "W_InstkPnDtReqLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenInstkPlanDtReq = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenInstkPlanDtReq" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_InstkPlanDtReqPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_InstkPlanDtReqPst" , "W_InstkPnDtReqPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_BundleEntering = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_BundleEntering" , "W_BundleEntering");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_BundleEtr = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_BundleEtr" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_BundleEtrLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_BundleEtrLen" , "W_BdlEtrLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenBundleEtr = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenBundleEtr" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_BundleEtrPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_BundleEtrPst" , "W_BdlEtrPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_OrderDate = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_OrderDate" , "W_OrderDate");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_OrderDate = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_OrderDate" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_OrderDateLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_OrderDateLen" , "W_OdrgDateLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenOrderDate = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenOrderDate" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_OrderDatePst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_OrderDatePst" , "W_OdrgDatePst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_CaseEtrReq = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_CaseEtrReq" , "W_CaseEtrReq");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_NCaseEtrReq = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_NCaseEtrReq" , "W_CommonNotUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CaseEtrReqLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CaseEtrReqLen" , "W_CaseEtrReqLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenCaseEtrReq = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenCaseEtrReq" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CaseEtrReqPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CaseEtrReqPst" , "W_CaseEtrReqPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ConsignorCode = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ConsignorCode" , "W_ConsignorCode");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_CnsgnrCd = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_CnsgnrCd" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CnsgnrCdLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CnsgnrCdLen" , "W_CnsgnrCdLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenCnsgnrCd = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenCnsgnrCd" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CnsgnrCdPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CnsgnrCdPst" , "W_CnsgnrCdPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ItemName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ItemName" , "W_ItemName");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_NItemNm = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_NItemNm" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_ItemNmLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_ItemNmLen" , "W_ItemNameLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenItemNm = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenItemNm" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_ItemNmPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_ItemNmPst" , "W_ItemNamePosition");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ConsignorName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ConsignorName" , "W_ConsignorName");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_CnsgnrNm = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_CnsgnrNm" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CnsgnrNmLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CnsgnrNmLen" , "W_CnsgnrNmLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenCnsgnrNm = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenCnsgnrNm" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CnsgnrNmPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CnsgnrNmPst" , "W_CnsgnrNmPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_InstkQtyPtlReq = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_InstkQtyPtlReq" , "W_InstkQtyPtlReq");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_NInstkQtyPtlReq = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_NInstkQtyPtlReq" , "W_CommonNotUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_InstkQtyPtlLenReq = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_InstkQtyPtlLenReq" , "W_InstkQtyPtlReqLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenInstkQtyPtlReq = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenInstkQtyPtlReq" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_InstkQtyPtlReqPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_InstkQtyPtlReqPst" , "W_InstkQtyPtlReqPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_SplCdReq = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_SplCdReq" , "W_SplCdReq");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_NSupplierCdReq = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_NSupplierCdReq" , "W_CommonNotUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_SupplierCdReqLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_SupplierCdReqLen" , "W_SplCdReqLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenSupplierCdReq = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenSupplierCdReq" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_SupplierCdReqPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_SupplierCdReqPst" , "W_SplCdReqPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_TCDCRequired = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_TCDCRequired" , "W_TCDCRequired");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_NTCDCFlgReq = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_NTCDCFlgReq" , "W_CommonNotUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_TCDCFlgReqLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_TCDCFlgReqLen" , "W_TCDCFlgReqLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenTCDCFlgReq = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenTCDCFlgReq" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_TCDCFlgReqPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_TCDCFlgReqPst" , "W_TCDCFlgReqPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_SplName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_SplName" , "W_SupplierName");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_NSupplierNm = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_NSupplierNm" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_SupplierNmLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_SupplierNmLen" , "W_SplNmLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenSupplierNm = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenSupplierNm" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_SupplierNmPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_SupplierNmPst" , "W_SplNmPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_CustomerCodeAst = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_CustomerCodeAst" , "W_CustomerCodeAst");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_CustCdAst = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_CustCdAst" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CustCdAstLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CustCdAstLen" , "W_CustCdAstLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenCustCdAst = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenCustCdAst" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CustCdAstPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CustCdAstPst" , "W_CustCdAstPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_TicketNoRequired = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_TicketNoRequired" , "W_TicketNoRequired");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_NTktNoReq = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_NTktNoReq" , "W_CommonNotUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_TktNoReqLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_TktNoReqLen" , "W_TktNoReqLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenTktNoReq = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenTktNoReq" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_TktNoReqPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_TktNoReqPst" , "W_TktNoReqPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_CustomerName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_CustomerName" , "W_CustomerName");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_CustNmAst = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_CustNmAst" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CustNmAstLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CustNmAstLen" , "W_CustNmAstLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenCustNmAst = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenCustNmAst" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CustNmAstPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CustNmAstPst" , "W_CustNmAstPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_TktLineNoReq = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_TktLineNoReq" , "W_TktLineNoReq");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_NTktLineNoReq = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_NTktLineNoReq" , "W_CommonNotUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_TktLineNoReqLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_TktLineNoReqLen" , "W_TktLineNoReqLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenTktLineNoReq = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenTktLineNoReq" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_TktLineNoReqPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_TktLineNoReqPst" , "W_TktLineNoReqPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ItemCodeRequired = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ItemCodeRequired" , "W_ItemCodeRequired");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_NItemCdReq = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_NItemCdReq" , "W_CommonNotUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_ItemCdReqLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_ItemCdReqLen" , "W_ItemCdReqLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenItemCdReq = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenItemCdReq" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_ItemCdReqPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_ItemCdReqPst" , "W_ItemCdReqPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_TCRequiredAst = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_TCRequiredAst" , "W_TCRequired");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_BundleItf = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_BundleItf" , "W_BundleItf");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_BundleItf = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_BundleItf" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_BundleItfLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_BundleItfLen" , "W_BundleItfLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenBundleItf = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenBundleItf" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_BundleItfPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_BundleItfPst" , "W_BundleItfPosition");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_CaseItf = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_CaseItf" , "W_CaseItf");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_CaseItf = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_CaseItf" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CaseItfLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CaseItfLen" , "W_CaseItfLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenCaseItf = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenCaseItf" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CaseItfPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CaseItfPst" , "W_CaseItfPosition");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Submit = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Submit" , "Submit");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Clear = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Clear" , "Clear");

}
//#CM687655
//end of class
