// $Id: ReportDataStock.java,v 1.2 2006/11/13 08:21:58 suresh Exp $

//#CM694587
/*
 * Copyright 2000-2001 DAIFUKU Co.,Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of DAIFUKU Co.,Ltd.
 * Use is subject to license terms.
 */
package jp.co.daifuku.wms.base.system.display.web.reportdatastock;
import jp.co.daifuku.bluedog.ui.control.Page;

//#CM694588
/**
 * Non variable class generated by a tool.
 * 
 * <BR>
 * <TABLE BORDER="1" CELLPADDING="3" CELLSPACING="0">
 * <TR BGCOLOR="#CCCCFF" CLASS="TableHeadingColor"><TD>Date</TD><TD>Name</TD><TD>Comment</TD></TR>
 * <TR><TD>2004/02/13</TD><TD>N.Sawa(DFK)</TD><TD>created this class</TD></TR>
 * </TABLE>
 * <BR>
 * @version $Revision: 1.2 $, $Date: 2006/11/13 08:21:58 $
 * @author  $Author: suresh $
 */
public class ReportDataStock extends Page
{

	//#CM694589
	// Class variables -----------------------------------------------
	public jp.co.daifuku.bluedog.ui.control.Label lbl_SettingName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_SettingName" , "In_SettingName");
	public jp.co.daifuku.bluedog.ui.control.LinkButton btn_Help = jp.co.daifuku.bluedog.ui.control.LinkButtonFactory.getInstance("btn_Help" , "Help");
	public jp.co.daifuku.bluedog.ui.control.Message message = jp.co.daifuku.bluedog.ui.control.MessageFactory.getInstance("message" , "OperationMsg");
	public jp.co.daifuku.bluedog.ui.control.Tab tab_ReportDataStock = jp.co.daifuku.bluedog.ui.control.TabFactory.getInstance("tab_ReportDataStock" , "W_ReportDataStock");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_ToMenu = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_ToMenu" , "To_Menu");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_WorkerCode = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_WorkerCode" , "W_WorkerCode");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_WorkerCode = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_WorkerCode" , "W_WorkerCode");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Password = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Password" , "W_Password");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_Password = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_Password" , "W_Password");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ConsignorCode = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ConsignorCode" , "W_ConsignorCode");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_ConsignorCode = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_ConsignorCode" , "W_ConsignorCode");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_PsearchCnsgnrCd = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_PsearchCnsgnrCd" , "P_Search");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ReportDataStockFld = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ReportDataStockFld" , "W_ReportDataStockFld");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_RptDataStockFld = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_RptDataStockFld" , "W_RptDataStockFld");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Reference = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Reference" , "W_Reference");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ReportDataStockFileNm = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ReportDataStockFileNm" , "W_ReportDataStockFileNm");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_RptDataStockFileNm = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_RptDataStockFileNm" , "W_RptDataStockFileNm");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Start = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Start" , "Start");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Clear = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Clear" , "Clear");

}
//#CM694590
//end of class
