// $Id: DefineLoadDataMenu.java,v 1.2 2006/11/13 08:18:29 suresh Exp $

//#CM687559
/*
 * Copyright 2000-2001 DAIFUKU Co.,Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of DAIFUKU Co.,Ltd.
 * Use is subject to license terms.
 */
package jp.co.daifuku.wms.base.system.display.web.defineloaddatamenu;
import jp.co.daifuku.bluedog.ui.control.Page;

//#CM687560
/**
 * Non variable class generated by a tool.
 * 
 * <BR>
 * <TABLE BORDER="1" CELLPADDING="3" CELLSPACING="0">
 * <TR BGCOLOR="#CCCCFF" CLASS="TableHeadingColor"><TD>Date</TD><TD>Name</TD><TD>Comment</TD></TR>
 * <TR><TD>2004/02/13</TD><TD>N.Sawa(DFK)</TD><TD>created this class</TD></TR>
 * </TABLE>
 * <BR>
 * @version $Revision: 1.2 $, $Date: 2006/11/13 08:18:29 $
 * @author  $Author: suresh $
 */
public class DefineLoadDataMenu extends Page
{

	//#CM687561
	// Class variables -----------------------------------------------
	public jp.co.daifuku.bluedog.ui.control.Label lbl_SettingName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_SettingName" , "In_SettingName");
	public jp.co.daifuku.bluedog.ui.control.LinkButton btn_Help = jp.co.daifuku.bluedog.ui.control.LinkButtonFactory.getInstance("btn_Help" , "Help");
	public jp.co.daifuku.bluedog.ui.control.Message message = jp.co.daifuku.bluedog.ui.control.MessageFactory.getInstance("message" , "OperationMsg");
	public jp.co.daifuku.bluedog.ui.control.Tab tab_LodClm_Set = jp.co.daifuku.bluedog.ui.control.TabFactory.getInstance("tab_LodClm_Set" , "W_LodClm_Set");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_ToMenu = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_ToMenu" , "To_Menu");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_WorkerCode = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_WorkerCode" , "W_WorkerCode");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_WorkerCode = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_WorkerCode" , "W_WorkerCode");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Password = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Password" , "W_Password");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_Password = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_Password" , "W_Password");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_Plan_Instock = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_Plan_Instock" , "W_Plan_Instock");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_Plan_Storage = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_Plan_Storage" , "W_Plan_Storage");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_Plan_Retrieval = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_Plan_Retrieval" , "W_Plan_Retrieval");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_Plan_Picking = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_Plan_Picking" , "W_Plan_Picking");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_Plan_Shipping = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_Plan_Shipping" , "W_Plan_Shipping");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Next = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Next" , "Next");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Clear = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Clear" , "Clear");

}
//#CM687562
//end of class
