// $Id: DefineLoadDataMenuStorage.java,v 1.2 2006/11/13 08:18:24 suresh Exp $

//#CM688482
/*
 * Copyright 2000-2001 DAIFUKU Co.,Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of DAIFUKU Co.,Ltd.
 * Use is subject to license terms.
 */
package jp.co.daifuku.wms.base.system.display.web.defineloaddatamenu;
import jp.co.daifuku.bluedog.ui.control.Page;

//#CM688483
/**
 * Non variable class generated by a tool.
 * 
 * <BR>
 * <TABLE BORDER="1" CELLPADDING="3" CELLSPACING="0">
 * <TR BGCOLOR="#CCCCFF" CLASS="TableHeadingColor"><TD>Date</TD><TD>Name</TD><TD>Comment</TD></TR>
 * <TR><TD>2004/02/13</TD><TD>N.Sawa(DFK)</TD><TD>created this class</TD></TR>
 * </TABLE>
 * <BR>
 * @version $Revision: 1.2 $, $Date: 2006/11/13 08:18:24 $
 * @author  $Author: suresh $
 */
public class DefineLoadDataMenuStorage extends Page
{

	//#CM688484
	// Class variables -----------------------------------------------
	public jp.co.daifuku.bluedog.ui.control.Label lbl_SettingName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_SettingName" , "In_SettingName");
	public jp.co.daifuku.bluedog.ui.control.LinkButton btn_Help = jp.co.daifuku.bluedog.ui.control.LinkButtonFactory.getInstance("btn_Help" , "Help");
	public jp.co.daifuku.bluedog.ui.control.Message message = jp.co.daifuku.bluedog.ui.control.MessageFactory.getInstance("message" , "OperationMsg");
	public jp.co.daifuku.bluedog.ui.control.Tab tab_LodClmSetStrg = jp.co.daifuku.bluedog.ui.control.TabFactory.getInstance("tab_LodClmSetStrg" , "W_LodClm_SetStrg");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Back = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Back" , "Back");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_ToMenu = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_ToMenu" , "To_Menu");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ValidLeft1 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ValidLeft1" , "W_Valid");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_DigitsUseLength1 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_DigitsUseLength1" , "W_DigitsUseLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLength1 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLength1" , "W_MaxLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Position1 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Position1" , "W_Position");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_StrgPlanDateReq = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_StrgPlanDateReq" , "W_StrgPlanDateReq");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_NStrgPlanDateReq = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_NStrgPlanDateReq" , "W_CommonNotUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_StrgPlanDateReqLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_StrgPlanDateReqLen" , "W_StrgPlanDateReqLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenStrgPlanDateReq = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenStrgPlanDateReq" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_StrgPlanDateReqPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_StrgPlanDateReqPst" , "W_StrgPlanDateReqPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ConsignorCode = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ConsignorCode" , "W_ConsignorCode");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_CnsgnrCd = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_CnsgnrCd" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CnsgnrCdLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CnsgnrCdLen" , "W_CnsgnrCdLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenConsignorCode = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenConsignorCode" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CnsgnrCdPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CnsgnrCdPst" , "W_CnsgnrCdPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ConsignorName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ConsignorName" , "W_ConsignorName");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_CnsgnrNm = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_CnsgnrNm" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CnsgnrNmLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CnsgnrNmLen" , "W_CnsgnrNmLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenConsignorName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenConsignorName" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CnsgnrNmPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CnsgnrNmPst" , "W_CnsgnrNmPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ItemCodeRequired = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ItemCodeRequired" , "W_ItemCodeRequired");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_NItemCdReq = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_NItemCdReq" , "W_CommonNotUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_ItemCdReqLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_ItemCdReqLen" , "W_ItemCdReqLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenItemCodeReq = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenItemCodeReq" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_ItemCdReqPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_ItemCdReqPst" , "W_ItemCdReqPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_BundleItf = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_BundleItf" , "W_BundleItf");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_BundleItf = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_BundleItf" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_BundleItfLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_BundleItfLen" , "W_BundleItfLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenBundleItf = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenBundleItf" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_BundleItfPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_BundleItfPst" , "W_BundleItfPosition");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_CaseItf = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_CaseItf" , "W_CaseItf");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_CaseItf = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_CaseItf" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CaseItfLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CaseItfLen" , "W_CaseItfLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenCaseItf = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenCaseItf" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CaseItfPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CaseItfPst" , "W_CaseItfPosition");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_BundleEntering = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_BundleEntering" , "W_BundleEntering");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_BundleEtr = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_BundleEtr" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_BundleEtrLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_BundleEtrLen" , "W_BdlEtrLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenBundleEtr = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenBundleEtr" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_BundleEtrPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_BundleEtrPst" , "W_BdlEtrPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_CaseEtrReq = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_CaseEtrReq" , "W_CaseEtrReq");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_NCaseEtrReq = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_NCaseEtrReq" , "W_CommonNotUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CaseEtrReqLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CaseEtrReqLen" , "W_CaseEtrReqLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenCaseEtrReq = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenCaseEtrReq" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CaseEtrReqPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CaseEtrReqPst" , "W_CaseEtrReqPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ItemName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ItemName" , "W_ItemName");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_NItemNm = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_NItemNm" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_ItemNmLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_ItemNmLen" , "W_ItemNameLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenItemNm = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenItemNm" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_ItemNmPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_ItemNmPst" , "W_ItemNamePosition");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_StrgQtyPtlReq = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_StrgQtyPtlReq" , "W_StrgQtyPtlReq");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_NStrgQtyPtlReq = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_NStrgQtyPtlReq" , "W_CommonNotUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_StrgQtyPtlReqLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_StrgQtyPtlReqLen" , "W_StrgQtyPtlReqLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenStrgQtyPtlReq = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenStrgQtyPtlReq" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_StrgQtyPtlReqPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_StrgQtyPtlReqPst" , "W_StrgQtyPtlReqPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_PieceStrgLct = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_PieceStrgLct" , "W_PiceStrgLct");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_PieceStrgLct = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_PieceStrgLct" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_PieceStrgLctLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_PieceStrgLctLen" , "W_PiceStrgLctLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenPieceStrgLct = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenPieceStrgLct" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_PieceStrgLctPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_PieceStrgLctPst" , "W_PiceStrgLctPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_CaseStrgLct = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_CaseStrgLct" , "W_CaseStrgLct");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_CaseStrgLct = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_CaseStrgLct" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CaseStrgLctLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CaseStrgLctLen" , "W_CaseStrgLctLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenCaseStrgLct = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenCaseStrgLct" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CaseStrgLctPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CaseStrgLctPst" , "W_CaseStrgLctPst");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Submit = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Submit" , "Submit");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Clear = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Clear" , "Clear");

}
//#CM688485
//end of class
