// $Id: RetrievalPlanModify2.java,v 1.2 2007/02/07 04:19:31 suresh Exp $

//#CM718352
/*
 * Copyright 2000-2001 DAIFUKU Co.,Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of DAIFUKU Co.,Ltd.
 * Use is subject to license terms.
 */
package jp.co.daifuku.wms.retrieval.display.web.retrievalplanmodify;
import jp.co.daifuku.bluedog.ui.control.Page;

//#CM718353
/**
 * Non variable class generated by a tool. 
 * 
 * <BR>
 * <TABLE BORDER=1 CELLPADDING=3 CELLSPACING=0>
 * <TR BGCOLOR=#CCCCFF CLASS=TableHeadingColor><TD>Date</TD><TD>Name</TD><TD>Comment</TD></TR>
 * <TR><TD>2004/02/13</TD><TD>N.Sawa(DFK)</TD><TD>created this class</TD></TR>
 * </TABLE>
 * <BR>
 * @version $Revision: 1.2 $, $Date: 2007/02/07 04:19:31 $
 * @author  $Author: suresh $
 */
public class RetrievalPlanModify2 extends Page
{

	//#CM718354
	// Class variables -----------------------------------------------
	public jp.co.daifuku.bluedog.ui.control.Label lbl_SettingName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_SettingName" , "In_SettingName");
	public jp.co.daifuku.bluedog.ui.control.LinkButton btn_Help = jp.co.daifuku.bluedog.ui.control.LinkButtonFactory.getInstance("btn_Help" , "Help");
	public jp.co.daifuku.bluedog.ui.control.Message message = jp.co.daifuku.bluedog.ui.control.MessageFactory.getInstance("message" , "OperationMsg");
	public jp.co.daifuku.bluedog.ui.control.Tab tab_BscDtlMdfyDlt = jp.co.daifuku.bluedog.ui.control.TabFactory.getInstance("tab_BscDtlMdfyDlt" , "W_Bsc_DtlMdfyDlt");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Back = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Back" , "Back");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_ToMenu = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_ToMenu" , "To_Menu");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Consignor = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Consignor" , "W_Consignor");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_JavaSetCnsgnrCd = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_JavaSetCnsgnrCd" , "W_JavaSet");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_JavaSetCnsgnrNm = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_JavaSetCnsgnrNm" , "W_JavaSet");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_RetrievalPlanDate = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_RetrievalPlanDate" , "W_RetrievalPlanDate");
	public jp.co.daifuku.bluedog.ui.control.DateTextBox txt_FDate = jp.co.daifuku.bluedog.ui.control.DateTextBoxFactory.getInstance("txt_FDate" , "W_F_Date");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Item = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Item" , "W_Item");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_JavaSetItemCd = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_JavaSetItemCd" , "W_JavaSet");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_JavaSetItemNm = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_JavaSetItemNm" , "W_JavaSet");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_CaseRtrivlLct = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_CaseRtrivlLct" , "W_CaseRtrivlLct");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_CaseRtrivlLct = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_CaseRtrivlLct" , "W_CaseRtrivlLct");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_PSearchCaseRtrivlLct = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_PSearchCaseRtrivlLct" , "P_Search");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_PiceRtrivlLct = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_PiceRtrivlLct" , "W_PiceRtrivlLct");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_PieceRtrivlLct = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_PieceRtrivlLct" , "W_PieceRtrivlLct");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_PSearchPiceRtrivlLct = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_PSearchPiceRtrivlLct" , "P_Search");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_CustomerCode = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_CustomerCode" , "W_CustomerCode");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_CustomerCode = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_CustomerCode" , "W_CustomerCode");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_PSearchCustomerCode = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_PSearchCustomerCode" , "P_Search");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_CustomerName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_CustomerName" , "W_CustomerName");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_CustomerName = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_CustomerName" , "W_CustomerName");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_CaseOrder = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_CaseOrder" , "W_CaseOrder");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_CaseOrderNo = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_CaseOrderNo" , "W_CaseOrderNo");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_PSearchCaseOrder = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_PSearchCaseOrder" , "P_Search");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_PieceOrderNo = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_PieceOrderNo" , "W_PieceOrderNo");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_PieceOrderNo = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_PieceOrderNo" , "W_PieceOrderNo");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_PSearchPieceOrderNo = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_PSearchPieceOrderNo" , "P_Search");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_TicketNo = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_TicketNo" , "W_TicketNo");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_TicketNo = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_TicketNo" , "W_TicketNo");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_LineNo = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_LineNo" , "W_LineNo");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_LineNo = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_LineNo" , "W_LineNo");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_CaseEntering = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_CaseEntering" , "W_CaseEntering");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CaseEntering = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CaseEntering" , "W_CaseEntering");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_HostCasePlanQty = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_HostCasePlanQty" , "W_HostCasePlanQty");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_HostCasePlanQty = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_HostCasePlanQty" , "W_HostCasePlanQty");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_CaseItf = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_CaseItf" , "W_CaseItf");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_CaseItf = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_CaseItf" , "W_CaseItf");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_BundleEntering = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_BundleEntering" , "W_BundleEntering");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_BundleEntering = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_BundleEntering" , "W_BundleEntering");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_HostPiesePlanQty = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_HostPiesePlanQty" , "W_HostPiesePlanQty");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_HostPiesePlanQty = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_HostPiesePlanQty" , "W_HostPiesePlanQty");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_BundleItf = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_BundleItf" , "W_BundleItf");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_BundleItf = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_BundleItf" , "W_BundleItf");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Input = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Input" , "W_Input");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Clear = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Clear" , "Clear");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_ModifySubmit = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_ModifySubmit" , "W_ModifySubmit");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_AllDelete = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_AllDelete" , "W_AllDelete");
	public jp.co.daifuku.bluedog.ui.control.ListCell lst_SRetrievalPlanModify = jp.co.daifuku.bluedog.ui.control.ListCellFactory.getInstance("lst_SRetrievalPlanModify" , "W_S_RetrievalPlanModify");

}
//#CM718355
//end of class
