// $Id: ReportDataPlan.java,v 1.2 2006/11/13 08:21:52 suresh Exp $

//#CM694408
/*
 * Copyright 2000-2001 DAIFUKU Co.,Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of DAIFUKU Co.,Ltd.
 * Use is subject to license terms.
 */
package jp.co.daifuku.wms.base.system.display.web.reportdataplan;
import jp.co.daifuku.bluedog.ui.control.Page;

//#CM694409
/**
 * Non variable class generated by a tool.
 * 
 * <BR>
 * <TABLE BORDER="1" CELLPADDING="3" CELLSPACING="0">
 * <TR BGCOLOR="#CCCCFF" CLASS="TableHeadingColor"><TD>Date</TD><TD>Name</TD><TD>Comment</TD></TR>
 * <TR><TD>2004/02/13</TD><TD>N.Sawa(DFK)</TD><TD>created this class</TD></TR>
 * </TABLE>
 * <BR>
 * @version $Revision: 1.2 $, $Date: 2006/11/13 08:21:52 $
 * @author  $Author: suresh $
 */
public class ReportDataPlan extends Page
{

	//#CM694410
	// Class variables -----------------------------------------------
	public jp.co.daifuku.bluedog.ui.control.Label lbl_SettingName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_SettingName" , "In_SettingName");
	public jp.co.daifuku.bluedog.ui.control.LinkButton btn_Help = jp.co.daifuku.bluedog.ui.control.LinkButtonFactory.getInstance("btn_Help" , "Help");
	public jp.co.daifuku.bluedog.ui.control.Message message = jp.co.daifuku.bluedog.ui.control.MessageFactory.getInstance("message" , "OperationMsg");
	public jp.co.daifuku.bluedog.ui.control.Tab tab_DataReport = jp.co.daifuku.bluedog.ui.control.TabFactory.getInstance("tab_DataReport" , "W_DataReport");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_ToMenu = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_ToMenu" , "To_Menu");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_WorkerCode = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_WorkerCode" , "W_WorkerCode");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_WorkerCode = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_WorkerCode" , "W_WorkerCode");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Password = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Password" , "W_Password");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_Password = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_Password" , "W_Password");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_WorkDate1 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_WorkDate1" , "W_WorkDate");
	public jp.co.daifuku.bluedog.ui.control.DateTextBox txt_WorkDate1 = jp.co.daifuku.bluedog.ui.control.DateTextBoxFactory.getInstance("txt_WorkDate1" , "W_WorkDate1");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Select = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Select" , "W_Select");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ReportDetals = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ReportDetals" , "W_ReportDetals");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_WorkProgress = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_WorkProgress" , "W_WorkProgress");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Rupwi = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Rupwi" , "W_Rupwi");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Message = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Message" , "W_Message");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_ComUseSelectInstk = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_ComUseSelectInstk" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_InstockResult = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_InstockResult" , "W_InstockResult");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_ComUseWorkProgInstk = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_ComUseWorkProgInstk" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_ComUseRupwiInstk = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_ComUseRupwiInstk" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MessageInstk = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MessageInstk" , "W_Message");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_ComUseSelectStrg = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_ComUseSelectStrg" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_StorageResult = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_StorageResult" , "W_StorageResult");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_ComUseWorkProgStrg = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_ComUseWorkProgStrg" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_ComUseRupwiStrg = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_ComUseRupwiStrg" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MessageStrg = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MessageStrg" , "W_Message");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_ComUseSelectRtrivl = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_ComUseSelectRtrivl" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_RetrievalResult = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_RetrievalResult" , "W_RetrievalResult");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_ComUseWorkProgRtrivl = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_ComUseWorkProgRtrivl" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_ComUseRupwiRtrivl = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_ComUseRupwiRtrivl" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MessageRtrivl = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MessageRtrivl" , "W_Message");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_ComUseSelectPick = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_ComUseSelectPick" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_PickingResult = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_PickingResult" , "W_PickingResult");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_ComUseWorkProgPick = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_ComUseWorkProgPick" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_ComUseRupwiPick = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_ComUseRupwiPick" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MessagePick = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MessagePick" , "W_Message");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_ComUseSelectShp = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_ComUseSelectShp" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ShippingResult = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ShippingResult" , "W_ShippingResult");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_ComUseWorkProgShp = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_ComUseWorkProgShp" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_ComUseRupwiShp = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_ComUseRupwiShp" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MessageShp = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MessageShp" , "W_Message");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Start = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Start" , "Start");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Clear = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Clear" , "Clear");

}
//#CM694411
//end of class
