// $Id: RetrievalShortageInquiry.java,v 1.2 2006/11/13 08:22:04 suresh Exp $

//#CM694694
/*
 * Copyright 2000-2001 DAIFUKU Co.,Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of DAIFUKU Co.,Ltd.
 * Use is subject to license terms.
 */
package jp.co.daifuku.wms.base.system.display.web.retrievalshortageinquiry;
import jp.co.daifuku.bluedog.ui.control.Page;

//#CM694695
/**
 * Non variable class generated by a tool.
 * 
 * <BR>
 * <TABLE BORDER="1" CELLPADDING="3" CELLSPACING="0">
 * <TR BGCOLOR="#CCCCFF" CLASS="TableHeadingColor"><TD>Date</TD><TD>Name</TD><TD>Comment</TD></TR>
 * <TR><TD>2004/02/13</TD><TD>N.Sawa(DFK)</TD><TD>created this class</TD></TR>
 * </TABLE>
 * <BR>
 * @version $Revision: 1.2 $, $Date: 2006/11/13 08:22:04 $
 * @author  $Author: suresh $
 */
public class RetrievalShortageInquiry extends Page
{

	//#CM694696
	// Class variables -----------------------------------------------
	public jp.co.daifuku.bluedog.ui.control.Label lbl_SettingName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_SettingName" , "In_SettingName");
	public jp.co.daifuku.bluedog.ui.control.LinkButton btn_Help = jp.co.daifuku.bluedog.ui.control.LinkButtonFactory.getInstance("btn_Help" , "Help");
	public jp.co.daifuku.bluedog.ui.control.Message message = jp.co.daifuku.bluedog.ui.control.MessageFactory.getInstance("message" , "OperationMsg");
	public jp.co.daifuku.bluedog.ui.control.Tab tab_ListOutput = jp.co.daifuku.bluedog.ui.control.TabFactory.getInstance("tab_ListOutput" , "W_ListOutput");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_ToMenu = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_ToMenu" , "To_Menu");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_RegistDate = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_RegistDate" , "W_RegistDate");
	public jp.co.daifuku.bluedog.ui.control.PullDown pul_RegistDate = jp.co.daifuku.bluedog.ui.control.PullDownFactory.getInstance("pul_RegistDate" , "W_RegistDate");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ConsignorCode = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ConsignorCode" , "W_ConsignorCode");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_ConsignorCode = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_ConsignorCode" , "W_ConsignorCode");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Psearch = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Psearch" , "P_Search");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_DispType = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_DispType" , "W_GroupCondition");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_DispTypeItem = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_DispTypeItem" , "W_DispType_Item");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_DispTypePlan = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_DispTypePlan" , "W_DispType_Plan");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_PDisplay = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_PDisplay" , "W_P_Display");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Print = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Print" , "W_Print");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Clear = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Clear" , "Clear");

}
//#CM694697
//end of class
