//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2407
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
// 
//             Powered By： SR3.1(SmartRobot For SmartPersistenceLayer 3.1) 听棠
//             Created By： Administrator
//             Created Time： 2008-1-16 17:40:52
// 
// -------------------------------------------------------------
namespace BusinessEntity
{
    using System;
    using System.Collections;
    using System.Data;
    using PersistenceLayer;
    
    
    /// <summary>该类的摘要说明</summary>
    [Serializable()]
    public class FNPRINTBODYEntity : EntityObject
    {
        
        /// <summary>LISTKEY</summary>
        public const string __LISTKEY = "LISTKEY";
        
        /// <summary>RANGE1</summary>
        public const string __RANGE1 = "RANGE1";
        
        /// <summary>RANGE2</summary>
        public const string __RANGE2 = "RANGE2";
        
        /// <summary>RANGE3</summary>
        public const string __RANGE3 = "RANGE3";
        
        /// <summary>RANGE4</summary>
        public const string __RANGE4 = "RANGE4";
        
        /// <summary>RANGE5</summary>
        public const string __RANGE5 = "RANGE5";
        
        /// <summary>RANGE6</summary>
        public const string __RANGE6 = "RANGE6";
        
        /// <summary>RANGE7</summary>
        public const string __RANGE7 = "RANGE7";
        
        /// <summary>RANGE8</summary>
        public const string __RANGE8 = "RANGE8";
        
        /// <summary>RANGE9</summary>
        public const string __RANGE9 = "RANGE9";
        
        /// <summary>RANGE10</summary>
        public const string __RANGE10 = "RANGE10";
        
        /// <summary>RANGE11</summary>
        public const string __RANGE11 = "RANGE11";

        private string m_LISTKEY;
        
        private string m_RANGE1;
        
        private string m_RANGE2;
        
        private string m_RANGE3;
        
        private string m_RANGE4;
        
        private string m_RANGE5;
        
        private string m_RANGE6;
        
        private string m_RANGE7;
        
        private string m_RANGE8;
        
        private string m_RANGE9;
        
        private string m_RANGE10;
        
        private string m_RANGE11;
        
        /// <summary>构造函数</summary>
        public FNPRINTBODYEntity()
        {
        }
        
        /// <summary>属性LISTKEY </summary>
        public string LISTKEY
        {
            get
            {
                return this.m_LISTKEY;
            }
            set
            {
                this.m_LISTKEY = value;
            }
        }
        
        /// <summary>属性RANGE1 </summary>
        public string RANGE1
        {
            get
            {
                return this.m_RANGE1;
            }
            set
            {
                this.m_RANGE1 = value;
            }
        }
        
        /// <summary>属性RANGE2 </summary>
        public string RANGE2
        {
            get
            {
                return this.m_RANGE2;
            }
            set
            {
                this.m_RANGE2 = value;
            }
        }
        
        /// <summary>属性RANGE3 </summary>
        public string RANGE3
        {
            get
            {
                return this.m_RANGE3;
            }
            set
            {
                this.m_RANGE3 = value;
            }
        }
        
        /// <summary>属性RANGE4 </summary>
        public string RANGE4
        {
            get
            {
                return this.m_RANGE4;
            }
            set
            {
                this.m_RANGE4 = value;
            }
        }
        
        /// <summary>属性RANGE5 </summary>
        public string RANGE5
        {
            get
            {
                return this.m_RANGE5;
            }
            set
            {
                this.m_RANGE5 = value;
            }
        }
        
        /// <summary>属性RANGE6 </summary>
        public string RANGE6
        {
            get
            {
                return this.m_RANGE6;
            }
            set
            {
                this.m_RANGE6 = value;
            }
        }
        
        /// <summary>属性RANGE7 </summary>
        public string RANGE7
        {
            get
            {
                return this.m_RANGE7;
            }
            set
            {
                this.m_RANGE7 = value;
            }
        }
        
        /// <summary>属性RANGE8 </summary>
        public string RANGE8
        {
            get
            {
                return this.m_RANGE8;
            }
            set
            {
                this.m_RANGE8 = value;
            }
        }
        
        /// <summary>属性RANGE9 </summary>
        public string RANGE9
        {
            get
            {
                return this.m_RANGE9;
            }
            set
            {
                this.m_RANGE9 = value;
            }
        }
        
        /// <summary>属性RANGE10 </summary>
        public string RANGE10
        {
            get
            {
                return this.m_RANGE10;
            }
            set
            {
                this.m_RANGE10 = value;
            }
        }
        
        /// <summary>属性RANGE11 </summary>
        public string RANGE11
        {
            get
            {
                return this.m_RANGE11;
            }
            set
            {
                this.m_RANGE11 = value;
            }
        }
    }
    
    /// FNPRINTBODYEntity执行类
    public abstract class FNPRINTBODYEntityAction
    {
        
        private FNPRINTBODYEntityAction()
        {
        }
        
        public static void Save(FNPRINTBODYEntity obj)
        {
            if (obj!=null)
            {
                obj.Save();
            }
        }
        
        /// <summary>根据主键获取一个实体</summary>
        public static FNPRINTBODYEntity RetrieveAFNPRINTBODYEntity()
        {
            FNPRINTBODYEntity obj=new FNPRINTBODYEntity();
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static EntityContainer RetrieveFNPRINTBODYEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(FNPRINTBODYEntity));
            return rc.AsEntityContainer();
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static DataTable GetFNPRINTBODYEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(FNPRINTBODYEntity));
            return rc.AsDataTable();
        }
    }
}
