// $Id: ListFolderSelect.java,v 1.2 2006/11/13 08:19:00 suresh Exp $

//#CM692325
/*
 * Copyright 2000-2001 DAIFUKU Co.,Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of DAIFUKU Co.,Ltd.
 * Use is subject to license terms.
 */
package jp.co.daifuku.wms.base.system.display.web.listbox.listfolderselect;
import jp.co.daifuku.bluedog.ui.control.Page;

//#CM692326
/**
 * Non variable class generated by a tool.
 * 
 * <BR>
 * <TABLE BORDER="1" CELLPADDING="3" CELLSPACING="0">
 * <TR BGCOLOR="#CCCCFF" CLASS="TableHeadingColor"><TD>Date</TD><TD>Name</TD><TD>Comment</TD></TR>
 * <TR><TD>2004/02/13</TD><TD>N.Sawa(DFK)</TD><TD>created this class</TD></TR>
 * </TABLE>
 * <BR>
 * @version $Revision: 1.2 $, $Date: 2006/11/13 08:19:00 $
 * @author  $Author: suresh $
 */
public class ListFolderSelect extends Page
{

	//#CM692327
	// Class variables -----------------------------------------------
	public jp.co.daifuku.bluedog.ui.control.Message message = jp.co.daifuku.bluedog.ui.control.MessageFactory.getInstance("message" , "OperationMsg");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Folder = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Folder" , "W_Folder");
	public jp.co.daifuku.bluedog.ui.control.PullDown pul_Folder = jp.co.daifuku.bluedog.ui.control.PullDownFactory.getInstance("pul_Folder" , "W_Folder");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Up = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Up" , "W_Up");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Select = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Select" , "W_Select");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Close = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Close" , "Close");

}
//#CM692328
//end of class
