// $Id: skelten.java,v 1.2 2007/03/07 07:45:22 suresh Exp $

/*
 * Copyright 2000-2001 DAIFUKU Co.,Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of DAIFUKU Co.,Ltd.
 * Use is subject to license terms.
 */
package jp.co.daifuku.wms.YkkGMAX.Inquiry;
import jp.co.daifuku.bluedog.ui.control.Page;

/**
 * This class can not be changed and it is generated by ScreenGenerator.
 * 
 * <BR>
 * <TABLE BORDER="1" CELLPADDING="3" CELLSPACING="0">
 * <TR BGCOLOR="#CCCCFF" CLASS="TableHeadingColor"><TD>Date</TD><TD>Name</TD><TD>Comment</TD></TR>
 * <TR><TD>2004/02/13</TD><TD>N.Sawa(DFK)</TD><TD>created this class</TD></TR>
 * </TABLE>
 * <BR>
 * @version $Revision: 1.2 $, $Date: 2007/03/07 07:45:22 $
 * @author  $Author: suresh $
 */
public class IOHistorySummaryStation extends Page
{

	// Class variables -----------------------------------------------

	/**
	 * ControlID	lbl_SettingName
	 * TemplateKey	In_SettingName
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_SettingName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_SettingName" , "In_SettingName");

	/**
	 * ControlID	btn_Help
	 * TemplateKey	Help
	 * ControlType	LinkButton
	 */
	public jp.co.daifuku.bluedog.ui.control.LinkButton btn_Help = jp.co.daifuku.bluedog.ui.control.LinkButtonFactory.getInstance("btn_Help" , "Help");

	/**
	 * ControlID	message
	 * TemplateKey	OperationMsg
	 * ControlType	Message
	 */
	public jp.co.daifuku.bluedog.ui.control.Message message = jp.co.daifuku.bluedog.ui.control.MessageFactory.getInstance("message" , "OperationMsg");

	/**
	 * ControlID	tab
	 * TemplateKey	YKK_TAB_Inquiry
	 * ControlType	Tab
	 */
	public jp.co.daifuku.bluedog.ui.control.Tab tab = jp.co.daifuku.bluedog.ui.control.TabFactory.getInstance("tab" , "YKK_TAB_Inquiry");

	/**
	 * ControlID	btn_ToMenu
	 * TemplateKey	To_Menu
	 * ControlType	SubmitButton
	 */
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_ToMenu = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_ToMenu" , "To_Menu");

	/**
	 * ControlID	lbl_DateTimeRange
	 * TemplateKey	YKK_LBL_DateTimeRange
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_DateTimeRange = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_DateTimeRange" , "YKK_LBL_DateTimeRange");

	/**
	 * ControlID	lbl_DateFrom
	 * TemplateKey	YKK_LBL_Date
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_DateFrom = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_DateFrom" , "YKK_LBL_Date");

	/**
	 * ControlID	txt_DateFrom
	 * TemplateKey	YKK_TXT_DateFrom
	 * ControlType	DateTextBox
	 */
	public jp.co.daifuku.bluedog.ui.control.DateTextBox txt_DateFrom = jp.co.daifuku.bluedog.ui.control.DateTextBoxFactory.getInstance("txt_DateFrom" , "YKK_TXT_DateFrom");

	/**
	 * ControlID	lbl_TimeFrom
	 * TemplateKey	YKK_LBL_Time
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_TimeFrom = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_TimeFrom" , "YKK_LBL_Time");

	/**
	 * ControlID	txt_TimeFrom
	 * TemplateKey	YKK_TXT_TimeFrom
	 * ControlType	TimeTextBox
	 */
	public jp.co.daifuku.bluedog.ui.control.TimeTextBox txt_TimeFrom = jp.co.daifuku.bluedog.ui.control.TimeTextBoxFactory.getInstance("txt_TimeFrom" , "YKK_TXT_TimeFrom");

	/**
	 * ControlID	lbl_to
	 * TemplateKey	YKK_LBL_to
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_to = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_to" , "YKK_LBL_to");

	/**
	 * ControlID	lbl_DateTo
	 * TemplateKey	YKK_LBL_Date
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_DateTo = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_DateTo" , "YKK_LBL_Date");

	/**
	 * ControlID	txt_DateTo
	 * TemplateKey	YKK_TXT_DateTo
	 * ControlType	DateTextBox
	 */
	public jp.co.daifuku.bluedog.ui.control.DateTextBox txt_DateTo = jp.co.daifuku.bluedog.ui.control.DateTextBoxFactory.getInstance("txt_DateTo" , "YKK_TXT_DateTo");

	/**
	 * ControlID	lbl_TimeTo
	 * TemplateKey	YKK_LBL_Time
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_TimeTo = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_TimeTo" , "YKK_LBL_Time");

	/**
	 * ControlID	txt_TimeTo
	 * TemplateKey	YKK_TXT_TimeTo
	 * ControlType	TimeTextBox
	 */
	public jp.co.daifuku.bluedog.ui.control.TimeTextBox txt_TimeTo = jp.co.daifuku.bluedog.ui.control.TimeTextBoxFactory.getInstance("txt_TimeTo" , "YKK_TXT_TimeTo");

	/**
	 * ControlID	slb_Download
	 * TemplateKey	W_Download
	 * ControlType	SubmitLabel
	 */
	public jp.co.daifuku.bluedog.ui.control.SubmitLabel slb_Download = jp.co.daifuku.bluedog.ui.control.SubmitLabelFactory.getInstance("slb_Download" , "W_Download");

	/**
	 * ControlID	btn_Show
	 * TemplateKey	YKK_BTN_Show
	 * ControlType	SubmitButton
	 */
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Show = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Show" , "YKK_BTN_Show");

	/**
	 * ControlID	btn_CSV
	 * TemplateKey	YKK_BTN_CSV
	 * ControlType	SubmitButton
	 */
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_CSV = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_CSV" , "YKK_BTN_CSV");

	/**
	 * ControlID	lbl_StockinStation
	 * TemplateKey	YKK_LBL_StockinStation
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_StockinStation = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_StockinStation" , "YKK_LBL_StockinStation");

	/**
	 * ControlID	lst_IOHistorySummaryStationUp
	 * TemplateKey	YKK_LST_IOHistorySummaryStationUp
	 * ControlType	ListCell
	 */
	public jp.co.daifuku.bluedog.ui.control.ListCell lst_IOHistorySummaryStationUp = jp.co.daifuku.bluedog.ui.control.ListCellFactory.getInstance("lst_IOHistorySummaryStationUp" , "YKK_LST_IOHistorySummaryStationUp");

	/**
	 * ControlID	lbl_UnitStockoutStation
	 * TemplateKey	YKK-LBL-UnitStockoutStation
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_UnitStockoutStation = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_UnitStockoutStation" , "YKK-LBL-UnitStockoutStation");

	/**
	 * ControlID	lst_IOHistorySummaryStationMid
	 * TemplateKey	YKK_LST_IOHistorySummaryStationMid
	 * ControlType	ListCell
	 */
	public jp.co.daifuku.bluedog.ui.control.ListCell lst_IOHistorySummaryStationMid = jp.co.daifuku.bluedog.ui.control.ListCellFactory.getInstance("lst_IOHistorySummaryStationMid" , "YKK_LST_IOHistorySummaryStationMid");

	/**
	 * ControlID	lbl_PickingStation
	 * TemplateKey	YKK-LBL-PickingStation
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_PickingStation = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_PickingStation" , "YKK-LBL-PickingStation");

	/**
	 * ControlID	lst_IOHistorySummaryStationLow
	 * TemplateKey	YKK_LST_IOHistorySummaryStationLow
	 * ControlType	ListCell
	 */
	public jp.co.daifuku.bluedog.ui.control.ListCell lst_IOHistorySummaryStationLow = jp.co.daifuku.bluedog.ui.control.ListCellFactory.getInstance("lst_IOHistorySummaryStationLow" , "YKK_LST_IOHistorySummaryStationLow");

}
//end of class
