// $Id: skelten.java,v 1.2 2007/03/07 07:45:22 suresh Exp $

/*
 * Copyright 2000-2001 DAIFUKU Co.,Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of DAIFUKU Co.,Ltd.
 * Use is subject to license terms.
 */
package jp.co.daifuku.wms.YkkGMAX.Inquiry;
import jp.co.daifuku.bluedog.ui.control.Page;

/**
 * This class can not be changed and it is generated by ScreenGenerator.
 * 
 * <BR>
 * <TABLE BORDER="1" CELLPADDING="3" CELLSPACING="0">
 * <TR BGCOLOR="#CCCCFF" CLASS="TableHeadingColor"><TD>Date</TD><TD>Name</TD><TD>Comment</TD></TR>
 * <TR><TD>2004/02/13</TD><TD>N.Sawa(DFK)</TD><TD>created this class</TD></TR>
 * </TABLE>
 * <BR>
 * @version $Revision: 1.2 $, $Date: 2007/03/07 07:45:22 $
 * @author  $Author: suresh $
 */
public class OvertimeStorageInfo extends Page
{

	// Class variables -----------------------------------------------
	public jp.co.daifuku.bluedog.ui.control.Label lbl_SettingName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_SettingName" , "YKK_LBL_OvertimeStorageInfo");
	public jp.co.daifuku.bluedog.ui.control.LinkButton btn_Help = jp.co.daifuku.bluedog.ui.control.LinkButtonFactory.getInstance("btn_Help" , "Help");
	public jp.co.daifuku.bluedog.ui.control.Message message = jp.co.daifuku.bluedog.ui.control.MessageFactory.getInstance("message" , "OperationMsg");
	public jp.co.daifuku.bluedog.ui.control.Tab tab = jp.co.daifuku.bluedog.ui.control.TabFactory.getInstance("tab" , "YKK_TAB_SearchReport");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_ToMenu = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_ToMenu" , "To_Menu");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_DepositoryType = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_DepositoryType" , "YKK_LBL_DepositoryType");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_AllTypes = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_AllTypes" , "YKK_RDO_AllTypesChecked");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_AutoDepository = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_AutoDepository" , "YKK_RDO_AutoDepository");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_FlatDepository = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_FlatDepository" , "YKK_RDO_FlatDepository");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_OrderBy = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_OrderBy" , "YKK_LBL_OrderBy");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_OvertimeStorageStockout = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_OvertimeStorageStockout" , "YKK_RDO_OvertimeStorageStockoutChecked");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_ItemCode = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_ItemCode" , "YKK_RDO_ItemCode_Overtime");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_BenchmarkDate = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_BenchmarkDate" , "YKK_LBL_BenchmarkDate");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Star = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Star" , "YKK_LBL_Star");
	public jp.co.daifuku.bluedog.ui.control.DateTextBox txt_BenchmarkDate = jp.co.daifuku.bluedog.ui.control.DateTextBoxFactory.getInstance("txt_BenchmarkDate" , "YKK_TXT_BenchmarkDate");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_BenchmarkObject = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_BenchmarkObject" , "YKK_LBL_BenchmarkObject");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_ReceiveMessageDateTime = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_ReceiveMessageDateTime" , "YKK_RDO_ReceiveMessageDateTimeChecked");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_StockinDateTime = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_StockinDateTime" , "YKK_RDO_StockinDateTime");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_LastUpdateDate = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_LastUpdateDate" , "YKK_RDO_LastUpdateDate");
	public jp.co.daifuku.bluedog.ui.control.SubmitLabel slb_Download = jp.co.daifuku.bluedog.ui.control.SubmitLabelFactory.getInstance("slb_Download" , "W_Download");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Show = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Show" , "YKK_BTN_Show_POPUP");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Print = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Print" , "YKK_BTN_Print");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_CSV = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_CSV" , "YKK_BTN_CSV");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Clear = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Clear" , "YKK_BTN_Clear");

}
//end of class
