// $Id: skelten.java,v 1.2 2007/03/07 07:45:22 suresh Exp $

/*
 * Copyright 2000-2001 DAIFUKU Co.,Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of DAIFUKU Co.,Ltd.
 * Use is subject to license terms.
 */
package jp.co.daifuku.wms.YkkGMAX.Inquiry;
import jp.co.daifuku.bluedog.ui.control.Page;

/**
 * This class can not be changed and it is generated by ScreenGenerator.
 * 
 * <BR>
 * <TABLE BORDER="1" CELLPADDING="3" CELLSPACING="0">
 * <TR BGCOLOR="#CCCCFF" CLASS="TableHeadingColor"><TD>Date</TD><TD>Name</TD><TD>Comment</TD></TR>
 * <TR><TD>2004/02/13</TD><TD>N.Sawa(DFK)</TD><TD>created this class</TD></TR>
 * </TABLE>
 * <BR>
 * @version $Revision: 1.2 $, $Date: 2007/03/07 07:45:22 $
 * @author  $Author: suresh $
 */
public class RetrievalOrderPrint extends Page
{

	// Class variables -----------------------------------------------

	/**
	 * ControlID	lbl_SettingName
	 * TemplateKey	In_SettingName
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_SettingName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_SettingName" , "In_SettingName");

	/**
	 * ControlID	btn_Help
	 * TemplateKey	Help
	 * ControlType	LinkButton
	 */
	public jp.co.daifuku.bluedog.ui.control.LinkButton btn_Help = jp.co.daifuku.bluedog.ui.control.LinkButtonFactory.getInstance("btn_Help" , "Help");

	/**
	 * ControlID	message
	 * TemplateKey	OperationMsg
	 * ControlType	Message
	 */
	public jp.co.daifuku.bluedog.ui.control.Message message = jp.co.daifuku.bluedog.ui.control.MessageFactory.getInstance("message" , "OperationMsg");

	/**
	 * ControlID	tab
	 * TemplateKey	YKK_TAB_Inquiry
	 * ControlType	Tab
	 */
	public jp.co.daifuku.bluedog.ui.control.Tab tab = jp.co.daifuku.bluedog.ui.control.TabFactory.getInstance("tab" , "YKK_TAB_Inquiry");

	/**
	 * ControlID	btn_ToMenu
	 * TemplateKey	To_Menu
	 * ControlType	SubmitButton
	 */
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_ToMenu = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_ToMenu" , "To_Menu");

	/**
	 * ControlID	lbl_DateTimeRange
	 * TemplateKey	YKK_LBL_DateTimeRange
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_DateTimeRange = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_DateTimeRange" , "YKK_LBL_DateTimeRange");

	/**
	 * ControlID	lbl_Star1
	 * TemplateKey	YKK_LBL_Star
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Star1 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Star1" , "YKK_LBL_Star");

	/**
	 * ControlID	lbl_DateFrom
	 * TemplateKey	YKK_LBL_Date
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_DateFrom = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_DateFrom" , "YKK_LBL_Date");

	/**
	 * ControlID	txt_DateFrom
	 * TemplateKey	YKK_TXT_DateFrom
	 * ControlType	DateTextBox
	 */
	public jp.co.daifuku.bluedog.ui.control.DateTextBox txt_DateFrom = jp.co.daifuku.bluedog.ui.control.DateTextBoxFactory.getInstance("txt_DateFrom" , "YKK_TXT_DateFrom");

	/**
	 * ControlID	lbl_TimeFrom
	 * TemplateKey	YKK_LBL_Time
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_TimeFrom = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_TimeFrom" , "YKK_LBL_Time");

	/**
	 * ControlID	txt_TimeFrom
	 * TemplateKey	YKK_TXT_TimeFrom
	 * ControlType	TimeTextBox
	 */
	public jp.co.daifuku.bluedog.ui.control.TimeTextBox txt_TimeFrom = jp.co.daifuku.bluedog.ui.control.TimeTextBoxFactory.getInstance("txt_TimeFrom" , "YKK_TXT_TimeFrom");

	/**
	 * ControlID	lbl_to
	 * TemplateKey	YKK_LBL_to
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_to = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_to" , "YKK_LBL_to");

	/**
	 * ControlID	lbl_DateTo
	 * TemplateKey	YKK_LBL_Date
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_DateTo = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_DateTo" , "YKK_LBL_Date");

	/**
	 * ControlID	txt_DateTo
	 * TemplateKey	YKK_TXT_DateTo
	 * ControlType	DateTextBox
	 */
	public jp.co.daifuku.bluedog.ui.control.DateTextBox txt_DateTo = jp.co.daifuku.bluedog.ui.control.DateTextBoxFactory.getInstance("txt_DateTo" , "YKK_TXT_DateTo");

	/**
	 * ControlID	lbl_TimeTo
	 * TemplateKey	YKK_LBL_Time
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_TimeTo = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_TimeTo" , "YKK_LBL_Time");

	/**
	 * ControlID	txt_TimeTo
	 * TemplateKey	YKK_TXT_TimeTo
	 * ControlType	TimeTextBox
	 */
	public jp.co.daifuku.bluedog.ui.control.TimeTextBox txt_TimeTo = jp.co.daifuku.bluedog.ui.control.TimeTextBoxFactory.getInstance("txt_TimeTo" , "YKK_TXT_TimeTo");

	/**
	 * ControlID	lbl_Section
	 * TemplateKey	YKK_LBL_Section
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Section = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Section" , "YKK_LBL_Section");

	/**
	 * ControlID	lbl_Star2
	 * TemplateKey	YKK_LBL_Star
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Star2 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Star2" , "YKK_LBL_Star");

	/**
	 * ControlID	txt_Section
	 * TemplateKey	YKK_TXT_Section
	 * ControlType	FreeTextBox
	 */
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_Section = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_Section" , "YKK_TXT_Section");

	/**
	 * ControlID	lbl_Line
	 * TemplateKey	YKK_LBL_Line
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Line = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Line" , "YKK_LBL_Line");

	/**
	 * ControlID	txt_Line
	 * TemplateKey	YKK_TXT_Line
	 * ControlType	FreeTextBox
	 */
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_Line = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_Line" , "YKK_TXT_Line");

	/**
	 * ControlID	lbl_WhenNextWorkBegin
	 * TemplateKey	YKK_LBL_WhenNextWorkBegin
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_WhenNextWorkBegin = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_WhenNextWorkBegin" , "YKK_LBL_WhenNextWorkBegin");

	/**
	 * ControlID	txt_WhenNextWorkBegin
	 * TemplateKey	YKK_TXT_WhenNextWorkBegin
	 * ControlType	DateTextBox
	 */
	public jp.co.daifuku.bluedog.ui.control.DateTextBox txt_WhenNextWorkBegin = jp.co.daifuku.bluedog.ui.control.DateTextBoxFactory.getInstance("txt_WhenNextWorkBegin" , "YKK_TXT_WhenNextWorkBegin");

	/**
	 * ControlID	lbl_Dynasty
	 * TemplateKey	YKK-LBL-Dynasty
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Dynasty = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Dynasty" , "YKK-LBL-Dynasty");

	/**
	 * ControlID	lbl_ItemNo
	 * TemplateKey	YKK_LBL_ItemNo
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ItemNo = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ItemNo" , "YKK_LBL_ItemNo");

	/**
	 * ControlID	txt_ItemNo
	 * TemplateKey	YKK_TXT_ItemNo
	 * ControlType	FreeTextBox
	 */
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_ItemNo = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_ItemNo" , "YKK_TXT_ItemNo");

	/**
	 * ControlID	btn_Search_POPUP
	 * TemplateKey	YKK_BTN_Search_POPUP
	 * ControlType	SubmitButton
	 */
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Search_POPUP = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Search_POPUP" , "YKK_BTN_Search_POPUP");

	/**
	 * ControlID	txt_ItemName1
	 * TemplateKey	YKK_TXT_ItemName1
	 * ControlType	FreeTextBox
	 */
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_ItemName1 = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_ItemName1" , "YKK_TXT_ItemName1");

	/**
	 * ControlID	lbl_ColorCode
	 * TemplateKey	YKK_LBL_ColorCode
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ColorCode = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ColorCode" , "YKK_LBL_ColorCode");

	/**
	 * ControlID	txt_ColorCode
	 * TemplateKey	YKK_TXT_ColorCode
	 * ControlType	FreeTextBox
	 */
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_ColorCode = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_ColorCode" , "YKK_TXT_ColorCode");

	/**
	 * ControlID	txt_ItemName2
	 * TemplateKey	YKK_TXT_ItemName2
	 * ControlType	FreeTextBox
	 */
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_ItemName2 = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_ItemName2" , "YKK_TXT_ItemName2");

	/**
	 * ControlID	txt_ItemName3
	 * TemplateKey	YKK_TXT_ItemName3
	 * ControlType	FreeTextBox
	 */
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_ItemName3 = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_ItemName3" , "YKK_TXT_ItemName3");

	/**
	 * ControlID	lbl_SortCondition
	 * TemplateKey	YKK-LBL-SortCondition
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_SortCondition = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_SortCondition" , "YKK-LBL-SortCondition");

	/**
	 * ControlID	rdo_WhenNextWorkBegin
	 * TemplateKey	YKK_RDO_WhenNextWorkBegin
	 * ControlType	RadioButton
	 */
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_WhenNextWorkBegin = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_WhenNextWorkBegin" , "YKK_RDO_WhenNextWorkBegin");

	/**
	 * ControlID	rdo_ItemNo
	 * TemplateKey	YKK_RDO_ItemNo
	 * ControlType	RadioButton
	 */
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_ItemNo = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_ItemNo" , "YKK_RDO_ItemNo");

	/**
	 * ControlID	slb_Popup
	 * TemplateKey	YKK_SLB_SubmitLabelPopup
	 * ControlType	SubmitLabel
	 */
	public jp.co.daifuku.bluedog.ui.control.SubmitLabel slb_Popup = jp.co.daifuku.bluedog.ui.control.SubmitLabelFactory.getInstance("slb_Popup" , "YKK_SLB_SubmitLabelPopup");

	/**
	 * ControlID	btn_Show
	 * TemplateKey	YKK_BTN_Show_NA
	 * ControlType	SubmitButton
	 */
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Show = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Show" , "YKK_BTN_Show_NA");

	/**
	 * ControlID	btn_Clear
	 * TemplateKey	YKK_BTN_Clear
	 * ControlType	SubmitButton
	 */
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Clear = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Clear" , "YKK_BTN_Clear");

}
//end of class
