// $Id: skelten.java,v 1.2 2007/03/07 07:45:22 suresh Exp $

/*
 * Copyright 2000-2001 DAIFUKU Co.,Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of DAIFUKU Co.,Ltd.
 * Use is subject to license terms.
 */
package jp.co.daifuku.wms.YkkGMAX.Inquiry;
import jp.co.daifuku.bluedog.ui.control.Page;

/**
 * This class can not be changed and it is generated by ScreenGenerator.
 * 
 * <BR>
 * <TABLE BORDER="1" CELLPADDING="3" CELLSPACING="0">
 * <TR BGCOLOR="#CCCCFF" CLASS="TableHeadingColor"><TD>Date</TD><TD>Name</TD><TD>Comment</TD></TR>
 * <TR><TD>2004/02/13</TD><TD>N.Sawa(DFK)</TD><TD>created this class</TD></TR>
 * </TABLE>
 * <BR>
 * @version $Revision: 1.2 $, $Date: 2007/03/07 07:45:22 $
 * @author  $Author: suresh $
 */
public class RetrievalOrderPrintPopup extends Page
{

	// Class variables -----------------------------------------------

	/**
	 * ControlID	message
	 * TemplateKey	OperationMsg
	 * ControlType	Message
	 */
	public jp.co.daifuku.bluedog.ui.control.Message message = jp.co.daifuku.bluedog.ui.control.MessageFactory.getInstance("message" , "OperationMsg");

	/**
	 * ControlID	lbl_Section
	 * TemplateKey	YKK_LBL_Section
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Section = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Section" , "YKK_LBL_Section");

	/**
	 * ControlID	txt_Section
	 * TemplateKey	YKK_TXT_Section
	 * ControlType	FreeTextBox
	 */
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_Section = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_Section" , "YKK_TXT_Section");

	/**
	 * ControlID	lbl_Line
	 * TemplateKey	YKK_LBL_Line
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Line = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Line" , "YKK_LBL_Line");

	/**
	 * ControlID	txt_Line
	 * TemplateKey	YKK_TXT_Line
	 * ControlType	FreeTextBox
	 */
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_Line = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_Line" , "YKK_TXT_Line");

	/**
	 * ControlID	lbl_WhenNextWorkBegin
	 * TemplateKey	YKK_LBL_WhenNextWorkBegin
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_WhenNextWorkBegin = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_WhenNextWorkBegin" , "YKK_LBL_WhenNextWorkBegin");

	/**
	 * ControlID	txt_WhenNextWorkBegin
	 * TemplateKey	YKK_TXT_WhenNextWorkBegin
	 * ControlType	DateTextBox
	 */
	public jp.co.daifuku.bluedog.ui.control.DateTextBox txt_WhenNextWorkBegin = jp.co.daifuku.bluedog.ui.control.DateTextBoxFactory.getInstance("txt_WhenNextWorkBegin" , "YKK_TXT_WhenNextWorkBegin");

	/**
	 * ControlID	lbl_ItemNo
	 * TemplateKey	YKK_LBL_ItemNo
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ItemNo = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ItemNo" , "YKK_LBL_ItemNo");

	/**
	 * ControlID	txt_ItemNo
	 * TemplateKey	YKK_TXT_ItemNo
	 * ControlType	FreeTextBox
	 */
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_ItemNo = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_ItemNo" , "YKK_TXT_ItemNo");

	/**
	 * ControlID	lbl_ColorCode
	 * TemplateKey	YKK_LBL_ColorCode
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ColorCode = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ColorCode" , "YKK_LBL_ColorCode");

	/**
	 * ControlID	txt_ColorCode
	 * TemplateKey	YKK_TXT_ColorCode
	 * ControlType	FreeTextBox
	 */
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_ColorCode = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_ColorCode" , "YKK_TXT_ColorCode");

	/**
	 * ControlID	btn_Close_U
	 * TemplateKey	Close
	 * ControlType	SubmitButton
	 */
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Close_U = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Close_U" , "Close");

	/**
	 * ControlID	lst_RetrievalOrderPrintPopup1
	 * TemplateKey	YKK_LST_RetrievalOrderPrintPopup
	 * ControlType	ListCell
	 */
	public jp.co.daifuku.bluedog.ui.control.ListCell lst_RetrievalOrderPrintPopup1 = jp.co.daifuku.bluedog.ui.control.ListCellFactory.getInstance("lst_RetrievalOrderPrintPopup1" , "YKK_LST_RetrievalOrderPrintPopup");

	/**
	 * ControlID	pgr_D
	 * TemplateKey	Pager
	 * ControlType	Pager
	 */
	public jp.co.daifuku.bluedog.ui.control.Pager pgr_D = jp.co.daifuku.bluedog.ui.control.PagerFactory.getInstance("pgr_D" , "Pager");

	/**
	 * ControlID	btn_SelectAllUp
	 * TemplateKey	YKK_BTN_SelectAll
	 * ControlType	SubmitButton
	 */
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_SelectAllUp = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_SelectAllUp" , "YKK_BTN_SelectAll");

	/**
	 * ControlID	btn_UnselectAllUp
	 * TemplateKey	YKK_BTN_UnselectAll
	 * ControlType	SubmitButton
	 */
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_UnselectAllUp = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_UnselectAllUp" , "YKK_BTN_UnselectAll");

	/**
	 * ControlID	btn_Input
	 * TemplateKey	YKK_BTN_Input
	 * ControlType	SubmitButton
	 */
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Input = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Input" , "YKK_BTN_Input");

	/**
	 * ControlID	btn_CSV_U
	 * TemplateKey	YKK_BTN_CSV
	 * ControlType	SubmitButton
	 */
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_CSV_U = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_CSV_U" , "YKK_BTN_CSV");

	/**
	 * ControlID	lbl_TicketNo
	 * TemplateKey	YKK_LBL_TicketNo
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_TicketNo = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_TicketNo" , "YKK_LBL_TicketNo");

	/**
	 * ControlID	txt_TicketNo
	 * TemplateKey	YKK_TXT_TicketNo_Enter
	 * ControlType	FreeTextBox
	 */
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_TicketNo = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_TicketNo" , "YKK_TXT_TicketNo_Enter");

	/**
	 * ControlID	btn_Input_TicketNo
	 * TemplateKey	YKK_BTN_Input
	 * ControlType	SubmitButton
	 */
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Input_TicketNo = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Input_TicketNo" , "YKK_BTN_Input");

	/**
	 * ControlID	lbl_BucketNo
	 * TemplateKey	YKK_LBL_BucketNo
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_BucketNo = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_BucketNo" , "YKK_LBL_BucketNo");

	/**
	 * ControlID	txt_BucketNo
	 * TemplateKey	YKK_TXT_BucketNo
	 * ControlType	FreeTextBox
	 */
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_BucketNo = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_BucketNo" , "YKK_TXT_BucketNo");

	/**
	 * ControlID	lbl_Total
	 * TemplateKey	YKK-LBL-Total
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Total = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Total" , "YKK-LBL-Total");

	/**
	 * ControlID	lbl_HowMuch
	 * TemplateKey	YKK-LBL-HowMuch
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_HowMuch = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_HowMuch" , "YKK-LBL-HowMuch");

	/**
	 * ControlID	lbl_Row
	 * TemplateKey	YKK-LBL-Row
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Row = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Row" , "YKK-LBL-Row");

	/**
	 * ControlID	lbl_Slash
	 * TemplateKey	YKK_LBL_Slash
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Slash = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Slash" , "YKK_LBL_Slash");

	/**
	 * ControlID	lbl_HowMuch2
	 * TemplateKey	YKK-LBL-HowMuch
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_HowMuch2 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_HowMuch2" , "YKK-LBL-HowMuch");

	/**
	 * ControlID	lbl_Page
	 * TemplateKey	YKK-LBL-Page
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Page = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Page" , "YKK-LBL-Page");

	/**
	 * ControlID	lst_RetrievalOrderPrintPopup2
	 * TemplateKey	YKK_LST_RetrievalOrderPrintPopup
	 * ControlType	ListCell
	 */
	public jp.co.daifuku.bluedog.ui.control.ListCell lst_RetrievalOrderPrintPopup2 = jp.co.daifuku.bluedog.ui.control.ListCellFactory.getInstance("lst_RetrievalOrderPrintPopup2" , "YKK_LST_RetrievalOrderPrintPopup");

	/**
	 * ControlID	slb_Download
	 * TemplateKey	W_Download
	 * ControlType	SubmitLabel
	 */
	public jp.co.daifuku.bluedog.ui.control.SubmitLabel slb_Download = jp.co.daifuku.bluedog.ui.control.SubmitLabelFactory.getInstance("slb_Download" , "W_Download");

	/**
	 * ControlID	btn_SelectAllDown
	 * TemplateKey	YKK_BTN_SelectAll
	 * ControlType	SubmitButton
	 */
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_SelectAllDown = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_SelectAllDown" , "YKK_BTN_SelectAll");

	/**
	 * ControlID	btn_UnselectAllDown
	 * TemplateKey	YKK_BTN_UnselectAll
	 * ControlType	SubmitButton
	 */
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_UnselectAllDown = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_UnselectAllDown" , "YKK_BTN_UnselectAll");

	/**
	 * ControlID	btn_Delete
	 * TemplateKey	YKK_BTN_Delete
	 * ControlType	SubmitButton
	 */
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Delete = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Delete" , "YKK_BTN_Delete");

	/**
	 * ControlID	btn_CSV
	 * TemplateKey	YKK_BTN_CSV
	 * ControlType	SubmitButton
	 */
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_CSV = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_CSV" , "YKK_BTN_CSV");

	/**
	 * ControlID	btn_Print
	 * TemplateKey	YKK_BTN_Print
	 * ControlType	SubmitButton
	 */
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Print = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Print" , "YKK_BTN_Print");

	/**
	 * ControlID	btn_Close_D
	 * TemplateKey	Close
	 * ControlType	SubmitButton
	 */
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Close_D = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Close_D" , "Close");

}
//end of class
