// $Id: skelten.java,v 1.2 2007/03/07 07:45:22 suresh Exp $

/*
 * Copyright 2000-2001 DAIFUKU Co.,Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of DAIFUKU Co.,Ltd.
 * Use is subject to license terms.
 */
package jp.co.daifuku.wms.YkkGMAX.Inquiry;
import jp.co.daifuku.bluedog.ui.control.Page;

/**
 * This class can not be changed and it is generated by ScreenGenerator.
 * 
 * <BR>
 * <TABLE BORDER="1" CELLPADDING="3" CELLSPACING="0">
 * <TR BGCOLOR="#CCCCFF" CLASS="TableHeadingColor"><TD>Date</TD><TD>Name</TD><TD>Comment</TD></TR>
 * <TR><TD>2004/02/13</TD><TD>N.Sawa(DFK)</TD><TD>created this class</TD></TR>
 * </TABLE>
 * <BR>
 * @version $Revision: 1.2 $, $Date: 2007/03/07 07:45:22 $
 * @author  $Author: suresh $
 */
public class TicketNoItemStorageInfo extends Page
{

	// Class variables -----------------------------------------------
	public jp.co.daifuku.bluedog.ui.control.Label lbl_SettingName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_SettingName" , "YKK_LBL_TicketNoItemStorageInfo");
	public jp.co.daifuku.bluedog.ui.control.LinkButton btn_Help = jp.co.daifuku.bluedog.ui.control.LinkButtonFactory.getInstance("btn_Help" , "Help");
	public jp.co.daifuku.bluedog.ui.control.Message message = jp.co.daifuku.bluedog.ui.control.MessageFactory.getInstance("message" , "OperationMsg");
	public jp.co.daifuku.bluedog.ui.control.Tab tab = jp.co.daifuku.bluedog.ui.control.TabFactory.getInstance("tab" , "YKK_TAB_SearchReport");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_ToMenu = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_ToMenu" , "To_Menu");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Depository = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Depository" , "YKK_LBL_Depository");
	public jp.co.daifuku.bluedog.ui.control.PullDown pul_Depository = jp.co.daifuku.bluedog.ui.control.PullDownFactory.getInstance("pul_Depository" , "YKK_PUL_Depository");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Division = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Division" , "YKK_LBL_Division");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_TicketNo = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_TicketNo" , "YKK_RDO_TicketNoChecked");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_ItemCode = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_ItemCode" , "YKK_RDO_ItemCode_Division");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_BucketNo = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_BucketNo" , "YKK_RDO_BucketNo");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_InquiryRange = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_InquiryRange" , "YKK_LBL_InquiryRange");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Star1 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Star1" , "YKK_LBL_Star");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_InquiryRangeFrom = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_InquiryRangeFrom" , "YKK_TXT_InquiryRangeFrom");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_to = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_to" , "YKK_LBL_to");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_InquiryRangeTo = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_InquiryRangeTo" , "YKK_TXT_InquiryRangeTo");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_RangeSet = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_RangeSet" , "YKK_CHK_RangeSet");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ItemCode = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ItemCode" , "YKK_LBL_ItemNo");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Star2 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Star2" , "YKK_LBL_Star");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_ItemCode = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_ItemCode" , "YKK_TXT_ItemNo_Enter");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_ItemBrowse = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_ItemBrowse" , "YKK_BTN_ItemBrowse_POPUP");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ItemName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ItemName" , "YKK_LBL_ItemName");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_ItemName1 = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_ItemName1" , "YKK_TXT_ItemName1_RO");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_ItemName2 = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_ItemName2" , "YKK_TXT_ItemName2_RO");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_ItemName3 = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_ItemName3" , "YKK_TXT_ItemName3_RO");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ColorCode = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ColorCode" , "YKK_LBL_ColorCode");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_ColorCode = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_ColorCode" , "YKK_TXT_ColorCode");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_BucketNo = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_BucketNo" , "YKK_LBL_BucketNo");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Star3 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Star3" , "YKK_LBL_Star");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_BucketNo = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_BucketNo" , "YKK_TXT_BucketNo");
	public jp.co.daifuku.bluedog.ui.control.SubmitLabel slb_Download = jp.co.daifuku.bluedog.ui.control.SubmitLabelFactory.getInstance("slb_Download" , "W_Download");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Show = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Show" , "YKK_BTN_Show_POPUP");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Print = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Print" , "YKK_BTN_Print");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_CSV = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_CSV" , "YKK_BTN_CSV");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Clear = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Clear" , "YKK_BTN_Clear");

}
//end of class
