// $Id: skelten.java,v 1.2 2007/03/07 07:45:22 suresh Exp $

/*
 * Copyright 2000-2001 DAIFUKU Co.,Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of DAIFUKU Co.,Ltd.
 * Use is subject to license terms.
 */
package jp.co.daifuku.wms.YkkGMAX.Maintenance;
import jp.co.daifuku.bluedog.ui.control.Page;

/**
 * This class can not be changed and it is generated by ScreenGenerator.
 * 
 * <BR>
 * <TABLE BORDER="1" CELLPADDING="3" CELLSPACING="0">
 * <TR BGCOLOR="#CCCCFF" CLASS="TableHeadingColor"><TD>Date</TD><TD>Name</TD><TD>Comment</TD></TR>
 * <TR><TD>2004/02/13</TD><TD>N.Sawa(DFK)</TD><TD>created this class</TD></TR>
 * </TABLE>
 * <BR>
 * @version $Revision: 1.2 $, $Date: 2007/03/07 07:45:22 $
 * @author  $Author: suresh $
 */
public class ItemMasterMaintenance extends Page
{

	// Class variables -----------------------------------------------
	public jp.co.daifuku.bluedog.ui.control.Label lbl_SettingName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_SettingName" , "YKK_LBL_ItemMasterMaintenance");
	public jp.co.daifuku.bluedog.ui.control.LinkButton btn_Help = jp.co.daifuku.bluedog.ui.control.LinkButtonFactory.getInstance("btn_Help" , "Help");
	public jp.co.daifuku.bluedog.ui.control.Message message = jp.co.daifuku.bluedog.ui.control.MessageFactory.getInstance("message" , "OperationMsg");
	public jp.co.daifuku.bluedog.ui.control.Tab tab = jp.co.daifuku.bluedog.ui.control.TabFactory.getInstance("tab" , "YKK_TAB_Maintenance");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_ToMenu = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_ToMenu" , "To_Menu");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ItemCode = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ItemCode" , "YKK_LBL_ItemNo");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Star = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Star" , "YKK_LBL_Star");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_ItemCode = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_ItemCode" , "YKK_TXT_ItemNo");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_ItemCodeBrowse = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_ItemCodeBrowse" , "YKK_BTN_Search_POPUP");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ManageDivision = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ManageDivision" , "YKK_LBL_ManageDivision");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_ItemInManage = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_ItemInManage" , "YKK_RDO_ItemInManageChecked");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_ItemOutOfManage = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_ItemOutOfManage" , "YKK_RDO_ItemOutOfManage");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_DealDivision = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_DealDivision" , "YKK_LBL_DealDivision");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Add = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Add" , "YKK_BTN_Add");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Modify = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Modify" , "YKK_BTN_Modify");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Delete = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Delete" , "YKK_BTN_Delete");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ItemCode_RO = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ItemCode_RO" , "YKK_LBL_ItemNo");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_ItemCode_RO = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_ItemCode_RO" , "YKK_TXT_ItemNo_RO");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ItemName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ItemName" , "YKK_LBL_ItemName");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_ItemName1 = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_ItemName1" , "YKK_TXT_ItemName1_RO");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_ItemName2 = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_ItemName2" , "YKK_TXT_ItemName2_RO");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_ItemName3 = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_ItemName3" , "YKK_TXT_ItemName3_RO");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MasterUnit = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MasterUnit" , "YKK_LBL_MasterUnit");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_MasterUnit = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_MasterUnit" , "YKK_TXT_MasterUnit_RO");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_FullCount = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_FullCount" , "YKK_LBL_FullCount");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_FullCount = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_FullCount" , "YKK_TXT_FullCount_RO");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_AutoDepoMaxCount = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_AutoDepoMaxCount" , "YKK_LBL_AutoDepoMaxCount");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_AutoDepoMaxCount = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_AutoDepoMaxCount" , "YKK_TXT_AutoDepoMaxCount");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MasterFormerUnitCount = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MasterFormerUnitCount" , "YKK_LBL_MasterFormerUnitCount");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_MasterFormerUnitCount = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_MasterFormerUnitCount" , "YKK_TXT_MasterFormerUnitCount");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_AutoDepoMinCount = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_AutoDepoMinCount" , "YKK_LBL_AutoDepoMinCount");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_AutoDepoMinCount = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_AutoDepoMinCount" , "YKK_TXT_AutoDepoMinCount");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_AccountDivision = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_AccountDivision" , "YKK_LBL_AccountDivision");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_WithAccount = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_WithAccount" , "YKK_RDO_WithAccountChecked");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_WithOutAccount = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_WithOutAccount" , "YKK_RDO_WithOutAccount");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_PickOutDivision = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_PickOutDivision" , "YKK_LBL_PickOutDivision");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_AutoDepoPickOut = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_AutoDepoPickOut" , "YKK_RDO_AutoDepoPickOutChecked");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_FlatDepoPickOut = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_FlatDepoPickOut" , "YKK_RDO_FlatDepoPickOut");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_BagWeightDivisi = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_BagWeightDivisi" , "YKK_LBL_BagWeightDivision");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_HasBagWeightDivisi = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_HasBagWeightDivisi" , "YKK_RDO_HasBagWeightDivision");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_NoBagWeightDivisi = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_NoBagWeightDivisi" , "YKK_RDO_NoBagWeightDivision");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Set = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Set" , "YKK_BTN_Set");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Clear = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Clear" , "YKK_BTN_Clear");

}
//end of class
