// $Id: skelten.java,v 1.2 2007/03/07 07:45:22 suresh Exp $

/*
 * Copyright 2000-2001 DAIFUKU Co.,Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of DAIFUKU Co.,Ltd.
 * Use is subject to license terms.
 */
package jp.co.daifuku.wms.YkkGMAX.Maintenance;
import jp.co.daifuku.bluedog.ui.control.Page;

/**
 * This class can not be changed and it is generated by ScreenGenerator.
 * 
 * <BR>
 * <TABLE BORDER="1" CELLPADDING="3" CELLSPACING="0">
 * <TR BGCOLOR="#CCCCFF" CLASS="TableHeadingColor"><TD>Date</TD><TD>Name</TD><TD>Comment</TD></TR>
 * <TR><TD>2004/02/13</TD><TD>N.Sawa(DFK)</TD><TD>created this class</TD></TR>
 * </TABLE>
 * <BR>
 * @version $Revision: 1.2 $, $Date: 2007/03/07 07:45:22 $
 * @author  $Author: suresh $
 */
public class LocationMaintenance extends Page
{

	// Class variables -----------------------------------------------
	public jp.co.daifuku.bluedog.ui.control.Label lbl_SettingName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_SettingName" , "YKK_LBL_LocationMaintenance");
	public jp.co.daifuku.bluedog.ui.control.LinkButton btn_Help = jp.co.daifuku.bluedog.ui.control.LinkButtonFactory.getInstance("btn_Help" , "Help");
	public jp.co.daifuku.bluedog.ui.control.Message message = jp.co.daifuku.bluedog.ui.control.MessageFactory.getInstance("message" , "OperationMsg");
	public jp.co.daifuku.bluedog.ui.control.Tab tab = jp.co.daifuku.bluedog.ui.control.TabFactory.getInstance("tab" , "YKK_TAB_Maintenance");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_ToMenu = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_ToMenu" , "To_Menu");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_LocationStatus = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_LocationStatus" , "YKK_LBL_LocationStatus");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_BlankLocation = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_BlankLocation" , "YKK_CHK_BlankLocation");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_UsedLocation = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_UsedLocation" , "YKK_CHK_UsedLocation");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_ErroLocation = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_ErroLocation" , "YKK_CHK_ErroLocation");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_WorkLocation = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_WorkLocation" , "YKK_CHK_WorkLocation");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ManageDivision = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ManageDivision" , "YKK_LBL_ManageDivision");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_ItemInManage = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_ItemInManage" , "YKK_RDO_ItemInManageChecked");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_ItemOutOfManage = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_ItemOutOfManage" , "YKK_RDO_ItemOutOfManage");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_LocationView = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_LocationView" , "YKK_LBL_LocationView");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_LocationViewInquiry = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_LocationViewInquiry" , "YKK_BTN_Inquiry_POPUP");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_LocationNo = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_LocationNo" , "YKK_LBL_LocationNo");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Star1 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Star1" , "YKK_LBL_Star");
	public jp.co.daifuku.bluedog.ui.control.FormatTextBox txt_LocationNo = jp.co.daifuku.bluedog.ui.control.FormatTextBoxFactory.getInstance("txt_LocationNo" , "YKK_TXT_LocationNo");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_DealDivision = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_DealDivision" , "YKK_LBL_DealDivision");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Add = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Add" , "YKK_BTN_Add");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Modify = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Modify" , "YKK_BTN_Modify");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Delete = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Delete" , "YKK_BTN_Delete");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_LocationNoLocationStatus = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_LocationNoLocationStatus" , "YKK_LBL_LocationNoLocationStatus");
	public jp.co.daifuku.bluedog.ui.control.FormatTextBox txt_LocationNo_RO = jp.co.daifuku.bluedog.ui.control.FormatTextBoxFactory.getInstance("txt_LocationNo_RO" , "YKK_TXT_LocationNo_RO");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_LocationStatus = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_LocationStatus" , "YKK_TXT_LocationStatus_RO");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_ManageDivision = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_ManageDivision" , "YKK_TXT_ManageDivision_RO");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_TicketNo = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_TicketNo" , "YKK_LBL_TicketNo");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_TicketNo = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_TicketNo" , "YKK_TXT_TicketNo_Enter");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_TicketNoBrowse = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_TicketNoBrowse" , "YKK_BTN_Search_POPUP");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ItemCode = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ItemCode" , "YKK_LBL_ItemNo");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_ItemCode = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_ItemCode" , "YKK_TXT_ItemNo_Enter_RO");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_ItemName = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_ItemName" , "YKK_TXT_ItemName_RO");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ColorCode = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ColorCode" , "YKK_LBL_ColorCode");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_ColorCode = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_ColorCode" , "YKK_TXT_ColorCode_RO");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_InstockCount = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_InstockCount" , "YKK_LBL_InstockCount");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_InstockCount = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_InstockCount" , "YKK_TXT_InstockCount_RO");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_BucketNo = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_BucketNo" , "YKK_LBL_BucketNo");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Star2 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Star2" , "YKK_LBL_Star");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_BucketNo = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_BucketNo" , "YKK_TXT_BucketNo");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_StockinDateTime = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_StockinDateTime" , "YKK_LBL_StockinDateTime");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Date = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Date" , "YKK_LBL_Date");
	public jp.co.daifuku.bluedog.ui.control.DateTextBox txt_StockinDate = jp.co.daifuku.bluedog.ui.control.DateTextBoxFactory.getInstance("txt_StockinDate" , "YKK_TXT_StockinDate");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Time = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Time" , "YKK_LBL_Time");
	public jp.co.daifuku.bluedog.ui.control.TimeTextBox txt_StockinTime = jp.co.daifuku.bluedog.ui.control.TimeTextBoxFactory.getInstance("txt_StockinTime" , "YKK_TXT_StockinTime");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Memo = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Memo" , "YKK_LBL_Memo");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_Memo = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_Memo" , "YKK_TXT_Memo");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Set = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Set" , "YKK_BTN_Set");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Clear = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Clear" , "YKK_BTN_Clear");

}
//end of class
