//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2407
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
// 
//             Powered By： SR3.1(SmartRobot For SmartPersistenceLayer 3.1) 听棠
//             Created By： Administrator
//             Created Time： 2008-1-7 11:31:43
// 
// -------------------------------------------------------------
namespace BusinessEntity
{
    using System;
    using System.Collections;
    using System.Data;
    using PersistenceLayer;
    
    
    /// <summary>该类的摘要说明</summary>
    [Serializable()]
    public class FMLINKEntity : EntityObject
    {
        
        /// <summary>PATERNNO</summary>
        public const string __PATERNNO = "PATERNNO";
        
        /// <summary>MEMO</summary>
        public const string __MEMO = "MEMO";
        
        private System.Decimal m_PATERNNO;
        
        private string m_MEMO;
        
        /// <summary>构造函数</summary>
        public FMLINKEntity()
        {
        }
        
        /// <summary>属性PATERNNO </summary>
        public System.Decimal PATERNNO
        {
            get
            {
                return this.m_PATERNNO;
            }
            set
            {
                this.m_PATERNNO = value;
            }
        }
        
        /// <summary>属性MEMO </summary>
        public string MEMO
        {
            get
            {
                return this.m_MEMO;
            }
            set
            {
                this.m_MEMO = value;
            }
        }
    }
    
    /// FMLINKEntity执行类
    public abstract class FMLINKEntityAction
    {
        
        private FMLINKEntityAction()
        {
        }
        
        public static void Save(FMLINKEntity obj)
        {
            if (obj!=null)
            {
                obj.Save();
            }
        }
        
        /// <summary>根据主键获取一个实体</summary>
        public static FMLINKEntity RetrieveAFMLINKEntity(System.Decimal PATERNNO)
        {
            FMLINKEntity obj=new FMLINKEntity();
            obj.PATERNNO=PATERNNO;
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static EntityContainer RetrieveFMLINKEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(FMLINKEntity));
            return rc.AsEntityContainer();
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static DataTable GetFMLINKEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(FMLINKEntity));
            return rc.AsDataTable();
        }
    }
}
