//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2407
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
// 
//             Powered By： SR3.1(SmartRobot For SmartPersistenceLayer 3.1) 听棠
//             Created By： Administrator
//             Created Time： 2008-1-7 11:31:43
// 
// -------------------------------------------------------------
namespace BusinessEntity
{
    using System;
    using System.Collections;
    using System.Data;
    using PersistenceLayer;
    
    
    /// <summary>该类的摘要说明</summary>
    [Serializable()]
    public class FNAWCCUSTOMEntity : EntityObject
    {
        
        /// <summary>KAISI_SETTEI</summary>
        public const string __KAISI_SETTEI = "KAISI_SETTEI";
        
        /// <summary>GROUPNO_KENSUU</summary>
        public const string __GROUPNO_KENSUU = "GROUPNO_KENSUU";
        
        /// <summary>DEBUGMODE</summary>
        public const string __DEBUGMODE = "DEBUGMODE";
        
        /// <summary>LOTNO_NULL_MODE</summary>
        public const string __LOTNO_NULL_MODE = "LOTNO_NULL_MODE";
        
        /// <summary>MULTIHIKIATE</summary>
        public const string __MULTIHIKIATE = "MULTIHIKIATE";
        
        /// <summary>EMPPB_SOFTZONE</summary>
        public const string __EMPPB_SOFTZONE = "EMPPB_SOFTZONE";
        
        /// <summary>SOKO_YUSEN</summary>
        public const string __SOKO_YUSEN = "SOKO_YUSEN";
        
        /// <summary>FLOOR_KAKUNIN</summary>
        public const string __FLOOR_KAKUNIN = "FLOOR_KAKUNIN";
        
        private string m_KAISI_SETTEI;
        
        private System.Decimal m_GROUPNO_KENSUU;
        
        private string m_DEBUGMODE;
        
        private string m_LOTNO_NULL_MODE;
        
        private string m_MULTIHIKIATE;
        
        private string m_EMPPB_SOFTZONE;
        
        private string m_SOKO_YUSEN;
        
        private string m_FLOOR_KAKUNIN;
        
        /// <summary>构造函数</summary>
        public FNAWCCUSTOMEntity()
        {
        }
        
        /// <summary>属性KAISI_SETTEI </summary>
        public string KAISI_SETTEI
        {
            get
            {
                return this.m_KAISI_SETTEI;
            }
            set
            {
                this.m_KAISI_SETTEI = value;
            }
        }
        
        /// <summary>属性GROUPNO_KENSUU </summary>
        public System.Decimal GROUPNO_KENSUU
        {
            get
            {
                return this.m_GROUPNO_KENSUU;
            }
            set
            {
                this.m_GROUPNO_KENSUU = value;
            }
        }
        
        /// <summary>属性DEBUGMODE </summary>
        public string DEBUGMODE
        {
            get
            {
                return this.m_DEBUGMODE;
            }
            set
            {
                this.m_DEBUGMODE = value;
            }
        }
        
        /// <summary>属性LOTNO_NULL_MODE </summary>
        public string LOTNO_NULL_MODE
        {
            get
            {
                return this.m_LOTNO_NULL_MODE;
            }
            set
            {
                this.m_LOTNO_NULL_MODE = value;
            }
        }
        
        /// <summary>属性MULTIHIKIATE </summary>
        public string MULTIHIKIATE
        {
            get
            {
                return this.m_MULTIHIKIATE;
            }
            set
            {
                this.m_MULTIHIKIATE = value;
            }
        }
        
        /// <summary>属性EMPPB_SOFTZONE </summary>
        public string EMPPB_SOFTZONE
        {
            get
            {
                return this.m_EMPPB_SOFTZONE;
            }
            set
            {
                this.m_EMPPB_SOFTZONE = value;
            }
        }
        
        /// <summary>属性SOKO_YUSEN </summary>
        public string SOKO_YUSEN
        {
            get
            {
                return this.m_SOKO_YUSEN;
            }
            set
            {
                this.m_SOKO_YUSEN = value;
            }
        }
        
        /// <summary>属性FLOOR_KAKUNIN </summary>
        public string FLOOR_KAKUNIN
        {
            get
            {
                return this.m_FLOOR_KAKUNIN;
            }
            set
            {
                this.m_FLOOR_KAKUNIN = value;
            }
        }
    }
    
    /// FNAWCCUSTOMEntity执行类
    public abstract class FNAWCCUSTOMEntityAction
    {
        
        private FNAWCCUSTOMEntityAction()
        {
        }
        
        public static void Save(FNAWCCUSTOMEntity obj)
        {
            if (obj!=null)
            {
                obj.Save();
            }
        }
        
        /// <summary>根据主键获取一个实体</summary>
        public static FNAWCCUSTOMEntity RetrieveAFNAWCCUSTOMEntity()
        {
            FNAWCCUSTOMEntity obj=new FNAWCCUSTOMEntity();
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static EntityContainer RetrieveFNAWCCUSTOMEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(FNAWCCUSTOMEntity));
            return rc.AsEntityContainer();
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static DataTable GetFNAWCCUSTOMEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(FNAWCCUSTOMEntity));
            return rc.AsDataTable();
        }
    }
}
