//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2407
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
// 
//             Powered By： SR3.1(SmartRobot For SmartPersistenceLayer 3.1) 听棠
//             Created By： Administrator
//             Created Time： 2008-1-7 11:31:43
// 
// -------------------------------------------------------------
namespace BusinessEntity
{
    using System;
    using System.Collections;
    using System.Data;
    using PersistenceLayer;
    
    
    /// <summary>该类的摘要说明</summary>
    [Serializable()]
    public class FNHZKEYEntity : EntityObject
    {
        
        /// <summary>SAKUSEIHIJI</summary>
        public const string __SAKUSEIHIJI = "SAKUSEIHIJI";
        
        /// <summary>SCHNO</summary>
        public const string __SCHNO = "SCHNO";
        
        /// <summary>MENTEKBN</summary>
        public const string __MENTEKBN = "MENTEKBN";
        
        /// <summary>ZAIKEY</summary>
        public const string __ZAIKEY = "ZAIKEY";
        
        /// <summary>ZKNAME</summary>
        public const string __ZKNAME = "ZKNAME";
        
        /// <summary>ZKKBN</summary>
        public const string __ZKKBN = "ZKKBN";
        
        /// <summary>SEKISAISU</summary>
        public const string __SEKISAISU = "SEKISAISU";
        
        /// <summary>YSHIKIRI</summary>
        public const string __YSHIKIRI = "YSHIKIRI";
        
        /// <summary>YSHUBETSU</summary>
        public const string __YSHUBETSU = "YSHUBETSU";
        
        /// <summary>SOTOSU</summary>
        public const string __SOTOSU = "SOTOSU";
        
        /// <summary>UCHISU</summary>
        public const string __UCHISU = "UCHISU";
        
        /// <summary>MENTEHIJI</summary>
        public const string __MENTEHIJI = "MENTEHIJI";
        
        /// <summary>JOGENSUJ</summary>
        public const string __JOGENSUJ = "JOGENSUJ";
        
        /// <summary>KAGENSUJ</summary>
        public const string __KAGENSUJ = "KAGENSUJ";
        
        /// <summary>TORIFLG</summary>
        public const string __TORIFLG = "TORIFLG";
        
        /// <summary>ERRCODE</summary>
        public const string __ERRCODE = "ERRCODE";
        
        /// <summary>SOFTZONE</summary>
        public const string __SOFTZONE = "SOFTZONE";
        
        private string m_SAKUSEIHIJI;
        
        private string m_SCHNO;
        
        private string m_MENTEKBN;
        
        private string m_ZAIKEY;
        
        private string m_ZKNAME;
        
        private string m_ZKKBN;
        
        private System.Decimal m_SEKISAISU;
        
        private System.Decimal m_YSHIKIRI;
        
        private string m_YSHUBETSU;
        
        private System.Decimal m_SOTOSU;
        
        private System.Decimal m_UCHISU;
        
        private string m_MENTEHIJI;
        
        private System.Decimal m_JOGENSUJ;
        
        private System.Decimal m_KAGENSUJ;
        
        private string m_TORIFLG;
        
        private string m_ERRCODE;
        
        private string m_SOFTZONE;
        
        /// <summary>构造函数</summary>
        public FNHZKEYEntity()
        {
        }
        
        /// <summary>属性SAKUSEIHIJI </summary>
        public string SAKUSEIHIJI
        {
            get
            {
                return this.m_SAKUSEIHIJI;
            }
            set
            {
                this.m_SAKUSEIHIJI = value;
            }
        }
        
        /// <summary>属性SCHNO </summary>
        public string SCHNO
        {
            get
            {
                return this.m_SCHNO;
            }
            set
            {
                this.m_SCHNO = value;
            }
        }
        
        /// <summary>属性MENTEKBN </summary>
        public string MENTEKBN
        {
            get
            {
                return this.m_MENTEKBN;
            }
            set
            {
                this.m_MENTEKBN = value;
            }
        }
        
        /// <summary>属性ZAIKEY </summary>
        public string ZAIKEY
        {
            get
            {
                return this.m_ZAIKEY;
            }
            set
            {
                this.m_ZAIKEY = value;
            }
        }
        
        /// <summary>属性ZKNAME </summary>
        public string ZKNAME
        {
            get
            {
                return this.m_ZKNAME;
            }
            set
            {
                this.m_ZKNAME = value;
            }
        }
        
        /// <summary>属性ZKKBN </summary>
        public string ZKKBN
        {
            get
            {
                return this.m_ZKKBN;
            }
            set
            {
                this.m_ZKKBN = value;
            }
        }
        
        /// <summary>属性SEKISAISU </summary>
        public System.Decimal SEKISAISU
        {
            get
            {
                return this.m_SEKISAISU;
            }
            set
            {
                this.m_SEKISAISU = value;
            }
        }
        
        /// <summary>属性YSHIKIRI </summary>
        public System.Decimal YSHIKIRI
        {
            get
            {
                return this.m_YSHIKIRI;
            }
            set
            {
                this.m_YSHIKIRI = value;
            }
        }
        
        /// <summary>属性YSHUBETSU </summary>
        public string YSHUBETSU
        {
            get
            {
                return this.m_YSHUBETSU;
            }
            set
            {
                this.m_YSHUBETSU = value;
            }
        }
        
        /// <summary>属性SOTOSU </summary>
        public System.Decimal SOTOSU
        {
            get
            {
                return this.m_SOTOSU;
            }
            set
            {
                this.m_SOTOSU = value;
            }
        }
        
        /// <summary>属性UCHISU </summary>
        public System.Decimal UCHISU
        {
            get
            {
                return this.m_UCHISU;
            }
            set
            {
                this.m_UCHISU = value;
            }
        }
        
        /// <summary>属性MENTEHIJI </summary>
        public string MENTEHIJI
        {
            get
            {
                return this.m_MENTEHIJI;
            }
            set
            {
                this.m_MENTEHIJI = value;
            }
        }
        
        /// <summary>属性JOGENSUJ </summary>
        public System.Decimal JOGENSUJ
        {
            get
            {
                return this.m_JOGENSUJ;
            }
            set
            {
                this.m_JOGENSUJ = value;
            }
        }
        
        /// <summary>属性KAGENSUJ </summary>
        public System.Decimal KAGENSUJ
        {
            get
            {
                return this.m_KAGENSUJ;
            }
            set
            {
                this.m_KAGENSUJ = value;
            }
        }
        
        /// <summary>属性TORIFLG </summary>
        public string TORIFLG
        {
            get
            {
                return this.m_TORIFLG;
            }
            set
            {
                this.m_TORIFLG = value;
            }
        }
        
        /// <summary>属性ERRCODE </summary>
        public string ERRCODE
        {
            get
            {
                return this.m_ERRCODE;
            }
            set
            {
                this.m_ERRCODE = value;
            }
        }
        
        /// <summary>属性SOFTZONE </summary>
        public string SOFTZONE
        {
            get
            {
                return this.m_SOFTZONE;
            }
            set
            {
                this.m_SOFTZONE = value;
            }
        }
    }
    
    /// FNHZKEYEntity执行类
    public abstract class FNHZKEYEntityAction
    {
        
        private FNHZKEYEntityAction()
        {
        }
        
        public static void Save(FNHZKEYEntity obj)
        {
            if (obj!=null)
            {
                obj.Save();
            }
        }
        
        /// <summary>根据主键获取一个实体</summary>
        public static FNHZKEYEntity RetrieveAFNHZKEYEntity()
        {
            FNHZKEYEntity obj=new FNHZKEYEntity();
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static EntityContainer RetrieveFNHZKEYEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(FNHZKEYEntity));
            return rc.AsEntityContainer();
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static DataTable GetFNHZKEYEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(FNHZKEYEntity));
            return rc.AsDataTable();
        }
    }
}
