//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2407
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
// 
//             Powered By： SR3.1(SmartRobot For SmartPersistenceLayer 3.1) 听棠
//             Created By： Administrator
//             Created Time： 2008-1-7 11:31:43
// 
// -------------------------------------------------------------
namespace BusinessEntity
{
    using System;
    using System.Collections;
    using System.Data;
    using PersistenceLayer;
    
    
    /// <summary>该类的摘要说明</summary>
    [Serializable()]
    public class FNKANRIEntity : EntityObject
    {
        
        /// <summary>SCHNO</summary>
        public const string __SCHNO = "SCHNO";
        
        /// <summary>YUSENKBN</summary>
        public const string __YUSENKBN = "YUSENKBN";
        
        /// <summary>SYUKEY</summary>
        public const string __SYUKEY = "SYUKEY";
        
        /// <summary>SAGYONOFROM</summary>
        public const string __SAGYONOFROM = "SAGYONOFROM";
        
        /// <summary>SAGYONOTO</summary>
        public const string __SAGYONOTO = "SAGYONOTO";
        
        /// <summary>SYUSTNO</summary>
        public const string __SYUSTNO = "SYUSTNO";
        
        /// <summary>KAIFLG</summary>
        public const string __KAIFLG = "KAIFLG";
        
        /// <summary>AILENO</summary>
        public const string __AILENO = "AILENO";
        
        private string m_SCHNO;
        
        private string m_YUSENKBN;
        
        private string m_SYUKEY;
        
        private string m_SAGYONOFROM;
        
        private string m_SAGYONOTO;
        
        private string m_SYUSTNO;
        
        private string m_KAIFLG;
        
        private System.Decimal m_AILENO;
        
        /// <summary>构造函数</summary>
        public FNKANRIEntity()
        {
        }
        
        /// <summary>属性SCHNO </summary>
        public string SCHNO
        {
            get
            {
                return this.m_SCHNO;
            }
            set
            {
                this.m_SCHNO = value;
            }
        }
        
        /// <summary>属性YUSENKBN </summary>
        public string YUSENKBN
        {
            get
            {
                return this.m_YUSENKBN;
            }
            set
            {
                this.m_YUSENKBN = value;
            }
        }
        
        /// <summary>属性SYUKEY </summary>
        public string SYUKEY
        {
            get
            {
                return this.m_SYUKEY;
            }
            set
            {
                this.m_SYUKEY = value;
            }
        }
        
        /// <summary>属性SAGYONOFROM </summary>
        public string SAGYONOFROM
        {
            get
            {
                return this.m_SAGYONOFROM;
            }
            set
            {
                this.m_SAGYONOFROM = value;
            }
        }
        
        /// <summary>属性SAGYONOTO </summary>
        public string SAGYONOTO
        {
            get
            {
                return this.m_SAGYONOTO;
            }
            set
            {
                this.m_SAGYONOTO = value;
            }
        }
        
        /// <summary>属性SYUSTNO </summary>
        public string SYUSTNO
        {
            get
            {
                return this.m_SYUSTNO;
            }
            set
            {
                this.m_SYUSTNO = value;
            }
        }
        
        /// <summary>属性KAIFLG </summary>
        public string KAIFLG
        {
            get
            {
                return this.m_KAIFLG;
            }
            set
            {
                this.m_KAIFLG = value;
            }
        }
        
        /// <summary>属性AILENO </summary>
        public System.Decimal AILENO
        {
            get
            {
                return this.m_AILENO;
            }
            set
            {
                this.m_AILENO = value;
            }
        }
    }
    
    /// FNKANRIEntity执行类
    public abstract class FNKANRIEntityAction
    {
        
        private FNKANRIEntityAction()
        {
        }
        
        public static void Save(FNKANRIEntity obj)
        {
            if (obj!=null)
            {
                obj.Save();
            }
        }
        
        /// <summary>根据主键获取一个实体</summary>
        public static FNKANRIEntity RetrieveAFNKANRIEntity()
        {
            FNKANRIEntity obj=new FNKANRIEntity();
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static EntityContainer RetrieveFNKANRIEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(FNKANRIEntity));
            return rc.AsEntityContainer();
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static DataTable GetFNKANRIEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(FNKANRIEntity));
            return rc.AsDataTable();
        }
    }
}
