//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2407
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
// 
//             Powered By： SR3.1(SmartRobot For SmartPersistenceLayer 3.1) 听棠
//             Created By： Administrator
//             Created Time： 2008-1-7 11:31:43
// 
// -------------------------------------------------------------
namespace BusinessEntity
{
    using System;
    using System.Collections;
    using System.Data;
    using PersistenceLayer;
    
    
    /// <summary>该类的摘要说明</summary>
    [Serializable()]
    public class FNSAINYUEntity : EntityObject
    {
        
        /// <summary>STNO</summary>
        public const string __STNO = "STNO";
        
        /// <summary>SAGYONO</summary>
        public const string __SAGYONO = "SAGYONO";
        
        /// <summary>SYSTEMID</summary>
        public const string __SYSTEMID = "SYSTEMID";
        
        /// <summary>SYORIFLG</summary>
        public const string __SYORIFLG = "SYORIFLG";
        
        private string m_STNO;
        
        private string m_SAGYONO;
        
        private string m_SYSTEMID;
        
        private string m_SYORIFLG;
        
        /// <summary>构造函数</summary>
        public FNSAINYUEntity()
        {
        }
        
        /// <summary>属性STNO </summary>
        public string STNO
        {
            get
            {
                return this.m_STNO;
            }
            set
            {
                this.m_STNO = value;
            }
        }
        
        /// <summary>属性SAGYONO </summary>
        public string SAGYONO
        {
            get
            {
                return this.m_SAGYONO;
            }
            set
            {
                this.m_SAGYONO = value;
            }
        }
        
        /// <summary>属性SYSTEMID </summary>
        public string SYSTEMID
        {
            get
            {
                return this.m_SYSTEMID;
            }
            set
            {
                this.m_SYSTEMID = value;
            }
        }
        
        /// <summary>属性SYORIFLG </summary>
        public string SYORIFLG
        {
            get
            {
                return this.m_SYORIFLG;
            }
            set
            {
                this.m_SYORIFLG = value;
            }
        }
    }
    
    /// FNSAINYUEntity执行类
    public abstract class FNSAINYUEntityAction
    {
        
        private FNSAINYUEntityAction()
        {
        }
        
        public static void Save(FNSAINYUEntity obj)
        {
            if (obj!=null)
            {
                obj.Save();
            }
        }
        
        /// <summary>根据主键获取一个实体</summary>
        public static FNSAINYUEntity RetrieveAFNSAINYUEntity()
        {
            FNSAINYUEntity obj=new FNSAINYUEntity();
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static EntityContainer RetrieveFNSAINYUEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(FNSAINYUEntity));
            return rc.AsEntityContainer();
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static DataTable GetFNSAINYUEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(FNSAINYUEntity));
            return rc.AsDataTable();
        }
    }
}
