//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2407
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
// 
//             Powered By： SR3.1(SmartRobot For SmartPersistenceLayer 3.1) 听棠
//             Created By： Administrator
//             Created Time： 2008-1-7 11:31:43
// 
// -------------------------------------------------------------
namespace BusinessEntity
{
    using System;
    using System.Collections;
    using System.Data;
    using PersistenceLayer;
    
    
    /// <summary>该类的摘要说明</summary>
    [Serializable()]
    public class FNSIJIEntity : EntityObject
    {
        
        /// <summary>HANSOKEY</summary>
        public const string __HANSOKEY = "HANSOKEY";
        
        /// <summary>MCKEY</summary>
        public const string __MCKEY = "MCKEY";
        
        /// <summary>TICKET_NO</summary>
        public const string __TICKET_NO = "TICKET_NO";
        
        /// <summary>ZAIKEY</summary>
        public const string __ZAIKEY = "ZAIKEY";
        
        /// <summary>COLOR_CODE</summary>
        public const string __COLOR_CODE = "COLOR_CODE";
        
        /// <summary>NYUSYUSU</summary>
        public const string __NYUSYUSU = "NYUSYUSU";
        
        /// <summary>RETRIEVAL_PLAN_KEY</summary>
        public const string __RETRIEVAL_PLAN_KEY = "RETRIEVAL_PLAN_KEY";
        
        /// <summary>LABEL_KEY</summary>
        public const string __LABEL_KEY = "LABEL_KEY";
        
        /// <summary>SECTION</summary>
        public const string __SECTION = "SECTION";
        
        /// <summary>LINE</summary>
        public const string __LINE = "LINE";
        
        /// <summary>LINE_TYPE</summary>
        public const string __LINE_TYPE = "LINE_TYPE";
        
        /// <summary>CUSTOMER_CODE</summary>
        public const string __CUSTOMER_CODE = "CUSTOMER_CODE";
        
        /// <summary>RETRIEVAL_STATION</summary>
        public const string __RETRIEVAL_STATION = "RETRIEVAL_STATION";
        
        /// <summary>DEPOT_CODE</summary>
        public const string __DEPOT_CODE = "DEPOT_CODE";
        
        /// <summary>MANAGE_ITEM_FLAG</summary>
        public const string __MANAGE_ITEM_FLAG = "MANAGE_ITEM_FLAG";
        
        private string m_HANSOKEY;
        
        private string m_MCKEY;
        
        private string m_TICKET_NO;
        
        private string m_ZAIKEY;
        
        private string m_COLOR_CODE;
        
        private System.Decimal m_NYUSYUSU;
        
        private string m_RETRIEVAL_PLAN_KEY;
        
        private string m_LABEL_KEY;
        
        private string m_SECTION;
        
        private string m_LINE;
        
        private string m_LINE_TYPE;
        
        private string m_CUSTOMER_CODE;
        
        private string m_RETRIEVAL_STATION;
        
        private string m_DEPOT_CODE;
        
        private string m_MANAGE_ITEM_FLAG;
        
        /// <summary>构造函数</summary>
        public FNSIJIEntity()
        {
        }
        
        /// <summary>属性HANSOKEY </summary>
        public string HANSOKEY
        {
            get
            {
                return this.m_HANSOKEY;
            }
            set
            {
                this.m_HANSOKEY = value;
            }
        }
        
        /// <summary>属性MCKEY </summary>
        public string MCKEY
        {
            get
            {
                return this.m_MCKEY;
            }
            set
            {
                this.m_MCKEY = value;
            }
        }
        
        /// <summary>属性TICKET_NO </summary>
        public string TICKET_NO
        {
            get
            {
                return this.m_TICKET_NO;
            }
            set
            {
                this.m_TICKET_NO = value;
            }
        }
        
        /// <summary>属性ZAIKEY </summary>
        public string ZAIKEY
        {
            get
            {
                return this.m_ZAIKEY;
            }
            set
            {
                this.m_ZAIKEY = value;
            }
        }
        
        /// <summary>属性COLOR_CODE </summary>
        public string COLOR_CODE
        {
            get
            {
                return this.m_COLOR_CODE;
            }
            set
            {
                this.m_COLOR_CODE = value;
            }
        }
        
        /// <summary>属性NYUSYUSU </summary>
        public System.Decimal NYUSYUSU
        {
            get
            {
                return this.m_NYUSYUSU;
            }
            set
            {
                this.m_NYUSYUSU = value;
            }
        }
        
        /// <summary>属性RETRIEVAL_PLAN_KEY </summary>
        public string RETRIEVAL_PLAN_KEY
        {
            get
            {
                return this.m_RETRIEVAL_PLAN_KEY;
            }
            set
            {
                this.m_RETRIEVAL_PLAN_KEY = value;
            }
        }
        
        /// <summary>属性LABEL_KEY </summary>
        public string LABEL_KEY
        {
            get
            {
                return this.m_LABEL_KEY;
            }
            set
            {
                this.m_LABEL_KEY = value;
            }
        }
        
        /// <summary>属性SECTION </summary>
        public string SECTION
        {
            get
            {
                return this.m_SECTION;
            }
            set
            {
                this.m_SECTION = value;
            }
        }
        
        /// <summary>属性LINE </summary>
        public string LINE
        {
            get
            {
                return this.m_LINE;
            }
            set
            {
                this.m_LINE = value;
            }
        }
        
        /// <summary>属性LINE_TYPE </summary>
        public string LINE_TYPE
        {
            get
            {
                return this.m_LINE_TYPE;
            }
            set
            {
                this.m_LINE_TYPE = value;
            }
        }
        
        /// <summary>属性CUSTOMER_CODE </summary>
        public string CUSTOMER_CODE
        {
            get
            {
                return this.m_CUSTOMER_CODE;
            }
            set
            {
                this.m_CUSTOMER_CODE = value;
            }
        }
        
        /// <summary>属性RETRIEVAL_STATION </summary>
        public string RETRIEVAL_STATION
        {
            get
            {
                return this.m_RETRIEVAL_STATION;
            }
            set
            {
                this.m_RETRIEVAL_STATION = value;
            }
        }
        
        /// <summary>属性DEPOT_CODE </summary>
        public string DEPOT_CODE
        {
            get
            {
                return this.m_DEPOT_CODE;
            }
            set
            {
                this.m_DEPOT_CODE = value;
            }
        }
        
        /// <summary>属性MANAGE_ITEM_FLAG </summary>
        public string MANAGE_ITEM_FLAG
        {
            get
            {
                return this.m_MANAGE_ITEM_FLAG;
            }
            set
            {
                this.m_MANAGE_ITEM_FLAG = value;
            }
        }
    }
    
    /// FNSIJIEntity执行类
    public abstract class FNSIJIEntityAction
    {
        
        private FNSIJIEntityAction()
        {
        }
        
        public static void Save(FNSIJIEntity obj)
        {
            if (obj!=null)
            {
                obj.Save();
            }
        }
        
        /// <summary>根据主键获取一个实体</summary>
        public static FNSIJIEntity RetrieveAFNSIJIEntity()
        {
            FNSIJIEntity obj=new FNSIJIEntity();
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static EntityContainer RetrieveFNSIJIEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(FNSIJIEntity));
            return rc.AsEntityContainer();
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static DataTable GetFNSIJIEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(FNSIJIEntity));
            return rc.AsDataTable();
        }
    }
}
