//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2407
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
// 
//             Powered By： SR3.1(SmartRobot For SmartPersistenceLayer 3.1) 听棠
//             Created By： Administrator
//             Created Time： 2008-1-7 11:31:43
// 
// -------------------------------------------------------------
namespace BusinessEntity
{
    using System;
    using System.Collections;
    using System.Data;
    using PersistenceLayer;
    
    
    /// <summary>该类的摘要说明</summary>
    [Serializable()]
    public class FNSOFTZONEYUSENEntity : EntityObject
    {
        
        /// <summary>SOFTZONE</summary>
        public const string __SOFTZONE = "SOFTZONE";
        
        /// <summary>YUSENSOFTZONE</summary>
        public const string __YUSENSOFTZONE = "YUSENSOFTZONE";
        
        /// <summary>SOFTZONEORDER</summary>
        public const string __SOFTZONEORDER = "SOFTZONEORDER";
        
        /// <summary>AKIKENKBN</summary>
        public const string __AKIKENKBN = "AKIKENKBN";
        
        private string m_SOFTZONE;
        
        private string m_YUSENSOFTZONE;
        
        private System.Decimal m_SOFTZONEORDER;
        
        private string m_AKIKENKBN;
        
        /// <summary>构造函数</summary>
        public FNSOFTZONEYUSENEntity()
        {
        }
        
        /// <summary>属性SOFTZONE </summary>
        public string SOFTZONE
        {
            get
            {
                return this.m_SOFTZONE;
            }
            set
            {
                this.m_SOFTZONE = value;
            }
        }
        
        /// <summary>属性YUSENSOFTZONE </summary>
        public string YUSENSOFTZONE
        {
            get
            {
                return this.m_YUSENSOFTZONE;
            }
            set
            {
                this.m_YUSENSOFTZONE = value;
            }
        }
        
        /// <summary>属性SOFTZONEORDER </summary>
        public System.Decimal SOFTZONEORDER
        {
            get
            {
                return this.m_SOFTZONEORDER;
            }
            set
            {
                this.m_SOFTZONEORDER = value;
            }
        }
        
        /// <summary>属性AKIKENKBN </summary>
        public string AKIKENKBN
        {
            get
            {
                return this.m_AKIKENKBN;
            }
            set
            {
                this.m_AKIKENKBN = value;
            }
        }
    }
    
    /// FNSOFTZONEYUSENEntity执行类
    public abstract class FNSOFTZONEYUSENEntityAction
    {
        
        private FNSOFTZONEYUSENEntityAction()
        {
        }
        
        public static void Save(FNSOFTZONEYUSENEntity obj)
        {
            if (obj!=null)
            {
                obj.Save();
            }
        }
        
        /// <summary>根据主键获取一个实体</summary>
        public static FNSOFTZONEYUSENEntity RetrieveAFNSOFTZONEYUSENEntity()
        {
            FNSOFTZONEYUSENEntity obj=new FNSOFTZONEYUSENEntity();
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static EntityContainer RetrieveFNSOFTZONEYUSENEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(FNSOFTZONEYUSENEntity));
            return rc.AsEntityContainer();
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static DataTable GetFNSOFTZONEYUSENEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(FNSOFTZONEYUSENEntity));
            return rc.AsDataTable();
        }
    }
}
