//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2407
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
// 
//             Powered By： SR3.1(SmartRobot For SmartPersistenceLayer 3.1) 听棠
//             Created By： Administrator
//             Created Time： 2008-1-7 11:31:43
// 
// -------------------------------------------------------------
namespace BusinessEntity
{
    using System;
    using System.Collections;
    using System.Data;
    using PersistenceLayer;
    
    
    /// <summary>该类的摘要说明</summary>
    [Serializable()]
    public class LOGINUSEREntity : EntityObject
    {
        
        /// <summary>USERID</summary>
        public const string __USERID = "USERID";
        
        /// <summary>PASSWORD</summary>
        public const string __PASSWORD = "PASSWORD";
        
        /// <summary>PWDEXPIRES</summary>
        public const string __PWDEXPIRES = "PWDEXPIRES";
        
        /// <summary>PWDCHANGEINTERVAL</summary>
        public const string __PWDCHANGEINTERVAL = "PWDCHANGEINTERVAL";
        
        /// <summary>ROLEID</summary>
        public const string __ROLEID = "ROLEID";
        
        /// <summary>LASTACCESSDATE</summary>
        public const string __LASTACCESSDATE = "LASTACCESSDATE";
        
        /// <summary>SAMEUSERLOGINMAX</summary>
        public const string __SAMEUSERLOGINMAX = "SAMEUSERLOGINMAX";
        
        /// <summary>FAILEDLOGINATTEMPTS</summary>
        public const string __FAILEDLOGINATTEMPTS = "FAILEDLOGINATTEMPTS";
        
        /// <summary>FAILEDCOUNT</summary>
        public const string __FAILEDCOUNT = "FAILEDCOUNT";
        
        /// <summary>FAILEDSTARTDATE</summary>
        public const string __FAILEDSTARTDATE = "FAILEDSTARTDATE";
        
        /// <summary>UPDATEDATE</summary>
        public const string __UPDATEDATE = "UPDATEDATE";
        
        private string m_USERID;
        
        private string m_PASSWORD;
        
        private System.DateTime m_PWDEXPIRES = DateTime.MinValue;
        
        private System.Decimal m_PWDCHANGEINTERVAL;
        
        private string m_ROLEID;
        
        private System.DateTime m_LASTACCESSDATE = DateTime.MinValue;
        
        private System.Decimal m_SAMEUSERLOGINMAX;
        
        private System.Decimal m_FAILEDLOGINATTEMPTS;
        
        private System.Decimal m_FAILEDCOUNT;
        
        private System.DateTime m_FAILEDSTARTDATE = DateTime.MinValue;
        
        private System.DateTime m_UPDATEDATE = DateTime.MinValue;
        
        /// <summary>构造函数</summary>
        public LOGINUSEREntity()
        {
        }
        
        /// <summary>属性USERID </summary>
        public string USERID
        {
            get
            {
                return this.m_USERID;
            }
            set
            {
                this.m_USERID = value;
            }
        }
        
        /// <summary>属性PASSWORD </summary>
        public string PASSWORD
        {
            get
            {
                return this.m_PASSWORD;
            }
            set
            {
                this.m_PASSWORD = value;
            }
        }
        
        /// <summary>属性PWDEXPIRES </summary>
        public System.DateTime PWDEXPIRES
        {
            get
            {
                return this.m_PWDEXPIRES;
            }
            set
            {
                this.m_PWDEXPIRES = value;
            }
        }
        
        /// <summary>属性PWDCHANGEINTERVAL </summary>
        public System.Decimal PWDCHANGEINTERVAL
        {
            get
            {
                return this.m_PWDCHANGEINTERVAL;
            }
            set
            {
                this.m_PWDCHANGEINTERVAL = value;
            }
        }
        
        /// <summary>属性ROLEID </summary>
        public string ROLEID
        {
            get
            {
                return this.m_ROLEID;
            }
            set
            {
                this.m_ROLEID = value;
            }
        }
        
        /// <summary>属性LASTACCESSDATE </summary>
        public System.DateTime LASTACCESSDATE
        {
            get
            {
                return this.m_LASTACCESSDATE;
            }
            set
            {
                this.m_LASTACCESSDATE = value;
            }
        }
        
        /// <summary>属性SAMEUSERLOGINMAX </summary>
        public System.Decimal SAMEUSERLOGINMAX
        {
            get
            {
                return this.m_SAMEUSERLOGINMAX;
            }
            set
            {
                this.m_SAMEUSERLOGINMAX = value;
            }
        }
        
        /// <summary>属性FAILEDLOGINATTEMPTS </summary>
        public System.Decimal FAILEDLOGINATTEMPTS
        {
            get
            {
                return this.m_FAILEDLOGINATTEMPTS;
            }
            set
            {
                this.m_FAILEDLOGINATTEMPTS = value;
            }
        }
        
        /// <summary>属性FAILEDCOUNT </summary>
        public System.Decimal FAILEDCOUNT
        {
            get
            {
                return this.m_FAILEDCOUNT;
            }
            set
            {
                this.m_FAILEDCOUNT = value;
            }
        }
        
        /// <summary>属性FAILEDSTARTDATE </summary>
        public System.DateTime FAILEDSTARTDATE
        {
            get
            {
                return this.m_FAILEDSTARTDATE;
            }
            set
            {
                this.m_FAILEDSTARTDATE = value;
            }
        }
        
        /// <summary>属性UPDATEDATE </summary>
        public System.DateTime UPDATEDATE
        {
            get
            {
                return this.m_UPDATEDATE;
            }
            set
            {
                this.m_UPDATEDATE = value;
            }
        }
    }
    
    /// LOGINUSEREntity执行类
    public abstract class LOGINUSEREntityAction
    {
        
        private LOGINUSEREntityAction()
        {
        }
        
        public static void Save(LOGINUSEREntity obj)
        {
            if (obj!=null)
            {
                obj.Save();
            }
        }
        
        /// <summary>根据主键获取一个实体</summary>
        public static LOGINUSEREntity RetrieveALOGINUSEREntity(string USERID)
        {
            LOGINUSEREntity obj=new LOGINUSEREntity();
            obj.USERID=USERID;
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static EntityContainer RetrieveLOGINUSEREntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(LOGINUSEREntity));
            return rc.AsEntityContainer();
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static DataTable GetLOGINUSEREntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(LOGINUSEREntity));
            return rc.AsDataTable();
        }
    }
}
