//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2407
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
// 
//             Powered By： SR3.1(SmartRobot For SmartPersistenceLayer 3.1) 听棠
//             Created By： Administrator
//             Created Time： 2008-1-7 11:31:43
// 
// -------------------------------------------------------------
namespace BusinessEntity
{
    using System;
    using System.Collections;
    using System.Data;
    using PersistenceLayer;
    
    
    /// <summary>该类的摘要说明</summary>
    [Serializable()]
    public class TERMINALEntity : EntityObject
    {
        
        /// <summary>TERMINALNUMBER</summary>
        public const string __TERMINALNUMBER = "TERMINALNUMBER";
        
        /// <summary>TERMINALNAME</summary>
        public const string __TERMINALNAME = "TERMINALNAME";
        
        /// <summary>IPADDRESS</summary>
        public const string __IPADDRESS = "IPADDRESS";
        
        /// <summary>ROLEID</summary>
        public const string __ROLEID = "ROLEID";
        
        /// <summary>PRINTER_NO</summary>
        public const string __PRINTER_NO = "PRINTER_NO";
        
        /// <summary>UPDATEDATE</summary>
        public const string __UPDATEDATE = "UPDATEDATE";
        
        /// <summary>PROC</summary>
        public const string __PROC = "PROC";
        
        /// <summary>STNO</summary>
        public const string __STNO = "STNO";

        public const string __FIXED_WEIGHT = "FIXED_WEIGHT";    
        
        private string m_TERMINALNUMBER;
        
        private string m_TERMINALNAME;
        
        private string m_IPADDRESS;
        
        private string m_ROLEID;
        
        private System.Decimal m_PRINTER_NO;
        
        private System.DateTime m_UPDATEDATE = DateTime.MinValue;
        
        private string m_PROC;
        
        private string m_STNO;

        private System.Decimal m_FIXED_WEIGHT;
        
        /// <summary>构造函数</summary>
        public TERMINALEntity()
        {
        }
        
        /// <summary>属性TERMINALNUMBER </summary>
        public string TERMINALNUMBER
        {
            get
            {
                return this.m_TERMINALNUMBER;
            }
            set
            {
                this.m_TERMINALNUMBER = value;
            }
        }
        
        /// <summary>属性TERMINALNAME </summary>
        public string TERMINALNAME
        {
            get
            {
                return this.m_TERMINALNAME;
            }
            set
            {
                this.m_TERMINALNAME = value;
            }
        }
        
        /// <summary>属性IPADDRESS </summary>
        public string IPADDRESS
        {
            get
            {
                return this.m_IPADDRESS;
            }
            set
            {
                this.m_IPADDRESS = value;
            }
        }
        
        /// <summary>属性ROLEID </summary>
        public string ROLEID
        {
            get
            {
                return this.m_ROLEID;
            }
            set
            {
                this.m_ROLEID = value;
            }
        }
        
        /// <summary>属性PRINTER_NO </summary>
        public System.Decimal PRINTER_NO
        {
            get
            {
                return this.m_PRINTER_NO;
            }
            set
            {
                this.m_PRINTER_NO = value;
            }
        }
        
        /// <summary>属性UPDATEDATE </summary>
        public System.DateTime UPDATEDATE
        {
            get
            {
                return this.m_UPDATEDATE;
            }
            set
            {
                this.m_UPDATEDATE = value;
            }
        }
        
        /// <summary>属性PROC </summary>
        public string PROC
        {
            get
            {
                return this.m_PROC;
            }
            set
            {
                this.m_PROC = value;
            }
        }
        
        /// <summary>属性STNO </summary>
        public string STNO
        {
            get
            {
                return this.m_STNO;
            }
            set
            {
                this.m_STNO = value;
            }
        }

        /// <summary>属性FIXED_WEIGHT </summary>
        public System.Decimal FIXED_WEIGHT
        {
            get
            {
                return this.m_FIXED_WEIGHT;
            }
            set
            {
                this.m_FIXED_WEIGHT = value;
            }
        }  

        
    }
    
    /// TERMINALEntity执行类
    public abstract class TERMINALEntityAction
    {
        
        private TERMINALEntityAction()
        {
        }
        
        public static void Save(TERMINALEntity obj)
        {
            if (obj!=null)
            {
                obj.Save();
            }
        }
        
        /// <summary>根据主键获取一个实体</summary>
        public static TERMINALEntity RetrieveATERMINALEntity(string TERMINALNUMBER)
        {
            TERMINALEntity obj=new TERMINALEntity();
            obj.TERMINALNUMBER=TERMINALNUMBER;
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static EntityContainer RetrieveTERMINALEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(TERMINALEntity));
            return rc.AsEntityContainer();
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static DataTable GetTERMINALEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(TERMINALEntity));
            return rc.AsDataTable();
        }
    }
}
