// $Id: skelten.java,v 1.2 2007/03/07 07:45:22 suresh Exp $

/*
 * Copyright 2000-2001 DAIFUKU Co.,Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of DAIFUKU Co.,Ltd.
 * Use is subject to license terms.
 */
package jp.co.daifuku.wms.YkkGMAX.Stockout;
import jp.co.daifuku.bluedog.ui.control.Page;

/**
 * This class can not be changed and it is generated by ScreenGenerator.
 * 
 * <BR>
 * <TABLE BORDER="1" CELLPADDING="3" CELLSPACING="0">
 * <TR BGCOLOR="#CCCCFF" CLASS="TableHeadingColor"><TD>Date</TD><TD>Name</TD><TD>Comment</TD></TR>
 * <TR><TD>2004/02/13</TD><TD>N.Sawa(DFK)</TD><TD>created this class</TD></TR>
 * </TABLE>
 * <BR>
 * @version $Revision: 1.2 $, $Date: 2007/03/07 07:45:22 $
 * @author  $Author: suresh $
 */
public class ExceptionStockout extends Page
{

	// Class variables -----------------------------------------------

	/**
	 * ControlID	lbl_SettingName
	 * TemplateKey	YKK_LBL-ExceptionStockout
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_SettingName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_SettingName" , "YKK_LBL-ExceptionStockout");

	/**
	 * ControlID	btn_Help
	 * TemplateKey	Help
	 * ControlType	LinkButton
	 */
	public jp.co.daifuku.bluedog.ui.control.LinkButton btn_Help = jp.co.daifuku.bluedog.ui.control.LinkButtonFactory.getInstance("btn_Help" , "Help");

	/**
	 * ControlID	message
	 * TemplateKey	OperationMsg
	 * ControlType	Message
	 */
	public jp.co.daifuku.bluedog.ui.control.Message message = jp.co.daifuku.bluedog.ui.control.MessageFactory.getInstance("message" , "OperationMsg");

	/**
	 * ControlID	btn_ToMenu
	 * TemplateKey	To_Menu
	 * ControlType	SubmitButton
	 */
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_ToMenu = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_ToMenu" , "To_Menu");

	/**
	 * ControlID	lbl_StockoutCondition
	 * TemplateKey	YKK_LBL_StockoutCondition
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_StockoutCondition = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_StockoutCondition" , "YKK_LBL_StockoutCondition");

	/**
	 * ControlID	rdo_OverTimeStorageStockout
	 * TemplateKey	YKK_RDO_OvertimeStorageStockout
	 * ControlType	RadioButton
	 */
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_OverTimeStorageStockout = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_OverTimeStorageStockout" , "YKK_RDO_OvertimeStorageStockout");

	/**
	 * ControlID	lbl_StockinDateTime
	 * TemplateKey	YKK_LBL_StockinDateTime
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_StockinDateTime = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_StockinDateTime" , "YKK_LBL_StockinDateTime");

	/**
	 * ControlID	lbl_Date
	 * TemplateKey	YKK_LBL_Date
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Date = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Date" , "YKK_LBL_Date");

	/**
	 * ControlID	txt_StockinDate
	 * TemplateKey	YKK_TXT_StockinDate
	 * ControlType	DateTextBox
	 */
	public jp.co.daifuku.bluedog.ui.control.DateTextBox txt_StockinDate = jp.co.daifuku.bluedog.ui.control.DateTextBoxFactory.getInstance("txt_StockinDate" , "YKK_TXT_StockinDate");

	/**
	 * ControlID	lbl_Time
	 * TemplateKey	YKK_LBL_Time
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Time = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Time" , "YKK_LBL_Time");

	/**
	 * ControlID	txt_StockinTime
	 * TemplateKey	YKK_TXT_StockinTime
	 * ControlType	TimeTextBox
	 */
	public jp.co.daifuku.bluedog.ui.control.TimeTextBox txt_StockinTime = jp.co.daifuku.bluedog.ui.control.TimeTextBoxFactory.getInstance("txt_StockinTime" , "YKK_TXT_StockinTime");

	/**
	 * ControlID	lbl_BeforeThisDate
	 * TemplateKey	YKK_LBL_BeforeThisDate
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_BeforeThisDate = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_BeforeThisDate" , "YKK_LBL_BeforeThisDate");

	/**
	 * ControlID	rdo_BitsStorageStockout
	 * TemplateKey	YKK_RDO_BitsStorageStockout
	 * ControlType	RadioButton
	 */
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_BitsStorageStockout = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_BitsStorageStockout" , "YKK_RDO_BitsStorageStockout");

	/**
	 * ControlID	lbl_ItemNo1
	 * TemplateKey	YKK_LBL_ItemNo
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ItemNo1 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ItemNo1" , "YKK_LBL_ItemNo");

	/**
	 * ControlID	txt_ItemNo1
	 * TemplateKey	YKK_TXT_ItemNo
	 * ControlType	FreeTextBox
	 */
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_ItemNo1 = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_ItemNo1" , "YKK_TXT_ItemNo");

	/**
	 * ControlID	btn_ItemBrowse1
	 * TemplateKey	YKK_BTN_ItemBrowse_POPUP
	 * ControlType	SubmitButton
	 */
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_ItemBrowse1 = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_ItemBrowse1" , "YKK_BTN_ItemBrowse_POPUP");

	/**
	 * ControlID	lbl_InstockCount
	 * TemplateKey	YKK_LBL_InstockCount
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_InstockCount = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_InstockCount" , "YKK_LBL_InstockCount");

	/**
	 * ControlID	txt_InstockCount
	 * TemplateKey	YKK_TXT_InstockCount
	 * ControlType	NumberTextBox
	 */
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_InstockCount = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_InstockCount" , "YKK_TXT_InstockCount");

	/**
	 * ControlID	lbl_FewerThanThis
	 * TemplateKey	YKK_LBL_FewerThanThis
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_FewerThanThis = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_FewerThanThis" , "YKK_LBL_FewerThanThis");

	/**
	 * ControlID	rdo_LocationStockout
	 * TemplateKey	YKK_RDO_LocationStockout
	 * ControlType	RadioButton
	 */
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_LocationStockout = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_LocationStockout" , "YKK_RDO_LocationStockout");

	/**
	 * ControlID	rdo_LocationRange
	 * TemplateKey	YKK_RDO_LocationRange
	 * ControlType	RadioButton
	 */
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_LocationRange = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_LocationRange" , "YKK_RDO_LocationRange");

	/**
	 * ControlID	txt_LocationNoFrom
	 * TemplateKey	YKK_TXT_LocationNoFrom
	 * ControlType	FormatTextBox
	 */
	public jp.co.daifuku.bluedog.ui.control.FormatTextBox txt_LocationNoFrom = jp.co.daifuku.bluedog.ui.control.FormatTextBoxFactory.getInstance("txt_LocationNoFrom" , "YKK_TXT_LocationNoFrom");

	/**
	 * ControlID	lbl_to
	 * TemplateKey	YKK_LBL_to
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_to = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_to" , "YKK_LBL_to");

	/**
	 * ControlID	txt_LocationNoTo
	 * TemplateKey	YKK_TXT_LocationNoTo
	 * ControlType	FormatTextBox
	 */
	public jp.co.daifuku.bluedog.ui.control.FormatTextBox txt_LocationNoTo = jp.co.daifuku.bluedog.ui.control.FormatTextBoxFactory.getInstance("txt_LocationNoTo" , "YKK_TXT_LocationNoTo");

	/**
	 * ControlID	rdo_ItemNo2
	 * TemplateKey	YKK_RDO_ItemCode
	 * ControlType	RadioButton
	 */
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_ItemNo2 = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_ItemNo2" , "YKK_RDO_ItemCode");

	/**
	 * ControlID	txt_ItemNo2
	 * TemplateKey	YKK_TXT_ItemNo
	 * ControlType	FreeTextBox
	 */
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_ItemNo2 = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_ItemNo2" , "YKK_TXT_ItemNo");

	/**
	 * ControlID	btn_ItemBrowse2
	 * TemplateKey	YKK_BTN_ItemBrowse_POPUP
	 * ControlType	SubmitButton
	 */
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_ItemBrowse2 = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_ItemBrowse2" , "YKK_BTN_ItemBrowse_POPUP");

	/**
	 * ControlID	lbl_ColorCode2
	 * TemplateKey	YKK_LBL_ColorCode
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ColorCode2 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ColorCode2" , "YKK_LBL_ColorCode");

	/**
	 * ControlID	txt_ColorCode2
	 * TemplateKey	YKK_TXT_ColorCode
	 * ControlType	FreeTextBox
	 */
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_ColorCode2 = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_ColorCode2" , "YKK_TXT_ColorCode");

	/**
	 * ControlID	rdo_SearchStockout
	 * TemplateKey	YKK_RDO_SearchStockout
	 * ControlType	RadioButton
	 */
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_SearchStockout = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_SearchStockout" , "YKK_RDO_SearchStockout");

	/**
	 * ControlID	lbl_ItemNo3
	 * TemplateKey	YKK_LBL_ItemNo
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ItemNo3 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ItemNo3" , "YKK_LBL_ItemNo");

	/**
	 * ControlID	txt_ItemNo3
	 * TemplateKey	YKK_TXT_ItemNo
	 * ControlType	FreeTextBox
	 */
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_ItemNo3 = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_ItemNo3" , "YKK_TXT_ItemNo");

	/**
	 * ControlID	btn_ItemBrowse3
	 * TemplateKey	YKK_BTN_ItemBrowse_POPUP
	 * ControlType	SubmitButton
	 */
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_ItemBrowse3 = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_ItemBrowse3" , "YKK_BTN_ItemBrowse_POPUP");

	/**
	 * ControlID	lbl_ColorCode
	 * TemplateKey	YKK_LBL_ColorCode
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ColorCode = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ColorCode" , "YKK_LBL_ColorCode");

	/**
	 * ControlID	txt_ColorCode
	 * TemplateKey	YKK_TXT_ColorCode
	 * ControlType	FreeTextBox
	 */
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_ColorCode = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_ColorCode" , "YKK_TXT_ColorCode");

	/**
	 * ControlID	rdo_DesignateLocationStockout
	 * TemplateKey	YKK_RDO_DesignateLocationStockout
	 * ControlType	RadioButton
	 */
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_DesignateLocationStockout = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_DesignateLocationStockout" , "YKK_RDO_DesignateLocationStockout");

	/**
	 * ControlID	lbl_LocationNo
	 * TemplateKey	W_LocationNo
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_LocationNo = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_LocationNo" , "W_LocationNo");

	/**
	 * ControlID	txt_LocationNo
	 * TemplateKey	YKK_TXT_LocationNo
	 * ControlType	FormatTextBox
	 */
	public jp.co.daifuku.bluedog.ui.control.FormatTextBox txt_LocationNo = jp.co.daifuku.bluedog.ui.control.FormatTextBoxFactory.getInstance("txt_LocationNo" , "YKK_TXT_LocationNo");

	/**
	 * ControlID	chk_AfterThisLocation
	 * TemplateKey	YKK_CHK_AfterThisLocation
	 * ControlType	CheckBox
	 */
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_AfterThisLocation = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_AfterThisLocation" , "YKK_CHK_AfterThisLocation");

	/**
	 * ControlID	lbl_Memo
	 * TemplateKey	YKK_LBL_Memo
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Memo = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Memo" , "YKK_LBL_Memo");

	/**
	 * ControlID	txt_Memo
	 * TemplateKey	YKK_TXT_Memo
	 * ControlType	FreeTextBox
	 */
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_Memo = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_Memo" , "YKK_TXT_Memo");

	/**
	 * ControlID	btn_Set
	 * TemplateKey	YKK_BTN_Set_POPUP
	 * ControlType	SubmitButton
	 */
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Set = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Set" , "YKK_BTN_Set_POPUP");

}
//end of class
