// $Id: skelten.java,v 1.2 2007/03/07 07:45:22 suresh Exp $

/*
 * Copyright 2000-2001 DAIFUKU Co.,Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of DAIFUKU Co.,Ltd.
 * Use is subject to license terms.
 */
package jp.co.daifuku.wms.YkkGMAX.Stockout;
import jp.co.daifuku.bluedog.ui.control.Page;

/**
 * This class can not be changed and it is generated by ScreenGenerator.
 * 
 * <BR>
 * <TABLE BORDER="1" CELLPADDING="3" CELLSPACING="0">
 * <TR BGCOLOR="#CCCCFF" CLASS="TableHeadingColor"><TD>Date</TD><TD>Name</TD><TD>Comment</TD></TR>
 * <TR><TD>2004/02/13</TD><TD>N.Sawa(DFK)</TD><TD>created this class</TD></TR>
 * </TABLE>
 * <BR>
 * @version $Revision: 1.2 $, $Date: 2007/03/07 07:45:22 $
 * @author  $Author: suresh $
 */
public class ExternalStockoutStart extends Page
{

	// Class variables -----------------------------------------------
	public jp.co.daifuku.bluedog.ui.control.Label lbl_SettingName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_SettingName" , "YKK_LBL_ExternalStockoutStart");
	public jp.co.daifuku.bluedog.ui.control.LinkButton btn_Help = jp.co.daifuku.bluedog.ui.control.LinkButtonFactory.getInstance("btn_Help" , "Help");
	public jp.co.daifuku.bluedog.ui.control.Message message = jp.co.daifuku.bluedog.ui.control.MessageFactory.getInstance("message" , "OperationMsg");
	public jp.co.daifuku.bluedog.ui.control.Tab tab = jp.co.daifuku.bluedog.ui.control.TabFactory.getInstance("tab" , "YKK_TAB_Setting");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_ToMenu = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_ToMenu" , "To_Menu");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Section = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Section" , "YKK_LBL_Section");
	public jp.co.daifuku.bluedog.ui.control.PullDown pul_Section = jp.co.daifuku.bluedog.ui.control.PullDownFactory.getInstance("pul_Section" , "YKK_PUL_Section");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_RetrievalNo = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_RetrievalNo" , "YKK_LBL_RetrievalNo");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_RetrievalNo = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_RetrievalNo" , "YKK_TXT_RetrievalNo");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_OrderNo = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_OrderNo" , "YKK_LBL_OrderNo");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_OrderNo = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_OrderNo" , "YKK_TXT_OrderNo");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Show = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Show" , "YKK_BTN_Show");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_OrderBy = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_OrderBy" , "YKK_LBL_OrderBy");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_ItemNo = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_ItemNo" , "YKK_RDO_ItemNoChcked");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_StockinTime = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_StockinTime" , "YKK_RDO_StockinTime");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_SelectAllUnit = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_SelectAllUnit" , "YKK_BTN_SelectAllUnit");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_SelectAll = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_SelectAll" , "YKK_BTN_SelectAll");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_UnselectAll = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_UnselectAll" , "YKK_BTN_UnselectAll");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Set_Up = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Set_Up" , "YKK_BTN_Set");
	public jp.co.daifuku.bluedog.ui.control.Pager pgr_Up = jp.co.daifuku.bluedog.ui.control.PagerFactory.getInstance("pgr_Up" , "YKK_Pager");
	public jp.co.daifuku.bluedog.ui.control.ListCell lst_ExternalStockoutStart = jp.co.daifuku.bluedog.ui.control.ListCellFactory.getInstance("lst_ExternalStockoutStart" , "YKK_LST_ExternalStockoutStart");
	public jp.co.daifuku.bluedog.ui.control.Pager pgr_Low = jp.co.daifuku.bluedog.ui.control.PagerFactory.getInstance("pgr_Low" , "YKK_Pager");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Set_Low = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Set_Low" , "YKK_BTN_Set");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_ReleaseStorage = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_ReleaseStorage" , "YKK_BTN_ReleaseStorage");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_DesignateStockoutStation = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_DesignateStockoutStation" , "YKK_LBL_DesignateStockoutStation");
	public jp.co.daifuku.bluedog.ui.control.PullDown pul_DesignateStockoutStation = jp.co.daifuku.bluedog.ui.control.PullDownFactory.getInstance("pul_DesignateStockoutStation" , "YKK_PUL_DesignateStockoutStation");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_Auto = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_Auto" , "YKK_RDO_Auto");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_Picking = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_Picking" , "YKK_RDO_Picking");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_SelectedUnitCount = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_SelectedUnitCount" , "YKK_LBL_SelectedUnitCount");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_EqualsMark = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_EqualsMark" , "YKK_LBL_EqualsMark");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_SelectedUnitCount = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_SelectedUnitCount" , "YKK_TXT_SelectedUnitCount_RO");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_TotalStockOutQty = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_TotalStockOutQty" , "YKK_LBL_TotalStockOutQty");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_EqualsMark_2 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_EqualsMark_2" , "YKK_LBL_EqualsMark");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_TotalStockOutQty = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_TotalStockOutQty" , "YKK_TXT_TotalStockOutQty");

}
//end of class
