// $Id: skelten.java,v 1.2 2007/03/07 07:45:22 suresh Exp $

/*
 * Copyright 2000-2001 DAIFUKU Co.,Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of DAIFUKU Co.,Ltd.
 * Use is subject to license terms.
 */
package jp.co.daifuku.wms.YkkGMAX.Stockout;

import jp.co.daifuku.bluedog.ui.control.Page;

/**
 * This class can not be changed and it is generated by ScreenGenerator.
 * 
 * <BR>
 * <TABLE BORDER="1" CELLPADDING="3" CELLSPACING="0">
 * <TR BGCOLOR="#CCCCFF" CLASS="TableHeadingColor">
 * <TD>Date</TD>
 * <TD>Name</TD>
 * <TD>Comment</TD>
 * </TR>
 * <TR>
 * <TD>2004/02/13</TD>
 * <TD>N.Sawa(DFK)</TD>
 * <TD>created this class</TD>
 * </TR>
 * </TABLE> <BR>
 * 
 * @version $Revision: 1.2 $, $Date: 2007/03/07 07:45:22 $
 * @author $Author: suresh $
 */
public class FinalProcedureStockoutStationSwitch extends Page
{

	// Class variables -----------------------------------------------
	public jp.co.daifuku.bluedog.ui.control.Label lbl_SettingName = jp.co.daifuku.bluedog.ui.control.LabelFactory
			.getInstance("lbl_SettingName",
					"YKK_LBL_FinalProcedureStockoutStationSwitch");
	public jp.co.daifuku.bluedog.ui.control.LinkButton btn_Help = jp.co.daifuku.bluedog.ui.control.LinkButtonFactory
			.getInstance("btn_Help", "Help");
	public jp.co.daifuku.bluedog.ui.control.Message message = jp.co.daifuku.bluedog.ui.control.MessageFactory
			.getInstance("message", "OperationMsg");
	public jp.co.daifuku.bluedog.ui.control.Tab tab = jp.co.daifuku.bluedog.ui.control.TabFactory
			.getInstance("tab", "YKK_TAB_Switch");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_ToMenu = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory
			.getInstance("btn_ToMenu", "To_Menu");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_CurrentStockoutStation = jp.co.daifuku.bluedog.ui.control.LabelFactory
			.getInstance("lbl_CurrentStockoutStation",
					"YKK_LBL_CurrentStockoutStation");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ChangedStockoutStation = jp.co.daifuku.bluedog.ui.control.LabelFactory
			.getInstance("lbl_ChangedStockoutStation",
					"YKK_LBL_ChangedStockoutStation");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_StcokoutStation31 = jp.co.daifuku.bluedog.ui.control.LabelFactory
			.getInstance("lbl_StcokoutStation31", "YKK_LBL_StcokoutStation31");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_CurrentStcokoutStation31 = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory
			.getInstance("txt_CurrentStcokoutStation31",
					"YKK_TXT_CurrentStockoutStation_RO");
	public jp.co.daifuku.bluedog.ui.control.PullDown pul_ChangedStockoutStation31 = jp.co.daifuku.bluedog.ui.control.PullDownFactory
			.getInstance("pul_ChangedStockoutStation31",
					"YKK_PUL_ChangedStockoutStation3F");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_StcokoutStation32 = jp.co.daifuku.bluedog.ui.control.LabelFactory
			.getInstance("lbl_StcokoutStation32", "YKK_LBL_StcokoutStation32");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_CurrentStcokoutStation32 = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory
			.getInstance("txt_CurrentStcokoutStation32",
					"YKK_TXT_CurrentStockoutStation_RO");
	public jp.co.daifuku.bluedog.ui.control.PullDown pul_ChangedStockoutStation32 = jp.co.daifuku.bluedog.ui.control.PullDownFactory
			.getInstance("pul_ChangedStockoutStation32",
					"YKK_PUL_ChangedStockoutStation3F");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_StcokoutStation41 = jp.co.daifuku.bluedog.ui.control.LabelFactory
			.getInstance("lbl_StcokoutStation41", "YKK_LBL_StcokoutStation41");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_CurrentStcokoutStation41 = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory
			.getInstance("txt_CurrentStcokoutStation41",
					"YKK_TXT_CurrentStockoutStation_RO");
	public jp.co.daifuku.bluedog.ui.control.PullDown pul_ChangedStockoutStation41 = jp.co.daifuku.bluedog.ui.control.PullDownFactory
			.getInstance("pul_ChangedStockoutStation41",
					"YKK_PUL_ChangedStockoutStation4F");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_StcokoutStation42 = jp.co.daifuku.bluedog.ui.control.LabelFactory
			.getInstance("lbl_StcokoutStation42", "YKK_LBL_StcokoutStation42");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_CurrentStcokoutStation42 = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory
			.getInstance("txt_CurrentStcokoutStation42",
					"YKK_TXT_CurrentStockoutStation_RO");
	public jp.co.daifuku.bluedog.ui.control.PullDown pul_ChangedStockoutStation42 = jp.co.daifuku.bluedog.ui.control.PullDownFactory
			.getInstance("pul_ChangedStockoutStation42",
					"YKK_PUL_ChangedStockoutStation4F");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Set = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory
			.getInstance("btn_Set", "YKK_BTN_Set");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Show = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory
			.getInstance("btn_Show", "YKK_BTN_Show");

}
// end of class
