// $Id: LableReprint.java,v 1.1 2007/12/13 06:25:10 administrator Exp $

/*
 * Copyright 2000-2001 DAIFUKU Co.,Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of DAIFUKU Co.,Ltd.
 * Use is subject to license terms.
 */
package jp.co.daifuku.wms.YkkGMAX.Stockout;
import jp.co.daifuku.bluedog.ui.control.Page;

/**
 * This class can not be changed and it is generated by ScreenGenerator.
 * 
 * <BR>
 * <TABLE BORDER="1" CELLPADDING="3" CELLSPACING="0">
 * <TR BGCOLOR="#CCCCFF" CLASS="TableHeadingColor"><TD>Date</TD><TD>Name</TD><TD>Comment</TD></TR>
 * <TR><TD>2004/02/13</TD><TD>N.Sawa(DFK)</TD><TD>created this class</TD></TR>
 * </TABLE>
 * <BR>
 * @version $Revision: 1.1 $, $Date: 2007/12/13 06:25:10 $
 * @author  $Author: administrator $
 */
public class LableReprint extends Page
{

	// Class variables -----------------------------------------------
	public jp.co.daifuku.bluedog.ui.control.Label lbl_SettingName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_SettingName" , "YKK_LBL_LableReprint");
	public jp.co.daifuku.bluedog.ui.control.LinkButton btn_Help = jp.co.daifuku.bluedog.ui.control.LinkButtonFactory.getInstance("btn_Help" , "Help");
	public jp.co.daifuku.bluedog.ui.control.Message message = jp.co.daifuku.bluedog.ui.control.MessageFactory.getInstance("message" , "OperationMsg");
	public jp.co.daifuku.bluedog.ui.control.Tab tab = jp.co.daifuku.bluedog.ui.control.TabFactory.getInstance("tab" , "YKK_TAB_Reprint");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_ToMenu = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_ToMenu" , "To_Menu");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_PrintStation = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_PrintStation" , "YKK_LBL_PrintStation");
	public jp.co.daifuku.bluedog.ui.control.PullDown pul_PrintStation = jp.co.daifuku.bluedog.ui.control.PullDownFactory.getInstance("pul_PrintStation" , "YKK_PUL_PrintStation");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_LableType = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_LableType" , "YKK_LBL_LableType");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_NormalStockout = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_NormalStockout" , "YKK_RDO_NormalStockoutChecked");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_FuyongStockout = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_FuyongStockout" , "YKK_RDO_FuyongStockout");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_ExternalStockout = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_ExternalStockout" , "YKK_RDO_ExternalStockout");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_CustomerStockout = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_CustomerStockout" , "YKK_RDO_CustomerStockout");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_PrintDateTime = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_PrintDateTime" , "YKK_LBL_PrintDateTime");
	public jp.co.daifuku.bluedog.ui.control.DateTextBox txt_PrintDateFrom = jp.co.daifuku.bluedog.ui.control.DateTextBoxFactory.getInstance("txt_PrintDateFrom" , "YKK_TXT_PrintDateFrom");
	public jp.co.daifuku.bluedog.ui.control.TimeTextBox txt_PrintTimeFrom = jp.co.daifuku.bluedog.ui.control.TimeTextBoxFactory.getInstance("txt_PrintTimeFrom" , "YKK_TXT_PrintTimeFrom");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_to = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_to" , "YKK_LBL_to");
	public jp.co.daifuku.bluedog.ui.control.DateTextBox txt_PrintDateTo = jp.co.daifuku.bluedog.ui.control.DateTextBoxFactory.getInstance("txt_PrintDateTo" , "YKK_TXT_PrintDateTo");
	public jp.co.daifuku.bluedog.ui.control.TimeTextBox txt_PrintTimeTo = jp.co.daifuku.bluedog.ui.control.TimeTextBoxFactory.getInstance("txt_PrintTimeTo" , "YKK_TXT_PrintTimeTo");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Show = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Show" , "YKK_BTN_Show");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Print = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Print" , "YKK_BTN_Print");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ReprintStation = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ReprintStation" , "YKK_LBL_ReprintStation");
	public jp.co.daifuku.bluedog.ui.control.PullDown pul_ReprintStation = jp.co.daifuku.bluedog.ui.control.PullDownFactory.getInstance("pul_ReprintStation" , "YKK_PUL_ReprintStation");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_LableInfo = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_LableInfo" , "YKK_LBL_LableInfo");
	public jp.co.daifuku.bluedog.ui.control.Pager pgr_Up = jp.co.daifuku.bluedog.ui.control.PagerFactory.getInstance("pgr_Up" , "YKK_Pager");
	public jp.co.daifuku.bluedog.ui.control.ListCell lst_LableReprint = jp.co.daifuku.bluedog.ui.control.ListCellFactory.getInstance("lst_LableReprint" , "YKK_LST_LableReprint");
	public jp.co.daifuku.bluedog.ui.control.Pager pgr_Low = jp.co.daifuku.bluedog.ui.control.PagerFactory.getInstance("pgr_Low" , "YKK_Pager");

}
//end of class
