// $Id: skelten.java,v 1.2 2007/03/07 07:45:22 suresh Exp $

/*
 * Copyright 2000-2001 DAIFUKU Co.,Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of DAIFUKU Co.,Ltd.
 * Use is subject to license terms.
 */
package jp.co.daifuku.wms.YkkGMAX.Stockout;
import jp.co.daifuku.bluedog.ui.control.Page;

/**
 * This class can not be changed and it is generated by ScreenGenerator.
 * 
 * <BR>
 * <TABLE BORDER="1" CELLPADDING="3" CELLSPACING="0">
 * <TR BGCOLOR="#CCCCFF" CLASS="TableHeadingColor"><TD>Date</TD><TD>Name</TD><TD>Comment</TD></TR>
 * <TR><TD>2004/02/13</TD><TD>N.Sawa(DFK)</TD><TD>created this class</TD></TR>
 * </TABLE>
 * <BR>
 * @version $Revision: 1.2 $, $Date: 2007/03/07 07:45:22 $
 * @author  $Author: suresh $
 */
public class StockoutStart extends Page
{

	// Class variables -----------------------------------------------

	/**
	 * ControlID	lbl_SettingName
	 * TemplateKey	YKK_LBL_StockoutStart
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_SettingName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_SettingName" , "YKK_LBL_StockoutStart");

	/**
	 * ControlID	btn_Help
	 * TemplateKey	Help
	 * ControlType	LinkButton
	 */
	public jp.co.daifuku.bluedog.ui.control.LinkButton btn_Help = jp.co.daifuku.bluedog.ui.control.LinkButtonFactory.getInstance("btn_Help" , "Help");

	/**
	 * ControlID	message
	 * TemplateKey	OperationMsg
	 * ControlType	Message
	 */
	public jp.co.daifuku.bluedog.ui.control.Message message = jp.co.daifuku.bluedog.ui.control.MessageFactory.getInstance("message" , "OperationMsg");

	/**
	 * ControlID	btn_ToMenu
	 * TemplateKey	To_Menu
	 * ControlType	SubmitButton
	 */
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_ToMenu = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_ToMenu" , "To_Menu");

	/**
	 * ControlID	rdo_OtherProcedure
	 * TemplateKey	YKK_RDO_OtherProcedure
	 * ControlType	RadioButton
	 */
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_OtherProcedure = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_OtherProcedure" , "YKK_RDO_OtherProcedure");

	/**
	 * ControlID	txt_Section
	 * TemplateKey	YKK_TXT_Section
	 * ControlType	FreeTextBox
	 */
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_Section = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_Section" , "YKK_TXT_Section");

	/**
	 * ControlID	lbl_Line
	 * TemplateKey	YKK_LBL_Line
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Line = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Line" , "YKK_LBL_Line");

	/**
	 * ControlID	txt_Line
	 * TemplateKey	YKK_TXT_Line
	 * ControlType	FreeTextBox
	 */
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_Line = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_Line" , "YKK_TXT_Line");

	/**
	 * ControlID	rdo_AssemblyLineWorkingProcedu
	 * TemplateKey	YKK_RDO_AssemblyLineWorkingProcedure
	 * ControlType	RadioButton
	 */
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_AssemblyLineWorkingProcedu = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_AssemblyLineWorkingProcedu" , "YKK_RDO_AssemblyLineWorkingProcedure");

	/**
	 * ControlID	lbl_LineDivision
	 * TemplateKey	YKK_LBL_LineDivision
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_LineDivision = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_LineDivision" , "YKK_LBL_LineDivision");

	/**
	 * ControlID	txt_LineDivision
	 * TemplateKey	YKK_TXT_LineDivision
	 * ControlType	NumberTextBox
	 */
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_LineDivision = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_LineDivision" , "YKK_TXT_LineDivision");

	/**
	 * ControlID	rdo_FinalProcedure
	 * TemplateKey	YKK_RDO_FinalProcedure
	 * ControlType	RadioButton
	 */
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_FinalProcedure = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_FinalProcedure" , "YKK_RDO_FinalProcedure");

	/**
	 * ControlID	btn_Show
	 * TemplateKey	YKK_BTN_Show
	 * ControlType	SubmitButton
	 */
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Show = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Show" , "YKK_BTN_Show");

	/**
	 * ControlID	lbl_OrderBy
	 * TemplateKey	YKK_LBL_OrderBy
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_OrderBy = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_OrderBy" , "YKK_LBL_OrderBy");

	/**
	 * ControlID	rdo_ItemNo
	 * TemplateKey	YKK_RDO_ItemNoChcked
	 * ControlType	RadioButton
	 */
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_ItemNo = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_ItemNo" , "YKK_RDO_ItemNoChcked");

	/**
	 * ControlID	rdo_StockinTime
	 * TemplateKey	YKK_RDO_StockinTime
	 * ControlType	RadioButton
	 */
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_StockinTime = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_StockinTime" , "YKK_RDO_StockinTime");

	/**
	 * ControlID	lbl_RetrievalNo
	 * TemplateKey	YKK_LBL_RetrievalNo
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_RetrievalNo = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_RetrievalNo" , "YKK_LBL_RetrievalNo");

	/**
	 * ControlID	txt_RetrievalNo
	 * TemplateKey	YKK_TXT_RetrievalNo
	 * ControlType	FreeTextBox
	 */
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_RetrievalNo = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_RetrievalNo" , "YKK_TXT_RetrievalNo");

	/**
	 * ControlID	btn_SelectAllUnit
	 * TemplateKey	YKK_BTN_SelectAllUnit
	 * ControlType	SubmitButton
	 */
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_SelectAllUnit = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_SelectAllUnit" , "YKK_BTN_SelectAllUnit");

	/**
	 * ControlID	btn_SelectAll
	 * TemplateKey	YKK_BTN_SelectAll
	 * ControlType	SubmitButton
	 */
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_SelectAll = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_SelectAll" , "YKK_BTN_SelectAll");

	/**
	 * ControlID	btn_UnselectAll
	 * TemplateKey	YKK_BTN_UnselectAll
	 * ControlType	SubmitButton
	 */
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_UnselectAll = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_UnselectAll" , "YKK_BTN_UnselectAll");

	/**
	 * ControlID	btn_Set_Up
	 * TemplateKey	YKK_BTN_Set
	 * ControlType	SubmitButton
	 */
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Set_Up = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Set_Up" , "YKK_BTN_Set");

	/**
	 * ControlID	pgr_Up
	 * TemplateKey	YKK_Pager
	 * ControlType	Pager
	 */
	public jp.co.daifuku.bluedog.ui.control.Pager pgr_Up = jp.co.daifuku.bluedog.ui.control.PagerFactory.getInstance("pgr_Up" , "YKK_Pager");

	/**
	 * ControlID	lst_StockoutStart
	 * TemplateKey	YKK_LST_StockoutStart
	 * ControlType	ListCell
	 */
	public jp.co.daifuku.bluedog.ui.control.ListCell lst_StockoutStart = jp.co.daifuku.bluedog.ui.control.ListCellFactory.getInstance("lst_StockoutStart" , "YKK_LST_StockoutStart");

	/**
	 * ControlID	pgr_Low
	 * TemplateKey	YKK_Pager
	 * ControlType	Pager
	 */
	public jp.co.daifuku.bluedog.ui.control.Pager pgr_Low = jp.co.daifuku.bluedog.ui.control.PagerFactory.getInstance("pgr_Low" , "YKK_Pager");

	/**
	 * ControlID	btn_Set_Low
	 * TemplateKey	YKK_BTN_Set
	 * ControlType	SubmitButton
	 */
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Set_Low = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Set_Low" , "YKK_BTN_Set");

	/**
	 * ControlID	btn_ReleaseStorage
	 * TemplateKey	YKK_BTN_ReleaseStorage
	 * ControlType	SubmitButton
	 */
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_ReleaseStorage = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_ReleaseStorage" , "YKK_BTN_ReleaseStorage");

	/**
	 * ControlID	lbl_DesignateStockoutStation
	 * TemplateKey	YKK_LBL_DesignateStockoutStation
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_DesignateStockoutStation = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_DesignateStockoutStation" , "YKK_LBL_DesignateStockoutStation");

	/**
	 * ControlID	pul_DesignateStockoutStation
	 * TemplateKey	YKK_PUL_DesignateStockoutStation
	 * ControlType	PullDown
	 */
	public jp.co.daifuku.bluedog.ui.control.PullDown pul_DesignateStockoutStation = jp.co.daifuku.bluedog.ui.control.PullDownFactory.getInstance("pul_DesignateStockoutStation" , "YKK_PUL_DesignateStockoutStation");

	/**
	 * ControlID	rdo_Auto
	 * TemplateKey	YKK_RDO_Auto
	 * ControlType	RadioButton
	 */
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_Auto = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_Auto" , "YKK_RDO_Auto");

	/**
	 * ControlID	rdo_Picking
	 * TemplateKey	YKK_RDO_Picking
	 * ControlType	RadioButton
	 */
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_Picking = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_Picking" , "YKK_RDO_Picking");

	/**
	 * ControlID	lbl_SelectedUnitCount
	 * TemplateKey	YKK_LBL_SelectedUnitCount
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_SelectedUnitCount = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_SelectedUnitCount" , "YKK_LBL_SelectedUnitCount");

	/**
	 * ControlID	lbl_EqualsMark
	 * TemplateKey	YKK_LBL_EqualsMark
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_EqualsMark = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_EqualsMark" , "YKK_LBL_EqualsMark");

	/**
	 * ControlID	txt_SelectedUnitCount
	 * TemplateKey	YKK_TXT_SelectedUnitCount_RO
	 * ControlType	NumberTextBox
	 */
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_SelectedUnitCount = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_SelectedUnitCount" , "YKK_TXT_SelectedUnitCount_RO");

	/**
	 * ControlID	lbl_TotalStockOutQty
	 * TemplateKey	YKK_LBL_TotalStockOutQty
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_TotalStockOutQty = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_TotalStockOutQty" , "YKK_LBL_TotalStockOutQty");

	/**
	 * ControlID	lbl_EqualsMark_2
	 * TemplateKey	YKK_LBL_EqualsMark
	 * ControlType	Label
	 */
	public jp.co.daifuku.bluedog.ui.control.Label lbl_EqualsMark_2 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_EqualsMark_2" , "YKK_LBL_EqualsMark");

	/**
	 * ControlID	txt_TotalStockOutQty
	 * TemplateKey	YKK_TXT_TotalStockOutQty
	 * ControlType	NumberTextBox
	 */
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_TotalStockOutQty = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_TotalStockOutQty" , "YKK_TXT_TotalStockOutQty");

}
//end of class
