// $Id: DefineReportDataInstock.java,v 1.2 2006/11/13 08:18:48 suresh Exp $

//#CM688740
/*
 * Copyright 2000-2001 DAIFUKU Co.,Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of DAIFUKU Co.,Ltd.
 * Use is subject to license terms.
 */
package jp.co.daifuku.wms.base.system.display.web.definereportdata;
import jp.co.daifuku.bluedog.ui.control.Page;

//#CM688741
/**
 * Non variable class generated by a tool.
 * 
 * <BR>
 * <TABLE BORDER="1" CELLPADDING="3" CELLSPACING="0">
 * <TR BGCOLOR="#CCCCFF" CLASS="TableHeadingColor"><TD>Date</TD><TD>Name</TD><TD>Comment</TD></TR>
 * <TR><TD>2004/02/13</TD><TD>N.Sawa(DFK)</TD><TD>created this class</TD></TR>
 * </TABLE>
 * <BR>
 * @version $Revision: 1.2 $, $Date: 2006/11/13 08:18:48 $
 * @author  $Author: suresh $
 */
public class DefineReportDataInstock extends Page
{

	//#CM688742
	// Class variables -----------------------------------------------
	public jp.co.daifuku.bluedog.ui.control.Label lbl_SettingName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_SettingName" , "In_SettingName");
	public jp.co.daifuku.bluedog.ui.control.LinkButton btn_Help = jp.co.daifuku.bluedog.ui.control.LinkButtonFactory.getInstance("btn_Help" , "Help");
	public jp.co.daifuku.bluedog.ui.control.Message message = jp.co.daifuku.bluedog.ui.control.MessageFactory.getInstance("message" , "OperationMsg");
	public jp.co.daifuku.bluedog.ui.control.Tab tab_RptClmSetInstk = jp.co.daifuku.bluedog.ui.control.TabFactory.getInstance("tab_RptClmSetInstk" , "W_RptClm_SetInstk");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Back = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Back" , "Back");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_ToMenu = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_ToMenu" , "To_Menu");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Valid1 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Valid1" , "W_Valid");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_DigitsUseLength1 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_DigitsUseLength1" , "W_DigitsUseLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLength1 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLength1" , "W_MaxLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Position1 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Position1" , "W_Position");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Valid2 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Valid2" , "W_Valid");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_DigitsUseLength2 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_DigitsUseLength2" , "W_DigitsUseLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLength2 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLength2" , "W_MaxLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Position2 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Position2" , "W_Position");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_InstockPlanDate = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_InstockPlanDate" , "W_InstockPlanDate");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_InstkPlanDate = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_InstkPlanDate" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_InstkPlanDateLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_InstkPlanDateLen" , "W_InstkPlanDateLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenInstkPlanDate = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenInstkPlanDate" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_InstkPlanDatePst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_InstkPlanDatePst" , "W_InstkPlanDatePst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ItemName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ItemName" , "W_ItemName");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_ItemNm = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_ItemNm" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_ItemNmLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_ItemNmLen" , "W_ItemNameLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenItemNm = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenItemNm" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_ItemNmPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_ItemNmPst" , "W_ItemNamePosition");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_OrderDate = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_OrderDate" , "W_OrderDate");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_OrderingDate = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_OrderingDate" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_OrderingDateLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_OrderingDateLen" , "W_OdrgDateLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenOrderingDate = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenOrderingDate" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_OrderingDatePst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_OrderingDatePst" , "W_OdrgDatePst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_InstkPlanQtyPtl = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_InstkPlanQtyPtl" , "W_InstkPlanQtyPtl");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_InstkPlanQtyPtl = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_InstkPlanQtyPtl" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_InstkPlanQtyPtlLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_InstkPlanQtyPtlLen" , "W_InstkPlanQtyPtlLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenInstkPlanQtyPtl = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenInstkPlanQtyPtl" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_InstkPlanQtyPtlPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_InstkPlanQtyPtlPst" , "W_InstkPlanQtyPtlPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ConsignorCode = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ConsignorCode" , "W_ConsignorCode");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_CnsgnrCd = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_CnsgnrCd" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CnsgnrCdLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CnsgnrCdLen" , "W_CnsgnrCdLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenCnsgnrCd = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenCnsgnrCd" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CnsgnrCdPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CnsgnrCdPst" , "W_CnsgnrCdPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_TCDCFlag = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_TCDCFlag" , "W_TCDCFlag");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_TCDCfFlg = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_TCDCfFlg" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_TCDCfFlgLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_TCDCfFlgLen" , "W_TCDCFlagLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenTCDCfFlg = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenTCDCfFlg" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_TCDCFlgPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_TCDCFlgPst" , "W_TCDCFlagPosition");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ConsignorName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ConsignorName" , "W_ConsignorName");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_CnsgnrNm = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_CnsgnrNm" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CnsgnrNmLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CnsgnrNmLen" , "W_CnsgnrNmLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenCnsgnrNm = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenCnsgnrNm" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CnsgnrNmPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CnsgnrNmPst" , "W_CnsgnrNmPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_CustomerCode = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_CustomerCode" , "W_CustomerCode");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_CustCd = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_CustCd" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CustCdLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CustCdLen" , "W_CustCdLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenCustCd = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenCustCd" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CustCdPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CustCdPst" , "W_CustCdPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_SupplierCode = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_SupplierCode" , "W_SupplierCode");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_SupplierCd = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_SupplierCd" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_SupplierCdLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_SupplierCdLen" , "W_SplCdLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenSupplierCd = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenSupplierCd" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_SupplierCdPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_SupplierCdPst" , "W_SplCdPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_CustomerName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_CustomerName" , "W_CustomerName");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_CustNm = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_CustNm" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CustNmLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CustNmLen" , "W_CustNmLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenCustNm = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenCustNm" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CustNmPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CustNmPst" , "W_CustNmPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_SupplierName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_SupplierName" , "W_SupplierName");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_SupplierNm = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_SupplierNm" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_SupplierNmLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_SupplierNmLen" , "W_SplNmLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenSupplierNm = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenSupplierNm" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_SupplierNmPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_SupplierNmPst" , "W_SplNmPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_InstkQtyPtl = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_InstkQtyPtl" , "W_InstkQtyPtl");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_InstkQtyPtl = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_InstkQtyPtl" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_InstkQtyPtlLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_InstkQtyPtlLen" , "W_InstkQtyPtlLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenInstkQtyPtl = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenInstkQtyPtl" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_InstkQtyPtlPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_InstkQtyPtlPst" , "W_InstkQtyPtlPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_TicketNo = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_TicketNo" , "W_TicketNo");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_TicketNo = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_TicketNo" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_TicketNoLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_TicketNoLen" , "W_TicketNoLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenTicketNo = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenTicketNo" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_TicketNoPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_TicketNoPst" , "W_TicketNoPosition");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_InstockResultDate = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_InstockResultDate" , "W_InstockResultDate");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_InstkRsltDate = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_InstkRsltDate" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_InstkRsltDateLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_InstkRsltDateLen" , "W_InstkRsltDateLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenInstkRsltDate = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenInstkRsltDate" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_InstkRsltDatePst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_InstkRsltDatePst" , "W_InstkRsltDatePst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_TicketLineNo = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_TicketLineNo" , "W_TicketLineNo");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_TicketLineNo = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_TicketLineNo" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_TicketLineNoLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_TicketLineNoLen" , "W_TktLineNoLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenTicketLineNo = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenTicketLineNo" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_TicketLineNoPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_TicketLineNoPst" , "W_TktLineNoPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ResultFlag = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ResultFlag" , "W_ResultFlag");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_RsltFlg = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_RsltFlg" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_RsltFlgLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_RsltFlgLen" , "W_ResultFlagLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenRsltFlg = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenRsltFlg" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_RsltFlgPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_RsltFlgPst" , "W_ResultFlagPosition");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ItemCode = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ItemCode" , "W_ItemCode");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_ItemCd = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_ItemCd" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_ItemCdLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_ItemCdLen" , "W_ItemCodeLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenItemCd = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenItemCd" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_ItemCdPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_ItemCdPst" , "W_ItemCodePosition");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_UseByDate = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_UseByDate" , "W_UseByDate");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_UseByDate = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_UseByDate" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_UseByDateLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_UseByDateLen" , "W_UseByDateLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenUseByDate = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenUseByDate" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_UseByDatePst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_UseByDatePst" , "W_UseByDatePosition");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_BundleItf = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_BundleItf" , "W_BundleItf");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_BundleItf = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_BundleItf" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_BundleItfLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_BundleItfLen" , "W_BundleItfLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenBundleItf = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenBundleItf" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_BundleItfPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_BundleItfPst" , "W_BundleItfPosition");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_CaseItf = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_CaseItf" , "W_CaseItf");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_CaseItf = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_CaseItf" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CaseItfLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CaseItfLen" , "W_CaseItfLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenCaseItf = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenCaseItf" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CaseItfPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CaseItfPst" , "W_CaseItfPosition");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_BundleEntering = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_BundleEntering" , "W_BundleEntering");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_BundleEtr = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_BundleEtr" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_BundleEtrLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_BundleEtrLen" , "W_BdlEtrLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenBundleEtr = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenBundleEtr" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_BundleEtrPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_BundleEtrPst" , "W_BdlEtrPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_CaseEntering = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_CaseEntering" , "W_CaseEntering");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_CaseEtr = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_CaseEtr" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CaseEtrLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CaseEtrLen" , "W_CaseEtrLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenCaseEtr = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenCaseEtr" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CaseEtrPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CaseEtrPst" , "W_CaseEtrPst");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Submit = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Submit" , "Submit");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Clear = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Clear" , "Clear");

}
//#CM688743
//end of class
