// $Id: DefineReportDataShipping.java,v 1.2 2006/11/13 08:18:43 suresh Exp $

//#CM690687
/*
 * Copyright 2000-2001 DAIFUKU Co.,Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of DAIFUKU Co.,Ltd.
 * Use is subject to license terms.
 */
package jp.co.daifuku.wms.base.system.display.web.definereportdata;
import jp.co.daifuku.bluedog.ui.control.Page;

//#CM690688
/**
 * Non variable class generated by a tool.
 * 
 * <BR>
 * <TABLE BORDER="1" CELLPADDING="3" CELLSPACING="0">
 * <TR BGCOLOR="#CCCCFF" CLASS="TableHeadingColor"><TD>Date</TD><TD>Name</TD><TD>Comment</TD></TR>
 * <TR><TD>2004/02/13</TD><TD>N.Sawa(DFK)</TD><TD>created this class</TD></TR>
 * </TABLE>
 * <BR>
 * @version $Revision: 1.2 $, $Date: 2006/11/13 08:18:43 $
 * @author  $Author: suresh $
 */
public class DefineReportDataShipping extends Page
{

	//#CM690689
	// Class variables -----------------------------------------------
	public jp.co.daifuku.bluedog.ui.control.Label lbl_SettingName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_SettingName" , "In_SettingName");
	public jp.co.daifuku.bluedog.ui.control.LinkButton btn_Help = jp.co.daifuku.bluedog.ui.control.LinkButtonFactory.getInstance("btn_Help" , "Help");
	public jp.co.daifuku.bluedog.ui.control.Message message = jp.co.daifuku.bluedog.ui.control.MessageFactory.getInstance("message" , "OperationMsg");
	public jp.co.daifuku.bluedog.ui.control.Tab tab_RptClmSet = jp.co.daifuku.bluedog.ui.control.TabFactory.getInstance("tab_RptClmSet" , "W_RptClm_SetShp");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Back = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Back" , "Back");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_ToMenu = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_ToMenu" , "To_Menu");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Valid1 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Valid1" , "W_Valid");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_DigitsUseLength1 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_DigitsUseLength1" , "W_DigitsUseLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLength1 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLength1" , "W_MaxLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Position1 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Position1" , "W_Position");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Valid2 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Valid2" , "W_Valid");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_DigitsUseLength2 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_DigitsUseLength2" , "W_DigitsUseLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLength2 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLength2" , "W_MaxLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Position2 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Position2" , "W_Position");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ShippingPlanDate = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ShippingPlanDate" , "W_ShippingPlanDate");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_CommonUseShpPlanDate = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_CommonUseShpPlanDate" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_ShpPlanDateLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_ShpPlanDateLen" , "W_ShpPlanDateLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_JavaSetShpPlanDate = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_JavaSetShpPlanDate" , "W_JavaSet");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_ShpPlanDatePst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_ShpPlanDatePst" , "W_ShpPlanDatePst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ShpPlanQtyPtl = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ShpPlanQtyPtl" , "W_ShpPlanQtyPtl");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_CommonUseShpPlanPtl = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_CommonUseShpPlanPtl" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_ShpPlanQtyPtlLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_ShpPlanQtyPtlLen" , "W_ShpPlanQtyPtlLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_JavaSetShpPlanPtl = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_JavaSetShpPlanPtl" , "W_JavaSet");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_ShpPlanQtyPtlPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_ShpPlanQtyPtlPst" , "W_ShpPlanQtyPtlPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_OrderDate = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_OrderDate" , "W_OrderDate");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_CommonUseOdd = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_CommonUseOdd" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_OdrgDateLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_OdrgDateLen" , "W_OdrgDateLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_JavaSetOdd = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_JavaSetOdd" , "W_JavaSet");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_OdrgDatePst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_OdrgDatePst" , "W_OdrgDatePst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_TCDCFlag = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_TCDCFlag" , "W_TCDCFlag");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_CommonUseTCDC = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_CommonUseTCDC" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_TCDCFlagLength = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_TCDCFlagLength" , "W_TCDCFlagLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_JavaSetTCDC = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_JavaSetTCDC" , "W_JavaSet");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_TCDCFlagPosition = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_TCDCFlagPosition" , "W_TCDCFlagPosition");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ConsignorCode = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ConsignorCode" , "W_ConsignorCode");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_CommonUseCnsgnrCd = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_CommonUseCnsgnrCd" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CnsgnrCdLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CnsgnrCdLen" , "W_CnsgnrCdLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_JavaSetCnsgnrCd = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_JavaSetCnsgnrCd" , "W_JavaSet");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CnsgnrCdPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CnsgnrCdPst" , "W_CnsgnrCdPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_SupplierCode = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_SupplierCode" , "W_SupplierCode");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_CommonUseSplCd = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_CommonUseSplCd" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_SplCdLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_SplCdLen" , "W_SplCdLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_JavaSetSplCd = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_JavaSetSplCd" , "W_JavaSet");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_SplCdPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_SplCdPst" , "W_SplCdPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ConsignorName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ConsignorName" , "W_ConsignorName");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_CommonUseCnsgnrNm = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_CommonUseCnsgnrNm" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CnsgnrNmLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CnsgnrNmLen" , "W_CnsgnrNmLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_JavaSetCnsgnrNm = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_JavaSetCnsgnrNm" , "W_JavaSet");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CnsgnrNmPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CnsgnrNmPst" , "W_CnsgnrNmPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_SupplierName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_SupplierName" , "W_SupplierName");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_CommonUseSplNm = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_CommonUseSplNm" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_SplNmLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_SplNmLen" , "W_SplNmLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_JavaSetSpl = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_JavaSetSpl" , "W_JavaSet");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_SplNmPstNm = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_SplNmPstNm" , "W_SplNmPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_CustomerCode = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_CustomerCode" , "W_CustomerCode");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_CommonUseCustCd = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_CommonUseCustCd" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CustCdLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CustCdLen" , "W_CustCdLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_JavaSetCustCd = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_JavaSetCustCd" , "W_JavaSet");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CustCdPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CustCdPst" , "W_CustCdPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_InstockTicketNo = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_InstockTicketNo" , "W_InstockTicketNo");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_CommonUseInstkTkt = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_CommonUseInstkTkt" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_InstkTktNoLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_InstkTktNoLen" , "W_InstkTktNoLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_JavaSetInstkTkt = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_JavaSetInstkTkt" , "W_JavaSet");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_InstkTktNoPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_InstkTktNoPst" , "W_InstkTktNoPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_CustomerName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_CustomerName" , "W_CustomerName");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_CommonUseCustNm = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_CommonUseCustNm" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CustNmLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CustNmLen" , "W_CustNmLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_JavaSetCustNm = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_JavaSetCustNm" , "W_JavaSet");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CustNmPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CustNmPst" , "W_CustNmPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_InstkTktLineNo = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_InstkTktLineNo" , "W_InstkTktLineNo");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_CommonUseInstkTktLine = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_CommonUseInstkTktLine" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_InstkTktLineNoLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_InstkTktLineNoLen" , "W_InstkTktLineNoLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_JavaSetInstkTktLine = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_JavaSetInstkTktLine" , "W_JavaSet");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_InstkTktLineNoPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_InstkTktLineNoPst" , "W_InstkTktLineNoPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_TicketNo = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_TicketNo" , "W_TicketNo");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_CommonUseTktNo = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_CommonUseTktNo" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_TicketNoLength = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_TicketNoLength" , "W_TicketNoLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_JavaSetTktNo = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_JavaSetTktNo" , "W_JavaSet");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_TicketNoPosition = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_TicketNoPosition" , "W_TicketNoPosition");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ShpQtyPtl = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ShpQtyPtl" , "W_ShpQtyPtl");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_CommonUseShpPtl = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_CommonUseShpPtl" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_ShpQtyPtlLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_ShpQtyPtlLen" , "W_ShpQtyPtlLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_JavaSetShpPtl = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_JavaSetShpPtl" , "W_JavaSet");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_ShpQtyPtlPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_ShpQtyPtlPst" , "W_ShpQtyPtlPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_TicketLineNo = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_TicketLineNo" , "W_TicketLineNo");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_CommonUseTktLineNo = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_CommonUseTktLineNo" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_TktLineNoLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_TktLineNoLen" , "W_TktLineNoLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_JavaSetTktLineNo = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_JavaSetTktLineNo" , "W_JavaSet");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_TktLineNoPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_TktLineNoPst" , "W_TktLineNoPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ShippingResultDate = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ShippingResultDate" , "W_ShippingResultDate");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_CommonUseShpRslt = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_CommonUseShpRslt" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_ShpRsltDateLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_ShpRsltDateLen" , "W_ShpRsltDateLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_JavaSetShpRslt = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_JavaSetShpRslt" , "W_JavaSet");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_ShpRsltDatePst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_ShpRsltDatePst" , "W_ShpRsltDatePst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ItemCode = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ItemCode" , "W_ItemCode");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_TktLineNoPstItemCo = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_TktLineNoPstItemCo" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_ItemCodeLength = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_ItemCodeLength" , "W_ItemCodeLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_JavaSetItemCo = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_JavaSetItemCo" , "W_JavaSet");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_ItemCodePosition = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_ItemCodePosition" , "W_ItemCodePosition");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ResultFlag = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ResultFlag" , "W_ResultFlag");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_CommonUseRsltFlg = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_CommonUseRsltFlg" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_ResultFlagLength = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_ResultFlagLength" , "W_ResultFlagLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_JavaSetRsltFlg = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_JavaSetRsltFlg" , "W_JavaSet");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_ResultFlagPosition = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_ResultFlagPosition" , "W_ResultFlagPosition");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_BundleItf = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_BundleItf" , "W_BundleItf");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_CommonUseBdlItf = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_CommonUseBdlItf" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_BundleItfLength = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_BundleItfLength" , "W_BundleItfLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_JavaSetBdlItf = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_JavaSetBdlItf" , "W_JavaSet");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_BundleItfPosition = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_BundleItfPosition" , "W_BundleItfPosition");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_UseByDate = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_UseByDate" , "W_UseByDate");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_CommonUseUseByDate = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_CommonUseUseByDate" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_UseByDateLength = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_UseByDateLength" , "W_UseByDateLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_JavaSetUseByDate = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_JavaSetUseByDate" , "W_JavaSet");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_UseByDatePosition = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_UseByDatePosition" , "W_UseByDatePosition");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_CaseItf = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_CaseItf" , "W_CaseItf");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_CommonUseCaseItf = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_CommonUseCaseItf" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CaseItfLength = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CaseItfLength" , "W_CaseItfLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_JavaSetCaseItf = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_JavaSetCaseItf" , "W_JavaSet");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CaseItfPosition = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CaseItfPosition" , "W_CaseItfPosition");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_BundleEntering = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_BundleEntering" , "W_BundleEntering");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_CommonUseBdlEtr = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_CommonUseBdlEtr" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_BdlEtrLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_BdlEtrLen" , "W_BdlEtrLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_JavaSetBdlEtr = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_JavaSetBdlEtr" , "W_JavaSet");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_BdlEtrPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_BdlEtrPst" , "W_BdlEtrPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_CaseEntering = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_CaseEntering" , "W_CaseEntering");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_CommonUseCaseEtr = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_CommonUseCaseEtr" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CaseEtrLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CaseEtrLen" , "W_CaseEtrLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_JavaSetCaseEtr = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_JavaSetCaseEtr" , "W_JavaSet");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CaseEtrPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CaseEtrPst" , "W_CaseEtrPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ItemName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ItemName" , "W_ItemName");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_W_CommonUseItemNm = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_W_CommonUseItemNm" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_ItemNameLength = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_ItemNameLength" , "W_ItemNameLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_JavaSetItemNm = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_JavaSetItemNm" , "W_JavaSet");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_ItemNamePosition = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_ItemNamePosition" , "W_ItemNamePosition");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Submit = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Submit" , "Submit");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Clear = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Clear" , "Clear");

}
//#CM690690
//end of class
