// $Id: DefineReportDataStorage.java,v 1.2 2006/11/13 08:18:40 suresh Exp $

//#CM691939
/*
 * Copyright 2000-2001 DAIFUKU Co.,Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of DAIFUKU Co.,Ltd.
 * Use is subject to license terms.
 */
package jp.co.daifuku.wms.base.system.display.web.definereportdata;
import jp.co.daifuku.bluedog.ui.control.Page;

//#CM691940
/**
 * Non variable class generated by a tool.
 * 
 * <BR>
 * <TABLE BORDER="1" CELLPADDING="3" CELLSPACING="0">
 * <TR BGCOLOR="#CCCCFF" CLASS="TableHeadingColor"><TD>Date</TD><TD>Name</TD><TD>Comment</TD></TR>
 * <TR><TD>2004/02/13</TD><TD>N.Sawa(DFK)</TD><TD>created this class</TD></TR>
 * </TABLE>
 * <BR>
 * @version $Revision: 1.2 $, $Date: 2006/11/13 08:18:40 $
 * @author  $Author: suresh $
 */
public class DefineReportDataStorage extends Page
{

	//#CM691941
	// Class variables -----------------------------------------------
	public jp.co.daifuku.bluedog.ui.control.Label lbl_SettingName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_SettingName" , "In_SettingName");
	public jp.co.daifuku.bluedog.ui.control.LinkButton btn_Help = jp.co.daifuku.bluedog.ui.control.LinkButtonFactory.getInstance("btn_Help" , "Help");
	public jp.co.daifuku.bluedog.ui.control.Message message = jp.co.daifuku.bluedog.ui.control.MessageFactory.getInstance("message" , "OperationMsg");
	public jp.co.daifuku.bluedog.ui.control.Tab tab_RptClmSetStrg = jp.co.daifuku.bluedog.ui.control.TabFactory.getInstance("tab_RptClmSetStrg" , "W_RptClm_SetStrg");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Back = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Back" , "Back");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_ToMenu = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_ToMenu" , "To_Menu");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Valid1 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Valid1" , "W_Valid");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_DigitsUseLength1 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_DigitsUseLength1" , "W_DigitsUseLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLength1 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLength1" , "W_MaxLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Position1 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Position1" , "W_Position");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Valid2 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Valid2" , "W_Valid");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_DigitsUseLength2 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_DigitsUseLength2" , "W_DigitsUseLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLength2 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLength2" , "W_MaxLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Position2 = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Position2" , "W_Position");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_StoragePlanDate = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_StoragePlanDate" , "W_StoragePlanDate");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_StrgPlanDate = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_StrgPlanDate" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_StrgPlanDateLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_StrgPlanDateLen" , "W_StrgPlanDateLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenStrgPlanDate = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenStrgPlanDate" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_StrgPlanDatePst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_StrgPlanDatePst" , "W_StrgPlanDatePst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ResultPieceQtyTwoByte = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ResultPieceQtyTwoByte" , "W_ResultPieceQtyTwoByte");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_RsltPieceQty = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_RsltPieceQty" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_RsltPieceQtyLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_RsltPieceQtyLen" , "W_RsltPiceQtyLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenRsltPieceQty = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenRsltPieceQty" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_RsltPieceQtyPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_RsltPieceQtyPst" , "W_RsltPiceQtyPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ConsignorCode = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ConsignorCode" , "W_ConsignorCode");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_CnsgnrCd = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_CnsgnrCd" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CnsgnrCdLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CnsgnrCdLen" , "W_CnsgnrCdLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenCnsgnrCd = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenCnsgnrCd" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CnsgnrCdPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CnsgnrCdPst" , "W_CnsgnrCdPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ResultCaseQtyTwoByte = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ResultCaseQtyTwoByte" , "W_ResultCaseQtyTwoByte");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_RsltCaseQty = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_RsltCaseQty" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_RsltCaseQtyLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_RsltCaseQtyLen" , "W_RsltCaseQtyLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenRsltCaseQty = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenRsltCaseQty" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_RsltCaseQtyPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_RsltCaseQtyPst" , "W_RsltCaseQtyPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ConsignorName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ConsignorName" , "W_ConsignorName");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_CnsgnrNm = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_CnsgnrNm" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CnsgnrNmLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CnsgnrNmLen" , "W_CnsgnrNmLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenCnsgnrNm = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenCnsgnrNm" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CnsgnrNmPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CnsgnrNmPst" , "W_CnsgnrNmPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_StorageResultDate = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_StorageResultDate" , "W_StorageResultDate");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_StrgRsltDate = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_StrgRsltDate" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_StrgRsltDateLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_StrgRsltDateLen" , "W_StrgRsltDateLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenStrgRsltDate = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenStrgRsltDate" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_StrgRsltDatePst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_StrgRsltDatePst" , "W_StrgRsltDatePst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ItemCode = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ItemCode" , "W_ItemCode");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_ItemCd = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_ItemCd" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_ItemCdLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_ItemCdLen" , "W_ItemCodeLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenItemCd = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenItemCd" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_ItemCdPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_ItemCdPst" , "W_ItemCodePosition");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ResultFlag = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ResultFlag" , "W_ResultFlag");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_RsltFlg = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_RsltFlg" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_RsltFlgLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_RsltFlgLen" , "W_ResultFlagLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenRsltFlg = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenRsltFlg" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_RsltFlgPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_RsltFlgPst" , "W_ResultFlagPosition");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_BundleItf = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_BundleItf" , "W_BundleItf");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_BundleItf = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_BundleItf" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_BundleItfLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_BundleItfLen" , "W_BundleItfLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenBundleItf = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenBundleItf" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_BundleItfPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_BundleItfPst" , "W_BundleItfPosition");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_UseByDate = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_UseByDate" , "W_UseByDate");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_UseByDate = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_UseByDate" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_UseByDateLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_UseByDateLen" , "W_UseByDateLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenUseByDate = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenUseByDate" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_UseByDatePst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_UseByDatePst" , "W_UseByDatePosition");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_CaseItf = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_CaseItf" , "W_CaseItf");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_CaseItf = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_CaseItf" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CaseItfLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CaseItfLen" , "W_CaseItfLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenCaseItf = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenCaseItf" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CaseItfPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CaseItfPst" , "W_CaseItfPosition");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_BundleEntering = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_BundleEntering" , "W_BundleEntering");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_BundleEtr = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_BundleEtr" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_BundleEtrLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_BundleEtrLen" , "W_BdlEtrLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenBundleEtr = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenBundleEtr" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_BundleEtrPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_BundleEtrPst" , "W_BdlEtrPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_CaseEntering = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_CaseEntering" , "W_CaseEntering");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_CaseEtr = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_CaseEtr" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CaseEtrLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CaseEtrLen" , "W_CaseEtrLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenCaseEtr = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenCaseEtr" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CaseEtrPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CaseEtrPst" , "W_CaseEtrPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ItemName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ItemName" , "W_ItemName");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_ItemNm = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_ItemNm" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_ItemNmLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_ItemNmLen" , "W_ItemNameLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenItemNm = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenItemNm" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_ItemNmPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_ItemNmPst" , "W_ItemNamePosition");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_StrgQtyPtl = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_StrgQtyPtl" , "W_StrgQtyPtl");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_StrgQtyPtl = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_StrgQtyPtl" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_StrgQtyPtlLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_StrgQtyPtlLen" , "W_StrgQtyPtlLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenStrgQtyPtl = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenStrgQtyPtl" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_StrgQtyPtlPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_StrgQtyPtlPst" , "W_StrgQtyPtlPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_PiceStrgLct = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_PiceStrgLct" , "W_PiceStrgLct");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_PieceStrgLct = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_PieceStrgLct" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_PieceStrgLctLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_PieceStrgLctLen" , "W_PiceStrgLctLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenPieceStrgLct = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenPieceStrgLct" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_PieceStrgLctPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_PieceStrgLctPst" , "W_PiceStrgLctPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_CaseStrgLct = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_CaseStrgLct" , "W_CaseStrgLct");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_CaseStrgLct = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_CaseStrgLct" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CaseStrgLctLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CaseStrgLctLen" , "W_CaseStrgLctLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenCaseStrgLct = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenCaseStrgLct" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CaseStrgLctPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CaseStrgLctPst" , "W_CaseStrgLctPst");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Submit = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Submit" , "Submit");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Clear = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Clear" , "Clear");

}
//#CM691942
//end of class
