// $Id: DefineReportDataStockMove.java,v 1.2 2006/11/13 08:18:41 suresh Exp $

//#CM691671
/*
 * Copyright 2000-2001 DAIFUKU Co.,Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of DAIFUKU Co.,Ltd.
 * Use is subject to license terms.
 */
package jp.co.daifuku.wms.base.system.display.web.definereportdata;
import jp.co.daifuku.bluedog.ui.control.Page;

//#CM691672
/**
 * Non variable class generated by a tool.
 * 
 * <BR>
 * <TABLE BORDER="1" CELLPADDING="3" CELLSPACING="0">
 * <TR BGCOLOR="#CCCCFF" CLASS="TableHeadingColor"><TD>Date</TD><TD>Name</TD><TD>Comment</TD></TR>
 * <TR><TD>2004/02/13</TD><TD>N.Sawa(DFK)</TD><TD>created this class</TD></TR>
 * </TABLE>
 * <BR>
 * @version $Revision: 1.2 $, $Date: 2006/11/13 08:18:41 $
 * @author  $Author: suresh $
 */
public class DefineReportDataStockMove extends Page
{

	//#CM691673
	// Class variables -----------------------------------------------
	public jp.co.daifuku.bluedog.ui.control.Label lbl_SettingName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_SettingName" , "In_SettingName");
	public jp.co.daifuku.bluedog.ui.control.LinkButton btn_Help = jp.co.daifuku.bluedog.ui.control.LinkButtonFactory.getInstance("btn_Help" , "Help");
	public jp.co.daifuku.bluedog.ui.control.Message message = jp.co.daifuku.bluedog.ui.control.MessageFactory.getInstance("message" , "OperationMsg");
	public jp.co.daifuku.bluedog.ui.control.Tab tab_RptClmSetStockMov = jp.co.daifuku.bluedog.ui.control.TabFactory.getInstance("tab_RptClmSetStockMov" , "W_RptClm_SetStockMov");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Back = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Back" , "Back");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_ToMenu = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_ToMenu" , "To_Menu");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Valid = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Valid" , "W_Valid");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_DigitsUseLength = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_DigitsUseLength" , "W_DigitsUseLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLen = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLen" , "W_MaxLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Position = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Position" , "W_Position");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ConsignorCode = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ConsignorCode" , "W_ConsignorCode");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_CnsgnrCd = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_CnsgnrCd" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CnsgnrCdLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CnsgnrCdLen" , "W_CnsgnrCdLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenCnsgnrCd = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenCnsgnrCd" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CnsgnrCdPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CnsgnrCdPst" , "W_CnsgnrCdPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ConsignorName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ConsignorName" , "W_ConsignorName");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_CnsgnrNm = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_CnsgnrNm" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CnsgnrNmLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CnsgnrNmLen" , "W_CnsgnrNmLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenCnsgnrNm = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenCnsgnrNm" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CnsgnrNmPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CnsgnrNmPst" , "W_CnsgnrNmPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ItemCode = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ItemCode" , "W_ItemCode");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_ItemCd = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_ItemCd" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_ItemCdLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_ItemCdLen" , "W_ItemCodeLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenItemCd = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenItemCd" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_ItemCdPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_ItemCdPst" , "W_ItemCodePosition");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ItemName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ItemName" , "W_ItemName");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_ItemNm = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_ItemNm" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_ItemNmLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_ItemNmLen" , "W_ItemNameLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenItemNm = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenItemNm" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_ItemNmPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_ItemNmPst" , "W_ItemNamePosition");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_CaseEntering = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_CaseEntering" , "W_CaseEntering");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_CaseEtr = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_CaseEtr" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CaseEtrLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CaseEtrLen" , "W_CaseEtrLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenCaseEtr = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenCaseEtr" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_CaseEtrPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_CaseEtrPst" , "W_CaseEtrPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MoveQtyPieceTotal = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MoveQtyPieceTotal" , "W_MoveQtyPieceTotal");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_MovQtyPtl = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_MovQtyPtl" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_MovQtyPtlLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_MovQtyPtlLen" , "W_MovQtyPtlLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenMovQtyPtl = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenMovQtyPtl" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_MovQtyPtlPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_MovQtyPtlPst" , "W_MovQtyPtlPst");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_FromMoveLocation = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_FromMoveLocation" , "W_FromMoveLocation");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_FromMovLct = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_FromMovLct" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_FromMovLctLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_FromMovLctLen" , "W_FrmMovLctLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenFromMovLct = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenFromMovLct" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_FromMovLctPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_FromMovLctPst" , "W_FrmMovLctPos");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ToMoveLocation = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ToMoveLocation" , "W_ToMoveLocation");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_ToMovLct = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_ToMovLct" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_ToMovLctLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_ToMovLctLen" , "W_ToMovLctLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenToMovLct = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenToMovLct" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_ToMovLctPst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_ToMovLctPst" , "W_ToMovLctPos");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MoveResultDate = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MoveResultDate" , "W_MoveResultDate");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_MovRsltDate = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_MovRsltDate" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_MovRsltDateLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_MovRsltDateLen" , "W_MovRsltDateLen");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenMovRsltDate = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenMovRsltDate" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_MovRsltDatePst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_MovRsltDatePst" , "W_MovRsltDatePos");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_UseByDate = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_UseByDate" , "W_UseByDate");
	public jp.co.daifuku.bluedog.ui.control.CheckBox chk_UseByDate = jp.co.daifuku.bluedog.ui.control.CheckBoxFactory.getInstance("chk_UseByDate" , "W_CommonUse");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_UseByDateLen = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_UseByDateLen" , "W_UseByDateLength");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_MaxLenUseByDate = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_MaxLenUseByDate" , "W_MaxLen");
	public jp.co.daifuku.bluedog.ui.control.NumberTextBox txt_UseByDatePst = jp.co.daifuku.bluedog.ui.control.NumberTextBoxFactory.getInstance("txt_UseByDatePst" , "W_UseByDatePosition");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Submit = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Submit" , "Submit");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Clear = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Clear" , "Clear");

}
//#CM691674
//end of class
