// $Id: DefineReportData.java,v 1.2 2006/11/13 08:18:49 suresh Exp $

//#CM688617
/*
 * Copyright 2000-2001 DAIFUKU Co.,Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of DAIFUKU Co.,Ltd.
 * Use is subject to license terms.
 */
package jp.co.daifuku.wms.base.system.display.web.definereportdata;
import jp.co.daifuku.bluedog.ui.control.Page;

//#CM688618
/**
 * Non variable class generated by a tool.
 * 
 * <BR>
 * <TABLE BORDER="1" CELLPADDING="3" CELLSPACING="0">
 * <TR BGCOLOR="#CCCCFF" CLASS="TableHeadingColor"><TD>Date</TD><TD>Name</TD><TD>Comment</TD></TR>
 * <TR><TD>2004/02/13</TD><TD>N.Sawa(DFK)</TD><TD>created this class</TD></TR>
 * </TABLE>
 * <BR>
 * @version $Revision: 1.2 $, $Date: 2006/11/13 08:18:49 $
 * @author  $Author: suresh $
 */
public class DefineReportData extends Page
{

	//#CM688619
	// Class variables -----------------------------------------------
	public jp.co.daifuku.bluedog.ui.control.Label lbl_SettingName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_SettingName" , "In_SettingName");
	public jp.co.daifuku.bluedog.ui.control.LinkButton btn_Help = jp.co.daifuku.bluedog.ui.control.LinkButtonFactory.getInstance("btn_Help" , "Help");
	public jp.co.daifuku.bluedog.ui.control.Message message = jp.co.daifuku.bluedog.ui.control.MessageFactory.getInstance("message" , "OperationMsg");
	public jp.co.daifuku.bluedog.ui.control.Tab tab_RptClmSet = jp.co.daifuku.bluedog.ui.control.TabFactory.getInstance("tab_RptClmSet" , "W_RptClm_Set");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_ToMenu = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_ToMenu" , "To_Menu");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_WorkerCode = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_WorkerCode" , "W_WorkerCode");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_WorkerCode = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_WorkerCode" , "W_WorkerCode");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Password = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Password" , "W_Password");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_Password = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_Password" , "W_Password");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_ResultInstock = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_ResultInstock" , "W_Result_Instock");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_ResultStorage = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_ResultStorage" , "W_Result_Storage");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_ResultRetrieval = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_ResultRetrieval" , "W_Result_Retrieval");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_ResultPicking = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_ResultPicking" , "W_Result_Picking");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_ResultShipping = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_ResultShipping" , "W_Result_Shipping");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_ResultStockMove = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_ResultStockMove" , "W_Result_StockMove");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_ResultInventory = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_ResultInventory" , "W_Result_Inventory");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_ResultNoPlanStrg = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_ResultNoPlanStrg" , "W_Result_NoPlanStrg");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_ResultNoPlanRtrivl = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_ResultNoPlanRtrivl" , "W_Result_NoPlanRtrivl");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Next = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Next" , "Next");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Clear = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Clear" , "Clear");

}
//#CM688620
//end of class
