// $Id: AsWorkMaintenance.java,v 1.2 2006/10/26 04:58:58 suresh Exp $

//#CM37780
/*
 * Copyright 2000-2001 DAIFUKU Co.,Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of DAIFUKU Co.,Ltd.
 * Use is subject to license terms.
 */
package jp.co.daifuku.wms.asrs.display.web.asrsworkmaintenance;
import jp.co.daifuku.bluedog.ui.control.Page;

//#CM37781
/**
 * Class generated by tool. Do not alter.
 * 
 * <BR>
 * <TABLE BORDER="1" CELLPADDING="3" CELLSPACING="0">
 * <TR BGCOLOR="#CCCCFF" CLASS="TableHeadingColor"><TD>Date</TD><TD>Name</TD><TD>Comment</TD></TR>
 * <TR><TD>2004/02/13</TD><TD>N.Sawa(DFK)</TD><TD>created this class</TD></TR>
 * </TABLE>
 * <BR>
 * @version $Revision: 1.2 $, $Date: 2006/10/26 04:58:58 $
 * @author  $Author: suresh $
 */
public class AsWorkMaintenance extends Page
{

	//#CM37782
	// Class variables -----------------------------------------------
	public jp.co.daifuku.bluedog.ui.control.Label lbl_SettingName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_SettingName" , "In_SettingName");
	public jp.co.daifuku.bluedog.ui.control.LinkButton btn_Help = jp.co.daifuku.bluedog.ui.control.LinkButtonFactory.getInstance("btn_Help" , "Help");
	public jp.co.daifuku.bluedog.ui.control.Message message = jp.co.daifuku.bluedog.ui.control.MessageFactory.getInstance("message" , "OperationMsg");
	public jp.co.daifuku.bluedog.ui.control.Tab tab_Maintenance = jp.co.daifuku.bluedog.ui.control.TabFactory.getInstance("tab_Maintenance" , "W_Maintenance");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_ToMenu = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_ToMenu" , "To_Menu");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_WokerCode = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_WokerCode" , "W_WorkerCode");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_WorkderCode = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_WorkderCode" , "W_WorkerCode");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Password = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Password" , "W_Password");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_Password = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_Password" , "W_Password");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_WorkPlaceStation = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_WorkPlaceStation" , "W_WorkPlaceStation");
	public jp.co.daifuku.bluedog.ui.control.PullDown pul_WorkPlace = jp.co.daifuku.bluedog.ui.control.PullDownFactory.getInstance("pul_WorkPlace" , "W_WorkPlace");
	public jp.co.daifuku.bluedog.ui.control.LinkedPullDown pul_Station = jp.co.daifuku.bluedog.ui.control.LinkedPullDownFactory.getInstance("pul_Station" , "W_Station");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Query = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Query" , "P_Query");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Setting = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Setting" , "Setting");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Reflesh = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Reflesh" , "Reflesh");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Clear = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Clear" , "Clear");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Work = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Work" , "W_Work");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_Maintenance_NoSend = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_Maintenance_NoSend" , "W_Maintenance_NoSend");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_Maintenance_Complete = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_Maintenance_Complete" , "W_Maintenance_Complete");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_Maintenance_CarryDelete = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_Maintenance_CarryDelete" , "W_Maintenance_CarryDelete");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Carry = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Carry" , "W_Carry");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_JavaSetCarryForm = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_JavaSetCarryForm" , "W_JavaSet");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_JavaSetCarryTo = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_JavaSetCarryTo" , "W_JavaSet");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Station_Stop = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Station_Stop" , "Station_Stop");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Station_Start = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Station_Start" , "Station_Start");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_LocationNo = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_LocationNo" , "W_LocationNo");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_JavaSetLocationNo = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_JavaSetLocationNo" , "W_JavaSet");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_WorkFlag = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_WorkFlag" , "W_CarryKind");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_JavaSetWorkFlag = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_JavaSetWorkFlag" , "W_JavaSet");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_WorkStatus = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_WorkStatus" , "W_CmdStatus");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_JavaSetWorkStatus = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_JavaSetWorkStatus" , "W_JavaSet");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_WorkClass = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_WorkClass" , "W_WorkClass");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_JavaSetWorkClass = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_JavaSetWorkClass" , "W_JavaSet");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_RetrievalDetails = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_RetrievalDetails" , "W_RetrievalDetails");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_JavaSetRetrievalDetails = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_JavaSetRetrievalDetails" , "W_JavaSet");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_WorkNo = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_WorkNo" , "W_WorkNo");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_JavaSetWorkNo = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_JavaSetWorkNo" , "W_JavaSet");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_CarryKey = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_CarryKey" , "W_CarryKey");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_JavaSetCarryKey = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_JavaSetCarryKey" , "W_JavaSet");

}
//#CM37783
//end of class
