// $Id: EmptyBucketAddModeSetting.java,v 1.1 2007/12/13 06:25:10 administrator Exp $

/*
 * Copyright 2000-2001 DAIFUKU Co.,Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of DAIFUKU Co.,Ltd.
 * Use is subject to license terms.
 */
package jp.co.daifuku.wms.YkkGMAX.System;
import jp.co.daifuku.bluedog.ui.control.Page;

/**
 * This class can not be changed and it is generated by ScreenGenerator.
 * 
 * <BR>
 * <TABLE BORDER="1" CELLPADDING="3" CELLSPACING="0">
 * <TR BGCOLOR="#CCCCFF" CLASS="TableHeadingColor"><TD>Date</TD><TD>Name</TD><TD>Comment</TD></TR>
 * <TR><TD>2004/02/13</TD><TD>N.Sawa(DFK)</TD><TD>created this class</TD></TR>
 * </TABLE>
 * <BR>
 * @version $Revision: 1.1 $, $Date: 2007/12/13 06:25:10 $
 * @author  $Author: administrator $
 */
public class EmptyBucketAddModeSetting extends Page
{

	// Class variables -----------------------------------------------
	public jp.co.daifuku.bluedog.ui.control.Label lbl_SettingName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_SettingName" , "YKK_LBL_EmptyBucketAddModeSetting");
	public jp.co.daifuku.bluedog.ui.control.LinkButton btn_Help = jp.co.daifuku.bluedog.ui.control.LinkButtonFactory.getInstance("btn_Help" , "Help");
	public jp.co.daifuku.bluedog.ui.control.Message message = jp.co.daifuku.bluedog.ui.control.MessageFactory.getInstance("message" , "OperationMsg");
	public jp.co.daifuku.bluedog.ui.control.Tab tab = jp.co.daifuku.bluedog.ui.control.TabFactory.getInstance("tab" , "YKK_TAB_Setting");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_ToMenu = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_ToMenu" , "To_Menu");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_StockinStation = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_StockinStation" , "YKK_LBL_StockinStation");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Status = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Status" , "YKK_LBL_Status");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ModeChange = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ModeChange" , "YKK_LBL_ModeChange");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_DiecastStockinStation = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_DiecastStockinStation" , "YKK_LBL_DiecastStockinStation");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_DiecastStockinStStatus = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_DiecastStockinStStatus" , "YKK_TXT_Status_RO");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_Stockin_Diecast = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_Stockin_Diecast" , "YKK_RDO_StockinChecked_Diecast");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_BucketAddMode_Diecast = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_BucketAddMode_Diecast" , "YKK_RDO_BucketAddMode_Diecast");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_AssemblyStockinStation = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_AssemblyStockinStation" , "YKK_LBL_AssemblyStockinStation");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_AssemblyStockinStStatus = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_AssemblyStockinStStatus" , "YKK_TXT_Status_RO");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_Stockin_Assembly = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_Stockin_Assembly" , "YKK_RDO_StockinChecked_Assembly");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_BucketAddMode_Assembly = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_BucketAddMode_Assembly" , "YKK_RDO_BucketAddMode_Assembly");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_SIStockinStation = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_SIStockinStation" , "YKK_LBL_SIStockinStation");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_SIStockinStStatus = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_SIStockinStStatus" , "YKK_TXT_Status_RO");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_Stockin_SI = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_Stockin_SI" , "YKK_RDO_StockinChecked_SI");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_BucketAddMode_SI = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_BucketAddMode_SI" , "YKK_RDO_BucketAddMode_SI");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Set = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Set" , "YKK_BTN_Set");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Show = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Show" , "YKK_BTN_Show");

}
//end of class
