// $Id: WorkStartStopSetting.java,v 1.1 2007/12/13 06:25:10 administrator Exp $

/*
 * Copyright 2000-2001 DAIFUKU Co.,Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of DAIFUKU Co.,Ltd.
 * Use is subject to license terms.
 */
package jp.co.daifuku.wms.YkkGMAX.System;
import jp.co.daifuku.bluedog.ui.control.Page;

/**
 * This class can not be changed and it is generated by ScreenGenerator.
 * 
 * <BR>
 * <TABLE BORDER="1" CELLPADDING="3" CELLSPACING="0">
 * <TR BGCOLOR="#CCCCFF" CLASS="TableHeadingColor"><TD>Date</TD><TD>Name</TD><TD>Comment</TD></TR>
 * <TR><TD>2004/02/13</TD><TD>N.Sawa(DFK)</TD><TD>created this class</TD></TR>
 * </TABLE>
 * <BR>
 * @version $Revision: 1.1 $, $Date: 2007/12/13 06:25:10 $
 * @author  $Author: administrator $
 */
public class WorkStartStopSetting extends Page
{

	// Class variables -----------------------------------------------
	public jp.co.daifuku.bluedog.ui.control.Label lbl_SettingName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_SettingName" , "YKK_LBL_WorkStartStopSetting");
	public jp.co.daifuku.bluedog.ui.control.LinkButton btn_Help = jp.co.daifuku.bluedog.ui.control.LinkButtonFactory.getInstance("btn_Help" , "Help");
	public jp.co.daifuku.bluedog.ui.control.Message message = jp.co.daifuku.bluedog.ui.control.MessageFactory.getInstance("message" , "OperationMsg");
	public jp.co.daifuku.bluedog.ui.control.Tab tab = jp.co.daifuku.bluedog.ui.control.TabFactory.getInstance("tab" , "YKK_TAB_Setting");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_ToMenu = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_ToMenu" , "To_Menu");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Mode = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Mode" , "YKK_LBL_Mode");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_Normal = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_Normal" , "YKK_RDO_NormalChecked");
	public jp.co.daifuku.bluedog.ui.control.RadioButton rdo_DataHolding = jp.co.daifuku.bluedog.ui.control.RadioButtonFactory.getInstance("rdo_DataHolding" , "YKK_RDO_DataHolding");
	public jp.co.daifuku.bluedog.ui.control.ListCell lst_WorkStartStopSetting = jp.co.daifuku.bluedog.ui.control.ListCellFactory.getInstance("lst_WorkStartStopSetting" , "YKK_LST_WorkStartStopSetting");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Online = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Online" , "YKK_BTN_Online");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Offline = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Offline" , "YKK_BTN_Offline");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_ForceOffline = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_ForceOffline" , "YKK_BTN_ForceOffline");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_WorkView = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_WorkView" , "YKK_BTN_WorkView_POPUP");

}
//end of class
