// $Id: LoadDataEnvironment.java,v 1.2 2006/11/13 08:21:16 suresh Exp $

//#CM693572
/*
 * Copyright 2000-2001 DAIFUKU Co.,Ltd. All Rights Reserved.
 *
 * This software is the proprietary information of DAIFUKU Co.,Ltd.
 * Use is subject to license terms.
 */
package jp.co.daifuku.wms.base.system.display.web.loaddataenvironment;
import jp.co.daifuku.bluedog.ui.control.Page;

//#CM693573
/**
 * Non variable class generated by a tool.
 * 
 * <BR>
 * <TABLE BORDER="1" CELLPADDING="3" CELLSPACING="0">
 * <TR BGCOLOR="#CCCCFF" CLASS="TableHeadingColor"><TD>Date</TD><TD>Name</TD><TD>Comment</TD></TR>
 * <TR><TD>2004/02/13</TD><TD>N.Sawa(DFK)</TD><TD>created this class</TD></TR>
 * </TABLE>
 * <BR>
 * @version $Revision: 1.2 $, $Date: 2006/11/13 08:21:16 $
 * @author  $Author: suresh $
 */
public class LoadDataEnvironment extends Page
{

	//#CM693574
	// Class variables -----------------------------------------------
	public jp.co.daifuku.bluedog.ui.control.Label lbl_SettingName = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_SettingName" , "In_SettingName");
	public jp.co.daifuku.bluedog.ui.control.LinkButton btn_Help = jp.co.daifuku.bluedog.ui.control.LinkButtonFactory.getInstance("btn_Help" , "Help");
	public jp.co.daifuku.bluedog.ui.control.Message message = jp.co.daifuku.bluedog.ui.control.MessageFactory.getInstance("message" , "OperationMsg");
	public jp.co.daifuku.bluedog.ui.control.Tab tab_Set = jp.co.daifuku.bluedog.ui.control.TabFactory.getInstance("tab_Set" , "W_Set");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_ToMenu = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_ToMenu" , "To_Menu");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_WorkerCode = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_WorkerCode" , "W_WorkerCode");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_WorkerCode = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_WorkerCode" , "W_WorkerCode");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_Password = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_Password" , "W_Password");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_Password = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_Password" , "W_Password");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_InstkPlanFld = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_InstkPlanFld" , "W_InstkPlanFld");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_InstkPlanFld = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_InstkPlanFld" , "W_InstkPlanFld");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_ReferenceInstk = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_ReferenceInstk" , "W_Reference");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_InstkPlanFileNm = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_InstkPlanFileNm" , "W_InstkPlanFileNm");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_InstkPlanFileNm = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_InstkPlanFileNm" , "W_InstkPlanFileNm");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_StrgPlanFld = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_StrgPlanFld" , "W_StrgPlanFld");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_StrgPlanFld = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_StrgPlanFld" , "W_StrgPlanFld");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_ReferenceStrg = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_ReferenceStrg" , "W_Reference");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_StrgPlanFileNm = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_StrgPlanFileNm" , "W_StrgPlanFileNm");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_StrgPlanFileNm = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_StrgPlanFileNm" , "W_StrgPlanFileNm");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_RtrivlPlanFld = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_RtrivlPlanFld" , "W_RtrivlPlanFld");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_RtrivlPlanFld = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_RtrivlPlanFld" , "W_RtrivlPlanFld");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_ReferenceRtrivl = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_ReferenceRtrivl" , "W_Reference");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_RtrivlPlanFileNm = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_RtrivlPlanFileNm" , "W_RtrivlPlanFileNm");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_RtrivlPlanFileNm = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_RtrivlPlanFileNm" , "W_RtrivlPlanFileNm");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_PickPlanDataFld = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_PickPlanDataFld" , "W_PickPlanDataFld");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_PickPlanFld = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_PickPlanFld" , "W_PickPlanFld");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_ReferencePick = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_ReferencePick" , "W_Reference");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_PickPlanDataFileNm = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_PickPlanDataFileNm" , "W_PickPlanDataFileNm");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_PickPlanFileNm = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_PickPlanFileNm" , "W_PickPlanFileNm");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ShpPlanDataFld = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ShpPlanDataFld" , "W_ShpPlanDataFld");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_ShpPlanFld = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_ShpPlanFld" , "W_ShpPlanFld");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_ReferenceShp = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_ReferenceShp" , "W_Reference");
	public jp.co.daifuku.bluedog.ui.control.Label lbl_ShpPlanFileNm = jp.co.daifuku.bluedog.ui.control.LabelFactory.getInstance("lbl_ShpPlanFileNm" , "W_ShpPlanFileNm");
	public jp.co.daifuku.bluedog.ui.control.FreeTextBox txt_ShpPlanFileNm = jp.co.daifuku.bluedog.ui.control.FreeTextBoxFactory.getInstance("txt_ShpPlanFileNm" , "W_ShpPlanFileNm");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Submit = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Submit" , "Submit");
	public jp.co.daifuku.bluedog.ui.control.SubmitButton btn_Clear = jp.co.daifuku.bluedog.ui.control.SubmitButtonFactory.getInstance("btn_Clear" , "Clear");

}
//#CM693575
//end of class
